# Signal categories #
HH_DL_resolved1b_GGF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11GGF_DNNOutput_GGF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11GGF_DNNOutput_GGF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11GGF_DNNOutput_GGF
HH_DL_resolved1b_VBF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11VBF_DNNOutput_VBF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11VBF_DNNOutput_VBF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11VBF_DNNOutput_VBF

HH_DL_resolved2b_GGF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11GGF_DNNOutput_GGF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11GGF_DNNOutput_GGF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11GGF_DNNOutput_GGF
HH_DL_resolved2b_VBF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11VBF_DNNOutput_VBF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11VBF_DNNOutput_VBF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11VBF_DNNOutput_VBF

HH_DL_boosted_GGF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11GGF_DNNOutput_GGF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11GGF_DNNOutput_GGF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11GGF_DNNOutput_GGF
HH_DL_boosted_VBF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11VBF_DNNOutput_VBF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11VBF_DNNOutput_VBF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11VBF_DNNOutput_VBF

HH_SL_resolved1b_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01GGF_DNNOutput_GGF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01GGF_DNNOutput_GGF

HH_SL_resolved1b_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01VBF_DNNOutput_VBF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01VBF_DNNOutput_VBF

HH_SL_resolved2b_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01GGF_DNNOutput_GGF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01GGF_DNNOutput_GGF

HH_SL_resolved2b_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01VBF_DNNOutput_VBF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01VBF_DNNOutput_VBF

HH_SL_boosted_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01GGF_DNNOutput_GGF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01GGF_DNNOutput_GGF

HH_SL_boosted_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01VBF_DNNOutput_VBF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01VBF_DNNOutput_VBF




# Background categories #

HH_DL_inclusive_DY_VVV:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11DY_DNNOutput_DY
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11DY_DNNOutput_DY
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11DY_DNNOutput_DY
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11DY_DNNOutput_DY
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11DY_DNNOutput_DY
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11DY_DNNOutput_DY
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11VVV_DNNOutput_VVV
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11VVV_DNNOutput_VVV
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11VVV_DNNOutput_VVV
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11VVV_DNNOutput_VVV
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11VVV_DNNOutput_VVV
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11VVV_DNNOutput_VVV
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11DY_DNNOutput_DY
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11DY_DNNOutput_DY
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11DY_DNNOutput_DY
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11VVV_DNNOutput_VVV
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11VVV_DNNOutput_VVV
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11VVV_DNNOutput_VVV


HH_DL_resolved_other:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11TT_DNNOutput_TT
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11TT_DNNOutput_TT
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11TT_DNNOutput_TT
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11TT_DNNOutput_TT
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11TT_DNNOutput_TT
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11TT_DNNOutput_TT
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11ST_DNNOutput_ST
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11ST_DNNOutput_ST
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11ST_DNNOutput_ST
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11ST_DNNOutput_ST
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11ST_DNNOutput_ST
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11ST_DNNOutput_ST
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11TTVX_DNNOutput_TTVX
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11TTVX_DNNOutput_TTVX
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11TTVX_DNNOutput_TTVX
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11TTVX_DNNOutput_TTVX
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11TTVX_DNNOutput_TTVX
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11TTVX_DNNOutput_TTVX
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11Rare_DNNOutput_Rare
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11Rare_DNNOutput_Rare
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11Rare_DNNOutput_Rare
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11Rare_DNNOutput_Rare
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11Rare_DNNOutput_Rare
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11Rare_DNNOutput_Rare
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11H_DNNOutput_H
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11H_DNNOutput_H
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags11H_DNNOutput_H
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11H_DNNOutput_H
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11H_DNNOutput_H
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag11H_DNNOutput_H

HH_DL_boosted_other:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11TT_DNNOutput_TT
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11TT_DNNOutput_TT
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11TT_DNNOutput_TT
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11TTVX_DNNOutput_TTVX
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11TTVX_DNNOutput_TTVX
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11TTVX_DNNOutput_TTVX
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11Rare_DNNOutput_Rare
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11Rare_DNNOutput_Rare
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11Rare_DNNOutput_Rare
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11ST_DNNOutput_ST
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11ST_DNNOutput_ST
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11ST_DNNOutput_ST
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11H_DNNOutput_H
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11H_DNNOutput_H
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag11H_DNNOutput_H


HH_SL_inclusive_WJets:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01WJets_DNNOutput_WJets

HH_SL_inclusive_other:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01ST_DNNOutput_ST
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01ST_DNNOutput_ST
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01ST_DNNOutput_ST

HH_SL_resolved_TopH:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01H_DNNOutput_H
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01H_DNNOutput_H

HH_SL_boosted_TopH:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01H_DNNOutput_H
