# Signal categories #
HH_SL_resolved1b_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03GGF_DNNOutput_GGF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03GGF_DNNOutput_GGF

HH_SL_resolved1b_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03VBF_DNNOutput_VBF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03VBF_DNNOutput_VBF

HH_SL_resolved2b_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03GGF_DNNOutput_GGF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03GGF_DNNOutput_GGF

HH_SL_resolved2b_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03VBF_DNNOutput_VBF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03VBF_DNNOutput_VBF

HH_SL_boosted_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03GGF_DNNOutput_GGF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03GGF_DNNOutput_GGF

HH_SL_boosted_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03VBF_DNNOutput_VBF
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03VBF_DNNOutput_VBF


# Background categories #

HH_SL_inclusive_wjets_other:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03Other_DNNOutput_Other

HH_SL_resolved_TopH:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03H_DNNOutput_H
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03H_DNNOutput_H
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03ST_DNNOutput_ST
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b03ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b03ST_DNNOutput_ST

HH_SL_boosted_TopH:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03H_DNNOutput_H
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted03ST_DNNOutput_ST
