# Signal categories #
HH_SL_e_resolved1b_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01GGF_DNNOutput_GGF
HH_SL_m_resolved1b_GGF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01GGF_DNNOutput_GGF

HH_SL_e_resolved1b_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01VBF_DNNOutput_VBF
HH_SL_m_resolved1b_VBF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01VBF_DNNOutput_VBF

HH_SL_e_resolved2b_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01GGF_DNNOutput_GGF
HH_SL_m_resolved2b_GGF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01GGF_DNNOutput_GGF

HH_SL_e_resolved2b_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01VBF_DNNOutput_VBF
HH_SL_m_resolved2b_VBF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01VBF_DNNOutput_VBF

HH_SL_e_boosted_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01GGF_DNNOutput_GGF
HH_SL_m_boosted_GGF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01GGF_DNNOutput_GGF

HH_SL_e_boosted_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01VBF_DNNOutput_VBF
HH_SL_m_boosted_VBF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01VBF_DNNOutput_VBF


# Background categories #
HH_SL_e_inclusive_WJets:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01WJets_DNNOutput_WJets
HH_SL_m_inclusive_WJets:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01WJets_DNNOutput_WJets

HH_SL_e_inclusive_other:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01ST_DNNOutput_ST
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01ST_DNNOutput_ST
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01ST_DNNOutput_ST
HH_SL_m_inclusive_other:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01ST_DNNOutput_ST

HH_SL_e_resolved_TopH:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01H_DNNOutput_H
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01H_DNNOutput_H
HH_SL_m_resolved_TopH:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b01H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b01H_DNNOutput_H

HH_SL_e_boosted_TopH:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01H_DNNOutput_H
HH_SL_m_boosted_TopH:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted01H_DNNOutput_H
