  limits_combined:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1"
    submit :  
      time: '1-00:00:00'
      mem : 9000
    combine_bins: True
    combine_eras: True
    split_eras: True
    extern: 
      txtFiles: 
        2016: 
          - /nfs/scratch/fynu/fbury/hig-21-005/resonant/sl/2016/{spin}/datacard_hh_bbww_sl_all_{mass}_{spin}_2016.txt
        2017: 
          - /nfs/scratch/fynu/fbury/hig-21-005/resonant/sl/2017/{spin}/datacard_hh_bbww_sl_all_{mass}_{spin}_2017.txt
        2018: 
          - /nfs/scratch/fynu/fbury/hig-21-005/resonant/sl/2018/{spin}/datacard_hh_bbww_sl_all_{mass}_{spin}_2018.txt
      rootFiles:
        - /home/ucl/cp3/fbury/scratch/hig-21-005/resonant/sl/*/{spin}/*{mass}*root
    bins:
      - HH_DL_{mass}_resolved1b_GGF
      - HH_DL_{mass}_resolved2b_GGF
      - HH_DL_{mass}_boosted_GGF
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
  limits_SL:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1"
    submit :  
      time: '1-00:00:00'
      mem : 9000
    combine_eras: True
    combine_bins: True
    split_eras: True
    extern: 
      txtFiles: 
        2016: 
          - /nfs/scratch/fynu/fbury/hig-21-005/resonant/sl/2016/{spin}/datacard_hh_bbww_sl_all_{mass}_{spin}_2016.txt
        2017: 
          - /nfs/scratch/fynu/fbury/hig-21-005/resonant/sl/2017/{spin}/datacard_hh_bbww_sl_all_{mass}_{spin}_2017.txt
        2018: 
          - /nfs/scratch/fynu/fbury/hig-21-005/resonant/sl/2018/{spin}/datacard_hh_bbww_sl_all_{mass}_{spin}_2018.txt
      rootFiles:
        - /home/ucl/cp3/fbury/scratch/hig-21-005/resonant/sl/*/{spin}/*{mass}*root
    bins: []
  limits_DL:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1"
    submit :  
      time: '1-00:00:00'
      mem : 9000
    combine_bins: True
    combine_eras: True
    split_eras: True
    bins:
      - HH_DL_{mass}_resolved1b_GGF
      - HH_DL_{mass}_resolved2b_GGF
      - HH_DL_{mass}_boosted_GGF
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other

  gof:
    mode: gof
    command: "combine -M GoodnessOfFit --algo=saturated --toysFrequentist"
    toys: 500
    toys-per-job: 10
    combine_bins: True
    combine_eras: True
    split_bins: True
    split_eras: True
    plotting:
      n_bins        : 32
      #left_margin   : 200
      #right_margin  : 20
    submit :  
      time: '0-02:00:00'
      mem : 3000
    bins:
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
  pulls:
    mode: pulls_impacts
    command: "combine -M MultiDimFit --verbose 3 --mass 125.0 --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-6000.0,6000.0 --robustFit 1"
    mc_stats: False
    use_snapshot: True
    unblind: True
    combine_bins: True
    combine_eras: True
    submit :  
      time: '0-02:00:00'
      mem : 3000
    plotting:
      left_margin           : 400
      right_margin          : 20
      label_size            : 18
      parameters_per_page   : 35
      order_by_impact       : True
    bins:
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other


  impacts:
    mode: pulls_impacts
    command: "combine -M MultiDimFit --verbose 3 --mass 125.0 --redefineSignalPOIs r --setParameters r=1.0 --robustFit 1"
    mc_stats: False
    use_snapshot: True
    combine_bins: True
    combine_eras: True
    submit :  
      time: '0-06:00:00'
      mem : 3000
    plotting:
      left_margin           : 400
      right_margin          : 20
      label_size            : 18
      parameters_per_page   : 35
      order_by_impact       : True
    bins:
      - HH_DL_{mass}_resolved1b_GGF
      - HH_DL_{mass}_resolved2b_GGF
      - HH_DL_{mass}_boosted_GGF
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
  impacts_unblinded:
    mode: pulls_impacts
    command: "combine -M MultiDimFit --verbose 3 --mass 125.0 --redefineSignalPOIs r --setParameters r=1.0  --robustFit 1"
    mc_stats: False
    unblind: True
    use_snapshot: True
    combine_bins: True
    combine_eras: True
    submit :  
      time: '0-06:00:00'
      mem : 3000
    plotting:
      left_margin           : 400
      right_margin          : 20
      label_size            : 18
      parameters_per_page   : 35
      order_by_impact       : True
    bins:
      - HH_DL_{mass}_resolved1b_GGF
      - HH_DL_{mass}_resolved2b_GGF
      - HH_DL_{mass}_boosted_GGF
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other

  prefit:
    mode: prefit 
    command: "combine -M FitDiagnostics --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes  --keepFailures  --skipSBFit --skipBOnlyFit --ignoreCovWarning -n HHbbWW"
    submit :  
      time: '1-00:00:00'
      mem : 20000
    combine_bins: True
    bins:
      - HH_DL_{mass}_resolved1b_GGF
      - HH_DL_{mass}_resolved2b_GGF
      - HH_DL_{mass}_boosted_GGF
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
    plots: 
      - bin_name: GGFnode
        header: GGF node
        plot_options: !include prefit_DL_res_main.yml
        analysis: 'HH'
        categories : [HH_DL_{mass}_resolved1b_GGF,HH_DL_{mass}_resolved2b_GGF,HH_DL_{mass}_boosted_GGF]
        labels: ['Resolved 1b','Resolved 2b','Boosted']
        unblind: False
        show_ratio: True
        sort_by_yield: True
      - bin_name: DYnode
        header: DY + VV(V) node
        plot_options: !include prefit_DL_res_main.yml
        analysis: 'HH'
        categories : [HH_DL_{mass}_inclusive_DY_VVV]
        unblind: True
        show_ratio: True
        sort_by_yield: True
      - bin_name: Othernode
        header: TT + Other Background node
        plot_options: !include prefit_DL_res_main.yml
        analysis: 'HH'
        categories: [HH_DL_{mass}_resolved_other,HH_DL_{mass}_boosted_other]
        labels: ['Resolved','Boosted']
        unblind: True
        show_ratio: True
        sort_by_yield: True
  postfit_b:
    mode: postfit_b
    command: "combine -M FitDiagnostics --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes  --keepFailures  --skipSBFit --ignoreCovWarning -n HHbbWW"
    submit :  
      time: '3-00:00:00'
      mem : 20000
    bins:
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
    plots: 
      - bin_name: DYnode
        header: DY + VV(V) node
        plot_options: !include prefit_DL_res_main.yml
        analysis: 'HH'
        categories : [HH_DL_{mass}_inclusive_DY_VVV]
        unblind: True
        show_ratio: True
        sort_by_yield: True
      - bin_name: Othernode
        header: TT + Other Background node
        plot_options: !include prefit_DL_res_main.yml
        analysis: 'HH'
        categories: [HH_DL_{mass}_resolved_other,HH_DL_{mass}_boosted_other]
        labels: ['Resolved','Boosted']
        unblind: True
        show_ratio: True
        sort_by_yield: True

#  postfit_s:
#    mode: postfit_s
#    command: "combine -M FitDiagnostics --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic --keepFailures  --skipBOnlyFit --ignoreCovWarning -n HHbbWW"
#    submit :  
#      time: '1-00:00:00'
#      mem : 15000
#    bins:
#      - HH_DL_resolved1b_GGF
#      - HH_DL_{mass}_resolved2b_GGF
#      - HH_DL_{mass}_boosted_GGF
#      - HH_DL_{mass}_resolved_DY_VVV
#      - HH_DL_{mass}_boosted_DY_VVV
#      - HH_DL_{mass}_resolved_other
#      - HH_DL_{mass}_boosted_other
#    plotting:
#        main: !include postfit_main.yml
#        plots: 
#          - name: GGFnode
#            header: GGF node
#            bins : [HH_DL_resolved1b_GGF,HH_DL_resolved2b_GGF,HH_DL_boosted_GGF]
#            labels: ['Resolved 1b','Resolved 2b','Boosted']
#            labelpos: [0.5, 8.5, 17]
#            unblind: False
#          - name: DYnode
#            header: DY + VV(V) node
#            bins : [HH_DL_resolved_DY_VVV,HH_DL_boosted_DY_VVV]
#            labels: ['Resolved','Boosted']
#            labelpos: [2, 10]
#            unblind: True
#          - name: Othernode
#            header: TT + Other BKG node
#            bins : [HH_DL_resolved_other,HH_DL_boosted_other]
#            labels: ['Resolved','Boosted']
#            labelpos: [2, 8]
#            unblind: True


