path: 
  2016:
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_Resonant_Boosted1B_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_Resonant_Resolved1B_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_Resonant_Resolved2B_syst_M_{mass}/
  2017:
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_Resonant_Boosted1B_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_Resonant_Resolved1B_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_Resonant_Resolved2B_syst_M_{mass}/
  2018:
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Boosted1B_{branch}_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Resolved1B_{branch}_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Resolved2B_{branch}_syst_M_{mass}/

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww_dl/Resonant/datacard_fit_Resonant_{branch}_Graviton_HME_{mass}_FR2

use_syst: True

yamlName: plots_DYEstimation_FakeExtrapolation.yml

produce_plots: True


era: 
 - 2016
 - 2017
 - 2018

combineConfigs:
  prefit:
    mode: prefit 
    command: "combine -M FitDiagnostics --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes  --keepFailures  --skipSBFit --skipBOnlyFit --ignoreCovWarning -n HHbbWW"
    submit :  
      time: '1-00:00:00'
      mem : 20000
    bins:
      - HME
    plotting:
        main: 
          bin_name_original       : 'none'
          datacard_original       : 'none'
          merged_eras_fit         : False
          minY                    : 0.001
          maxY                    : 10000000000000.
          useLogPlot              : True
          labelX                  : 'HME [x 10 GeV]'
          number_columns_legend   : 3
          minYerr                 : -0.6
          maxYerr                 : 0.6
          cats_labels_height      : 5000000.
        plots: 
          - name: HME
            header: HME
            bins : [HME]
            labels: ['']
            labelpos: [1]
            unblind: True


legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

normSyst  : !include norm_all_res.yml
shapeSyst  : !include shape_DL_systematics.yml

histConverter: 
  2016:
    HME:
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag_HME
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag_HME
  2017:
    HME:
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedOneBtag_HME
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedjetPUIDReweightingBtagAk4SFBtagAk8SFOneAk8JetInclusiveBoostedOneBtag_HME
  
  2018:
    HME:
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtag_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtag_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtag_HME
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtags_HME
      - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtag_HME
      - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtag_HME
      - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtag_HME
  

  
groups:
  2016:
    - !include groups_DL_bkg_2016.yml
    - !include groups_DY_datadriven_2016.yml
    - !include groups_Fakes_2016.yml
    - !include groups_data_2016.yml
    - signal_ggf_{spin}_{mass}_hbbhww:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbbWW [1 pb]"
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - GluGluToBulkGravitonToHHTo2B2VTo2L2Nu_M-{mass}.root
      signal_ggf_{spin}_{mass}_hbbhtt:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbb#tau#tau [1 pb]"
        order: 14
        line-color: '#c91a26'
        fill-color: '#c91a26'
        line-type: 1
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToBulkGravitonToHHTo2B2Tau_M-{mass}.root
  2017:
    - !include groups_DL_bkg_2017.yml
    - !include groups_DY_datadriven_2017.yml
    - !include groups_Fakes_2017.yml
    - !include groups_data_2017.yml
    - signal_ggf_{spin}_{mass}_hbbhww:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbbWW [1 pb]"
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - GluGluToBulkGravitonToHHTo2B2VTo2L2Nu_M-{mass}.root
      signal_ggf_{spin}_{mass}_hbbhtt:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbb#tau#tau [1 pb]"
        order: 14
        line-color: '#c91a26'
        fill-color: '#c91a26'
        line-type: 1
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToBulkGravitonToHHTo2B2Tau_M-{mass}.root
  2018:
    - !include groups_DL_bkg_2018.yml
    - !include groups_DY_datadriven_2018.yml
    - !include groups_Fakes_2018.yml
    - !include groups_data_2018.yml
    - signal_ggf_{spin}_{mass}_hbbhww:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbbWW [1 pb]"
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - GluGluToBulkGravitonToHHTo2B2VTo2L2Nu_M-{mass}.root
      signal_ggf_{spin}_{mass}_hbbhtt:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbb#tau#tau [1 pb]"
        order: 14
        line-color: '#c91a26'
        fill-color: '#c91a26'
        line-type: 1
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToBulkGravitonToHHTo2B2Tau_M-{mass}.root

