path: 
  2016:
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2016NanoV7_TTHIDLoose_Fake_DNNSL01_Boosted
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2016NanoV7_TTHIDLoose_Fake_DNNSL01_Resolved1B
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2016NanoV7_TTHIDLoose_Fake_DNNSL01_Resolved2B
  2017:
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2017NanoV7_TTHIDLoose_Fake_DNNSL01_Boosted
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2017NanoV7_TTHIDLoose_Fake_DNNSL01_Resolved1B
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2017NanoV7_TTHIDLoose_Fake_DNNSL01_Resolved2B
  2018:
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2018NanoV7_TTHIDLoose_Fake_DNNSL01_Boosted
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2018NanoV7_TTHIDLoose_Fake_DNNSL01_Resolved1B
    - /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL_Debug/full2018NanoV7_TTHIDLoose_Fake_DNNSL01_Resolved2B

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww_sl/NonResonant/datacard_fit_NonResonant_SL_DNN001_FR2

use_syst: True

yamlName: plots_FakeExtrapolation.yml

produce_plots: True

era: 
  - 2016
  - 2017
  - 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

#combineConfigs: !include combine_Res.yml

normSyst  : 
  - !include norm_lumi.yml
  - !include norm_BR.yml
  - !include norm_QCDscale.yml
  - !include norm_alpha_s.yml
  - !include norm_pdf.yml
  - !include norm_misc.yml
  - !include norm_SL_nonres_process.yml
  # Footer #
  - footer:
      - "nuisance edit rename TT    * CMS_bbwwsl_ps_fsr CMS_bbwwsl_ps_fsr_TT"
      - "nuisance edit rename ST    * CMS_bbwwsl_ps_fsr CMS_bbwwsl_ps_fsr_ST"
      - "nuisance edit rename WJets * CMS_bbwwsl_ps_fsr CMS_bbwwsl_ps_fsr_WJets"
      - "nuisance edit rename TT    * CMS_bbwwsl_ps_isr CMS_bbwwsl_ps_isr_TT"
      - "nuisance edit rename ST    * CMS_bbwwsl_ps_isr CMS_bbwwsl_ps_isr_ST"
      - "nuisance edit rename WJets * CMS_bbwwsl_ps_isr CMS_bbwwsl_ps_isr_WJets"


shapeSyst: !include shape_SL_systematics.yml


rebin: !include rebin_SL_nonresonant.yml


histConverter: !include cat_SL_nonresonant.yml
  
groups:
  2016:
    - !include groups_bkg_2016.yml
    - !include groups_Fakes_2016.yml
    - !include groups_data_2016.yml
    - !include groups_SL_signal_nonres.yml
  2017:
    - !include groups_bkg_2017.yml
    - !include groups_Fakes_2017.yml
    - !include groups_data_2017.yml
    - !include groups_SL_signal_nonres.yml
  2018:
    - !include groups_bkg_2018.yml
    - !include groups_Fakes_2018.yml
    - !include groups_data_2018.yml
    - !include groups_SL_signal_nonres.yml
