path: 
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved1B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved2B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Boosted1B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_DNN11_GGFNLO_BenchmarkSM/
use_syst: True

textfiles: datacard_SM.txt

combineCmd: "combine -M AsymptoticLimits -t -1 -d {}" 

yamlName: 
  - plots.yml
  - plots_DYEstimation_FakeExtrapolation.yml

produce_plots: True

era: 2017

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99

shapeSyst : !include shape_DL_systematics.yml
normSyst  : !include norm_datadriven_systematics.yml

rebin: !include rebin_DL_nonresonant.yml

DYnonclosure:
  path : config/fit_results.json
  hist:
    HH_DL_resolved_DY_VVV : 
      entry: HH_DL_resolved_DY_VVV_2017
      name: dy_resolved_nonclosure_dy_vvv
    HH_DL_boosted_DY_VVV : 
      entry: HH_DL_boosted_DY_VVV
      name: dy_boosted_nonclosure_dy_vvv
    HH_DL_inclusive_other: 
      entry: HH_DL_inclusive_other_2017
      name: dy_nonclosure_other
  group: DY

histConverter: !include cat_DL_nonresonant.yml
  
groups: 
  - !include groups_DL_bkg_2017.yml
  - !include groups_DY_datadriven_2017.yml
  - !include groups_data_2017.yml
  - !include groups_DL_BM_qqHH.yml
  - ggHH_BM_SM_hbbhww:
      type: signal
      legend: HH#rightarrowbbWW#rightarrowbb2l GGF (NLO#rightarrowBM SM) 
      order: 14
      line-color: '#288a24'
      line-type: 1
      files:
        - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmarkSM.root
  
    ggHH_BM_SM_hbbhtt:
      type: signal
      legend: HH#rightarrowbbWW#rightarrowbb#tau#tau (NLO#rightarrowBM SM) 
      order: 14
      line-color: '#288a24'
      line-type: 1
      files:
        - GluGluToHHTo2B2Tau_NLOBenchmarkSM.root



