path: 
    - /home/ucl/cp3/sdonerta/bamboodev/WWGGSnowmassMyFork/WWGGSnowMassAnalysis/13TeVSlurm 

outputDir: test

use_syst: False

yamlName: plots.yml

produce_plots: True

era: 
  - HL-LHC

combineConfigs: # <to_replace>

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

histConverter: 
  Inv_mass_gghasOneL:   # You could use any name as key (will be the category for the root file name and for combine)
    - Inv_mass_gghasOneL
    # Absolutely needs to be a list here
  
groups:
  GGH:
    fill-color: '#260AB3' #or whatever color 
    legend: 'WW\gamma\gamma'
    order: 1
    type: signal
    group: GGHH
    files:
      - GluGluToHHTo2G2Qlnu_node_cHHH1_TuneCP5_14TeV-powheg-pythia8_200PU.root
  Wjets:
    fill-color: '#cc7a16'  #or whatever color
    legend: 'Wjets'
    order: 2
    type: mc
    group: Wjets
    files:
      - W1JetsToLNu_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.root
      - W2JetsToLNu_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.root
      - W3JetsToLNu_TuneCUETP8M1_14TeV-madgraphMLM-pythia8_200PU.root
  GJet:
    fill-color: '#FFFF00'
    legend: 'GJet'
    order: 3
    type: mc 
    group: Gjet
    files:
      - GJet_Pt-20to40_DoubleEMEnriched_MGG-80toInf_TuneCP5_14TeV-pythia8_200PU.root
      - GJet_Pt-20toInf_DoubleEMEnriched_MGG-40to80_TuneCUEP8M2T4_14TeV_pythia8_200PU.root
      - GJet_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCUEP8M2T4_14TeV_Pythia8_200PU.root
  SingleH:
    fill-color: '#FFCC33'
    legend: 'Single H'
    order: 4
    type: mc
    group: SingleH
    files:
      - GluGluHToGG_M125_TuneCP5_14TeV-amcatnloFXFX-pythia8_200PU.root
      - VBFHToGG_M125_TuneCP5_14TeV-amcatnlo-pythia8_200PU.root
      - VHToGG_M125_TuneCP5_14TeV-amcatnloFXFX-madspin-pythia8_200PU.root
      - ttHJetToGG_M125_TuneCP5_14TeV-amcatnloFXFX-madspin-pythia8_200PU.root
  DiPhoton:
    fill-color: '#40D51A'
    legend: '\gamma\gamma Jets'
    order: 5
    type: mc
    group: GGjets
    files:
      - DiPhotonJetsBox_MGG-80toInf_14TeV-Sherpa_200PU.root
  TT:
    fill-color: '#D489FF' #or whatever color 
    legend: 't#bar{t}'
    order: 6
    type: mc
    group: TT
    files:
      - TT_TuneCUETP8M2T4_14TeV-powheg-pythia8_200PU.root
  QCD:
    fill-color: '#E2283B' #or whatever color 
    legend: 'QCD'
    order: 7
    type: mc
    group: qcd
    files:
      - QCD_Pt-30toInf_DoubleEMEnriched_MGG-40to80_TuneCUEP8M2T4_14TeV_Pythia8_200PU.root
      - QCD_Pt-40toInf_DoubleEMEnriched_MGG-80toInf_TuneCUEP8M2T4_14TeV_Pythia8_200PU.root
  TTGG:
    fill-color: '#28E298' #or whatever color 
    legend: 'TTGG'
    order: 8
    type: mc
    group: ttGG
    files:
      - TTGG_0Jets_TuneCUETP8M1_14TeV_amcatnlo_madspin_pythia8_200PU.root
  TTW:
    fill-color: '#c7e619' #or whatever color 
    legend: 'TTW Jets'
    order: 9
    type: mc
    group: ttW
    files:
      - TTWJetsToLNu_TuneCUETP8M1_14TeV-amcatnloFXFX-madspin-pythia8_200PU.root
  WGG:
    fill-color: '#008080' #or whatever color 
    legend: 'WGG Jets'
    order: 10
    type: mc
    group: wGG
    files:
      - WGGJets_TuneCP5_14TeV_madgraphMLM_pythia8_200PU.root
  WGJJ:
    fill-color: '#28CCE2' #or whatever color 
    legend: 'WGJJ'
    order: 11
    type: mc
    group: WGJJ
    files:
      - WGJJToLNu_EWK_QCD_TuneCP5_14TeV-madgraph-pythia8_200PU.root
  ZG:
    fill-color: '#990066' #or whatever color 
    legend: 'ZG'
    order: 12
    type: mc
    group: ZG
    files:
      - ZGTo2LG_TuneCUETP8M1_14TeV-amcatnloFXFX-pythia8_200PU.root

