path: 
  2016:
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_Resonant_Boosted1B_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_Resonant_Resolved1B_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_Resonant_Resolved2B_syst_M_{mass}/
  2017:
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_Resonant_Boosted1B_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_Resonant_Resolved1B_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_Resonant_Resolved2B_syst_M_{mass}/
  2018:
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Boosted1B_{branch}_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Resolved1B_{branch}_syst_M_{mass}/
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Resolved2B_{branch}_syst_M_{mass}/

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww_dl/Resonant/datacard_fit_Resonant_{branch}_Graviton_1D_syst_M_{mass}_FR2

use_syst: True

yamlName: plots_DYEstimation_FakeExtrapolation.yml

produce_plots: True

era: 
 - 2016
 - 2017
 - 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

combineConfigs: 
  - !include combine_DL_res.yml

normSyst  : !include norm_all_res.yml

shapeSyst  : !include shape_DL_systematics.yml


quantiles : 
  - &quant5 [0., 0.2, 0.4, 0.6, 0.8 ,1.]
  - &quant3 [0., 0.33, 0.66, 1.]
backgrounds : &back [TT,ST,DY,WJets,VV,VVV,Other_bbWW,ggH_hbb,ggH_hgg,ggH_hmm,ggH_htt,ggH_hww,ggH_hzz,qqH_hbb,qqH_hgg,qqH_hmm,qqH_htt,qqH_hww,qqH_hzz,ttH_hbb,ttH_hww,WH_hbb,ZH_hbb,ZH_htt,ZH_hww,tHq_hww,tHW_hww,VH_hww]
thresh: &thresh [1.e-05, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100., 121., 144., 169., 196., 225.]

rebin:
  HH_DL_{mass}_resolved1b_GGF:
    method: threshold 
    params: 
      - *thresh
      - [TT,ST,DY]
      - 15
      - 0.075
      - [signal_ggf_{spin}_{mass}_hbbhww,signal_ggf_{spin}_{mass}_hbbhtt]
  HH_DL_{mass}_resolved2b_GGF:
    method: threshold 
    params: 
      - *thresh
      - [TT,ST,DY]
      - 15
      - 0.1
      - [signal_ggf_{spin}_{mass}_hbbhww,signal_ggf_{spin}_{mass}_hbbhtt]
  HH_DL_{mass}_boosted_GGF:
    method: threshold 
    params: 
      - *thresh
      - [TT,ST,DY]
      - 15
      - 0.2
      - [signal_ggf_{spin}_{mass}_hbbhww,signal_ggf_{spin}_{mass}_hbbhtt]
  
  HH_DL_{mass}_inclusive_DY_VVV:
    method : quantile
    params : [*quant5, *back]

  HH_DL_{mass}_resolved_other:
    method : quantile
    params : [*quant5, *back]
  HH_DL_{mass}_boosted_other:
    method : quantile
    params : [*quant3, *back]

histCorrections: !include nonclosure_DY_res.yml

histConverter: 
  2016: !include resonant_cat_param_1D_mass_fix.yml
  2017: !include resonant_cat_param_1D_mass_fix.yml
  2018: !include resonant_cat_param_1D_mass.yml

groups:
  2016:
    - !include groups_DL_bkg_2016.yml
    - !include groups_DY_datadriven_2016.yml
    - !include groups_Fakes_2016.yml
    - !include groups_data_2016.yml
    - signal_ggf_{spin}_{mass}_hbbhww:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbbWW [1 pb]"
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - GluGluToBulkGravitonToHHTo2B2VTo2L2Nu_M-{mass}.root
      signal_ggf_{spin}_{mass}_hbbhtt:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbb#tau#tau [1 pb]"
        order: 14
        line-color: '#c91a26'
        fill-color: '#c91a26'
        line-type: 1
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToBulkGravitonToHHTo2B2Tau_M-{mass}.root
  2017:
    - !include groups_DL_bkg_2017.yml
    - !include groups_DY_datadriven_2017.yml
    - !include groups_Fakes_2017.yml
    - !include groups_data_2017.yml
    - signal_ggf_{spin}_{mass}_hbbhww:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbbWW [1 pb]"
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - GluGluToBulkGravitonToHHTo2B2VTo2L2Nu_M-{mass}.root
      signal_ggf_{spin}_{mass}_hbbhtt:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbb#tau#tau [1 pb]"
        order: 14
        line-color: '#c91a26'
        fill-color: '#c91a26'
        line-type: 1
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToBulkGravitonToHHTo2B2Tau_M-{mass}.root
  2018:
    - !include groups_DL_bkg_2018.yml
    - !include groups_DY_datadriven_2018.yml
    - !include groups_Fakes_2018.yml
    - !include groups_data_2018.yml
    - signal_ggf_{spin}_{mass}_hbbhww:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbbWW [1 pb]"
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - GluGluToBulkGravitonToHHTo2B2VTo2L2Nu_M-{mass}.root
      signal_ggf_{spin}_{mass}_hbbhtt:
        type: signal
        legend: "Graviton {mass} GeV #rightarrowHH#rightarrowbb#tau#tau [1 pb]"
        order: 14
        line-color: '#c91a26'
        fill-color: '#c91a26'
        line-type: 1
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToBulkGravitonToHHTo2B2Tau_M-{mass}.root

