path: 
  2016: /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2016NanoV7_NonResonant_DNN11_DYEstimation/
  2017: /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2017NanoV7_NonResonant_DNN11_DYEstimation/
  2018: /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2018NanoV7_NonResonant_DNN11_DYEstimation/
use_syst: False

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww_dl/NonResonant/datacard_fit_NonResonant_DNN11_DY_datadriven_FR2

yamlName: plots_DYEstimation.yml

produce_plots: True

era: 
  - 2016
  - 2017
  - 2018

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99

histConverter: !include cat_DY_nonresonant.yml

groups:
  2016:
    - !include groups_DL_bkg_2016.yml
    - !include groups_data_2016.yml
    - !include groups_DY_datadriven_2016.yml
  2017:
    - !include groups_DL_bkg_2017.yml
    - !include groups_data_2017.yml
    - !include groups_DY_datadriven_2017.yml
  2018:
    - !include groups_DL_bkg_2018.yml
    - !include groups_data_2018.yml
    - !include groups_DY_datadriven_2018.yml
