path: 
  2016:
    # DL #
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2016NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Boosted1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2016NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Resolved1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2016NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Resolved2B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2016NanoV7_DL_NonResonant_DNN11_GGFNLO_Benchmark{BM}
    # SL #
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2016NanoV7_SL_NonResonant_DNN01_Fake_Boosted
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2016NanoV7_SL_NonResonant_DNN01_Fake_Resolved1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2016NanoV7_SL_NonResonant_DNN01_Fake_Resolved2B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2016NanoV7_SL_NonResonant_DNN01_GGFNLO_Benchmark{BM}
  2017:
    # DL #
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2017NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Boosted1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2017NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Resolved1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2017NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Resolved2B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2017NanoV7_DL_NonResonant_DNN11_GGFNLO_Benchmark{BM}
    # SL #
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2017NanoV7_SL_NonResonant_DNN01_Fake_Boosted
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2017NanoV7_SL_NonResonant_DNN01_Fake_Resolved1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2017NanoV7_SL_NonResonant_DNN01_Fake_Resolved2B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2017NanoV7_SL_NonResonant_DNN01_GGFNLO_Benchmark{BM}
  2018:
    # DL #
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2018NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Boosted1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2018NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Resolved1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2018NanoV7_DL_NonResonant_DNN11_Fake_DYEstimation_Resolved2B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2018NanoV7_DL_NonResonant_DNN11_GGFNLO_Benchmark{BM}
    # SL #
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2018NanoV7_SL_NonResonant_DNN01_Fake_Boosted
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2018NanoV7_SL_NonResonant_DNN01_Fake_Resolved1B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2018NanoV7_SL_NonResonant_DNN01_Fake_Resolved2B
    - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/NonResonant/full2018NanoV7_SL_NonResonant_DNN01_GGFNLO_Benchmark{BM}


outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww/NonResonant/datacard_fit_NonResonant_BM_GGFNLO_{BM}_syst_FR2/

use_syst: True

textfiles: datacard_{BM}_{}.txt

yamlName: 
  - plots_DYEstimation_FakeExtrapolation.yml
  - plots_FakeExtrapolation.yml
  - plots.yml

produce_plots: True

era: 
  - 2016
  - 2017
  - 2018

combineConfigs: 
  limits_combined:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1"
    submit :  
      time: '0-12:00:00'
      mem : 9000
    bins:
      - HH_DL_resolved1b_GGF
      - HH_DL_resolved2b_GGF
      - HH_DL_boosted_GGF
      - HH_DL_resolved1b_VBF
      - HH_DL_resolved2b_VBF
      - HH_DL_boosted_VBF
      - HH_DL_inclusive_DY_VVV
      - HH_DL_resolved_other
      - HH_DL_boosted_other 
      - HH_SL_resolved1b_GGF
      - HH_SL_resolved2b_GGF
      - HH_SL_boosted_GGF
      - HH_SL_resolved1b_VBF
      - HH_SL_resolved2b_VBF
      - HH_SL_boosted_VBF
      - HH_SL_inclusive_other
      - HH_SL_resolved_TopH
      - HH_SL_boosted_TopH
  limits_DL:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1"
    submit :  
      time: '0-12:00:00'
      mem : 9000
    bins:
      - HH_DL_resolved1b_GGF
      - HH_DL_resolved2b_GGF
      - HH_DL_boosted_GGF
      - HH_DL_resolved1b_VBF
      - HH_DL_resolved2b_VBF
      - HH_DL_boosted_VBF
      - HH_DL_inclusive_DY_VVV
      - HH_DL_resolved_other
      - HH_DL_boosted_other 
  limits_SL:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1"
    submit :  
      time: '0-12:00:00'
      mem : 9000
    bins:
      - HH_SL_resolved1b_GGF
      - HH_SL_resolved2b_GGF
      - HH_SL_boosted_GGF
      - HH_SL_resolved1b_VBF
      - HH_SL_resolved2b_VBF
      - HH_SL_boosted_VBF
      - HH_SL_inclusive_other
      - HH_SL_resolved_TopH
      - HH_SL_boosted_TopH




plotIt: !include plotIt_nonres_COMB.yml

era: 
  - 2016
  - 2017
  - 2018

normSyst  : !include norm_comb_nonres.yml

shapeSyst  : !include shape_comb_systematics.yml

rebin: !include rebin_comb_nonresonant.yml
  
histCorrections: !include nonclosure_nonres.yml

histConverter: !include cat_comb_nonresonant.yml
  
groups:
  2016:
    - !include groups_bkg_2016.yml
    - !include groups_Fakes_2016.yml
    - !include groups_data_2016.yml
    - !include groups_COMB_BM_qqHH.yml
    - ggHH_BM_{BM}_hbbhww:
        type: signal
        legend: HH bbWW GGF (BM {BM}) 
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - cat: [".*SL.*"]
            files:
              - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmark{BM}.root
              - GluGluToHHTo2B2VLNu2J_NLOBenchmark{BM}.root
          - cat: [".*DL.*"]
            files:
              - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmark{BM}.root
      ggHH_BM_{BM}_hbbhtt:
        type: signal
        legend: HH bb#tau#tau GGF (BM {BM}) 
        order: 14
        line-color: '#c91a26'
        line-type: 1
        fill-color: '#c91a26'
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToHHTo2B2Tau_NLOBenchmark{BM}.root

  2017:
    - !include groups_bkg_2017.yml
    - !include groups_Fakes_2017.yml
    - !include groups_data_2017.yml
    - !include groups_COMB_BM_qqHH.yml
    - ggHH_BM_{BM}_hbbhww:
        type: signal
        legend: HH bbWW GGF (BM {BM}) 
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - cat: [".*SL.*"]
            files:
              - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmark{BM}.root
              - GluGluToHHTo2B2VLNu2J_NLOBenchmark{BM}.root
          - cat: [".*DL.*"]
            files:
              - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmark{BM}.root
      ggHH_BM_{BM}_hbbhtt:
        type: signal
        legend: HH bb#tau#tau GGF (BM {BM}) 
        order: 14
        line-color: '#c91a26'
        line-type: 1
        fill-color: '#c91a26'
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToHHTo2B2Tau_NLOBenchmark{BM}.root
  2018:
    - !include groups_bkg_2018.yml
    - !include groups_Fakes_2018.yml
    - !include groups_data_2018.yml
    - !include groups_COMB_BM_qqHH.yml
    - ggHH_BM_{BM}_hbbhww:
        type: signal
        legend: HH bbWW GGF (BM {BM}) 
        order: 14
        line-color: '#288a24'
        fill-color: '#288a24'
        line-type: 1
        line-width: 2
        fill-type: 3345
        files:
          - cat: [".*SL.*"]
            files:
              - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmark{BM}.root
              - GluGluToHHTo2B2VLNu2J_NLOBenchmark{BM}.root
          - cat: [".*DL.*"]
            files:
              - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmark{BM}.root
      ggHH_BM_{BM}_hbbhtt:
        type: signal
        legend: HH bb#tau#tau GGF (BM {BM}) 
        order: 14
        line-color: '#c91a26'
        line-type: 1
        fill-color: '#c91a26'
        line-width: 2
        fill-type: 3354
        files:
          - GluGluToHHTo2B2Tau_NLOBenchmark{BM}.root

