path: 
  2016:
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2016NanoV7_DL_Resonant_Fake_DYEstimation_Boosted1B_M_{mass}
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2016NanoV7_DL_Resonant_Fake_DYEstimation_Resolved1B_M_{mass}
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2016NanoV7_DL_Resonant_Fake_DYEstimation_Resolved2B_M_{mass}
  2017:
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2017NanoV7_DL_Resonant_Fake_DYEstimation_Boosted1B_M_{mass}
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2017NanoV7_DL_Resonant_Fake_DYEstimation_Resolved1B_M_{mass}
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2017NanoV7_DL_Resonant_Fake_DYEstimation_Resolved2B_M_{mass}
  2018:
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2018NanoV7_DL_Resonant_Fake_DYEstimation_Boosted1B_M_{mass}
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2018NanoV7_DL_Resonant_Fake_DYEstimation_Resolved1B_M_{mass}
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/Resonant/full2018NanoV7_DL_Resonant_Fake_DYEstimation_Resolved2B_M_{mass}

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww_dl/Resonant/datacard_fit_Resonant_{branch}_{spin}_{dim}_syst_M_{mass}_final_FR2

use_syst: True
include_overflow: True

yamlName: plots_DYEstimation_FakeExtrapolation.yml

plotIt: !include plotIt_res_DL.yml

era: 
 - 2016
 - 2017
 - 2018

combineConfigs: !include combine_DL_res.yml

normSyst  : !include norm_all_res.yml

shapeSyst  : !include shape_comb_systematics.yml

rebin: !include rebin_resonant_{branch}_{dim}.yml

histCorrections: !include nonclosure_DL_res.yml

histConverter: !include resonant_cat_param_{dim}_mass.yml

groups:
  2016:
    - !include groups_bkg_2016.yml
    - !include groups_Fakes_2016.yml
    - !include groups_data_2016.yml
    - !include groups_DL_signal_res_{spin}.yml
  2017:
    - !include groups_bkg_2017.yml
    - !include groups_Fakes_2017.yml
    - !include groups_data_2017.yml
    - !include groups_DL_signal_res_{spin}.yml
  2018:
    - !include groups_bkg_2018.yml
    - !include groups_Fakes_2018.yml
    - !include groups_data_2018.yml
    - !include groups_DL_signal_res_{spin}.yml
