path: 
  2016: /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2016NanoV7_NonResonant_DNN11_DYEstimation_PseudoData/
  2017: /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2017NanoV7_NonResonant_DNN11_DYEstimation_PseudoData/
  2018: /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2018NanoV7_NonResonant_DNN11_DYEstimation_PseudoData/
use_syst: False

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww_dl/NonResonant/datacard_fit_NonResonant_DNN11_DY_closure_FR2

yamlName: plots_pseudodata.yml

produce_plots: True

era: 
  - 2016
  - 2017
  - 2018

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99


histConverter: !include cat_DY_nonresonant.yml


groups:
  2016: 
    - !include groups_DL_bkg_2016.yml
    - !include groups_DL_PseudoData_2016.yml
    - DY:
        fill-color: '#1a83a1'
        legend: Drell-Yan (from data)
        order: 3
        type: mc
        files:
          - DYJetsToLL_M-10to50DYEstimation.root
          - DYJetsToLL_M-50DYEstimation.root
          - DYToLL_0JDYEstimation.root
          - DYToLL_1JDYEstimation.root
          - DYToLL_2JDYEstimation.root
  2017: 
    - !include groups_DL_bkg_2017.yml
    - !include groups_DL_PseudoData_2017.yml
    - DY:
        fill-color: '#1a83a1'
        legend: Drell-Yan (from data)
        order: 3
        type: mc
        files:
          - DYJetsToLL_M-10to50DYEstimation.root
          - DYJetsToLL_M-50DYEstimation.root
          - DYToLL_0JDYEstimation.root
          - DYToLL_1JDYEstimation.root
          - DYToLL_2JDYEstimation.root
  2018: 
    - !include groups_DL_bkg_2018.yml
    - !include groups_DL_PseudoData_2018.yml
    - DY:
        fill-color: '#1a83a1'
        legend: Drell-Yan (from data)
        order: 3
        type: mc
        files:
          - DYJetsToLL_M-10to50DYEstimation.root
          - DYJetsToLL_M-50DYEstimation.root
          - DYToLL_0JDYEstimation.root
          - DYToLL_1JDYEstimation.root
          - DYToLL_2JDYEstimation.root

