path: /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/FakeNC_SL_2016_MCFakes/
use_syst: False

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww_sl/NonResonant/datacard_SL_FNC_MCFakes_2016

yamlName: plots.yml

produce_plots: True

era: 2016

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99


histConverter: !include cat_SL_nonresonant_channel.yml
  
groups:
  TT:
    fill-color: '#cc7a16'
    legend: 't#bar{t}'
    order: 1
    type: mc
    files:
      - TTToHadronic.root

