path: 
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Boosted
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Resolved1B
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Resolved2B

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/datacard_fit_NonResonant_SL_DNN001_2018

use_syst: True

yamlName: plots_FakeExtrapolation.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

#combineConfigs: !include combine_Res.yml

normSyst  : 
  - !include norm_lumi.yml
  - !include norm_BR.yml
  - !include norm_QCDscale.yml
  - !include norm_alpha_s.yml
  - !include norm_pdf.yml
  - !include norm_misc.yml
  - !include norm_SL_nonres_process.yml
  # Footer #
  - footer:
      - "nuisance edit rename TT    * CMS_bbwwsl_ps_fsr CMS_bbwwsl_ps_fsr_TT"
      - "nuisance edit rename ST    * CMS_bbwwsl_ps_fsr CMS_bbwwsl_ps_fsr_ST"
      - "nuisance edit rename WJets * CMS_bbwwsl_ps_fsr CMS_bbwwsl_ps_fsr_WJets"
      - "nuisance edit rename TT    * CMS_bbwwsl_ps_isr CMS_bbwwsl_ps_isr_TT"
      - "nuisance edit rename ST    * CMS_bbwwsl_ps_isr CMS_bbwwsl_ps_isr_ST"
      - "nuisance edit rename WJets * CMS_bbwwsl_ps_isr CMS_bbwwsl_ps_isr_WJets"

histCorrections:
  - module: nonclosure.py:NonClosureFake
    init: 
      path_json: config/factors_SL_Fake_2018.json
    categories: 
      HH_e_resolved1b_GGF:
        key:      HH_e_resolved1b_GGF_2018
        systName: fake_nc_e_res1b_GGF
      HH_m_resolved1b_GGF:
        key:      HH_m_resolved1b_GGF_2018
        systName: fake_nc_m_res1b_GGF
      HH_e_resolved1b_VBF:
        key:      HH_e_resolved1b_VBF_2018
        systName: fake_nc_e_res1b_VBF
      HH_m_resolved1b_VBF:
        key:      HH_m_resolved1b_VBF_2018
        systName: fake_nc_m_res1b_VBF
      HH_e_resolved2b_GGF:
        key:      HH_e_resolved2b_GGF_2018
        systName: fake_nc_e_res2b_GGF
      HH_m_resolved2b_GGF:
        key:      HH_m_resolved2b_GGF_2018
        systName: fake_nc_m_res2b_GGF
      HH_e_resolved2b_VBF:
        key:      HH_e_resolved2b_VBF_2018
        systName: fake_nc_e_res2b_VBF
      HH_m_resolved2b_VBF:
        key:      HH_m_resolved2b_VBF_2018
        systName: fake_nc_m_res2b_VBF
      HH_e_boosted_GGF:
        key:      HH_e_boosted_GGF_2018
        systName: fake_nc_e_boosted_GGF
      HH_m_boosted_GGF:
        key:      HH_m_boosted_GGF_2018
        systName: fake_nc_m_boosted_GGF
      HH_e_boosted_VBF:
        key:      HH_e_boosted_VBF_2018
        systName: fake_nc_e_boosted_VBF
      HH_m_boosted_VBF:
        key:      HH_m_boosted_VBF_2018
        systName: fake_nc_m_boosted_VBF
      HH_e_inclusive_WJets:
        key:      HH_e_inclusive_WJets_2018
        systName: fake_nc_e_inc_wjets
      HH_m_inclusive_WJets:
        key:      HH_m_inclusive_WJets_2018
        systName: fake_nc_m_inc_wjets
      HH_e_inclusive_OtherH:
        key:      HH_e_inclusive_OtherH_2018
        systName: fake_nc_e_inc_otherh
      HH_m_inclusive_OtherH:
        key:      HH_m_inclusive_OtherH_2018
        systName: fake_nc_m_inc_otherh
      HH_e_resolved_Top:
        key:      HH_e_resolved_Top_2018
        systName: fake_nc_e_res_top
      HH_m_resolved_Top:
        key:      HH_m_resolved_Top_2018
        systName: fake_nc_m_res_top
      HH_e_boosted_Top:
        key:      HH_e_boosted_Top_2018
        systName: fake_nc_e_boosted_top
      HH_m_boosted_Top:
        key:      HH_m_boosted_Top_2018
        systName: fake_nc_m_boosted_top



shapeSyst: !include shape_SL_systematics.yml


rebin: !include rebin_SL_nonresonant.yml


histConverter: !include cat_SL_nonresonant_channel.yml
regroup: !include cat_SL_nonresonant_regroup.yml
  
groups:
  - !include groups_bkg_2018.yml
  - !include groups_Fakes_2018.yml
  - !include groups_data_2018.yml
  - !include groups_SL_signal_nonres.yml

