path: 
  2016:
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2016NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH0
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2016NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH1
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2016NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH2p45
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2016NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH5
  2017:
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2017NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH0
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2017NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH1
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2017NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH2p45
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2017NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH5
  2018:
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2018NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH0
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2018NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH1
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2018NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH2p45
    - /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2018NanoV7_NonResonant_DNN11_Fake_DYEstimation_GGFLO_BenchmarkcHHH5

outputDir: /home/ucl/cp3/fbury/scratch/Datacards/bbww_dl/NonResonant/datacard_fit_NonResonant_DNN11_GGFLO_raw_FR2

use_syst: False

yamlName: 
  - plots.yml

produce_plots: True

era: 
  - 2016
  - 2017
  - 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

histConverter: !include type2_reco_cat_nonresonant.yml

  
groups:
  ggHH_kl_0_kt_1_hbbhww:
    type: signal
    legend: HH bbWW GGF (cHHH0) 
    order: 14
    hide: True
    cross-section: 1
    line-color: '#288a24'
    fill-color: '#288a24'
    line-type: 1
    line-width: 2
    fill-type: 3345
    files:
      - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmarkcHHH0.root
  ggHH_kl_1_kt_1_hbbhww:
    type: signal
    legend: HH bbWW GGF (cHHH1) 
    order: 14
    hide: False
    cross-section: 1
    line-color: '#288a24'
    fill-color: '#288a24'
    line-type: 1
    line-width: 2
    fill-type: 3345
    files:
      - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmarkcHHH1.root
  ggHH_kl_2p45_kt_1_hbbhww:
    type: signal
    legend: HH bbWW GGF (cHHH2p45) 
    order: 14
    hide: True
    cross-section: 1
    line-color: '#288a24'
    fill-color: '#288a24'
    line-type: 1
    line-width: 2
    fill-type: 3345
    files:
      - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmarkcHHH2p45.root
  ggHH_kl_5_kt_1_hbbhww:
    type: signal
    legend: HH bbWW GGF (cHHH5) 
    order: 14
    hide: True
    cross-section: 1
    line-color: '#288a24'
    fill-color: '#288a24'
    line-type: 1
    line-width: 2
    fill-type: 3345
    files:
      - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmarkcHHH5.root
  
  ggHH_kl_0_kt_1_hbbhtt:
    type: signal
    legend: HH bb#tau#tau GGF (cHHH0) 
    order: 14
    hide: True
    cross-section: 1
    line-color: '#c4082e'
    fill-color: '#c4082e'
    line-type: 1
    line-width: 2
    fill-type: 3345
    files:
      - GluGluToHHTo2B2Tau_NLOBenchmarkcHHH0.root
  ggHH_kl_1_kt_1_hbbhtt:
    type: signal
    legend: HH bb#tau#tau GGF (cHHH1) 
    order: 14
    hide: True
    cross-section: 1
    line-color: '#c4082e'
    fill-color: '#c4082e'
    line-type: 1
    line-width: 2
    fill-type: 3345
    files:
      - GluGluToHHTo2B2Tau_NLOBenchmarkcHHH1.root
  ggHH_kl_2p45_kt_1_hbbhtt:
    type: signal
    legend: HH bb#tau#tau GGF (cHHH2p45) 
    order: 14
    hide: True
    cross-section: 1
    line-color: '#c4082e'
    fill-color: '#c4082e'
    line-type: 1
    line-width: 2
    fill-type: 3345
    files:
      - GluGluToHHTo2B2Tau_NLOBenchmarkcHHH2p45.root
  ggHH_kl_5_kt_1_hbbhtt:
    type: signal
    legend: HH bb#tau#tau GGF (cHHH5) 
    order: 14
    hide: True
    cross-section: 1
    line-color: '#c4082e'
    fill-color: '#c4082e'
    line-type: 1
    line-width: 2
    fill-type: 3345
    files:
      - GluGluToHHTo2B2Tau_NLOBenchmarkcHHH5.root
  
  
