data_obs: 
  legend: pseudodata
  type: data
  files:
    - DYJetsToLL_M-10to50Pseudodata.root
    - DYJetsToLL_M-50Pseudodata.root
    - DYToLL_0JPseudodata.root
    - DYToLL_1JPseudodata.root
    - DYToLL_2JPseudodata.root
    - GluGluHToBBPseudodata.root
    - GluGluHToGGPseudodata.root
    - GluGluHToMuMuPseudodata.root
    - GluGluHToTauTauPseudodata.root
    - GluGluHToWWTo2L2NuPseudodata.root
    - GluGluHToWWToLNuQQPseudodata.root
    - GluGluHToZZTo2L2QPseudodata.root
    - GluGluHToZZTo4LPseudodata.root
    - HZJ_HToWWPseudodata.root
    - ST_schannel_4fPseudodata.root
    - ST_tchannel_antitop_4fPseudodata.root
    - ST_tchannel_top_4fPseudodata.root
    - ST_tW_antitop_5fPseudodata.root
    - ST_tWll_5fPseudodata.root
    - ST_tW_top_5fPseudodata.root
    - TGJetsPseudodata.root
    - THQPseudodata.root
    - THWPseudodata.root
    - TTGJetsPseudodata.root
    - ttHJetTobbPseudodata.root
    - ttHJetToNonbbPseudodata.root
    - TTTo2L2NuPseudodata.root
    - TTToHadronicPseudodata.root
    - TTToSemiLeptonicPseudodata.root
    - TTTTPseudodata.root
    - TTWHPseudodata.root
    - TTWJetsToLNuPseudodata.root
    - TTWJetsToQQPseudodata.root
    - TTWWPseudodata.root
    - TTZHPseudodata.root
    - TTZToLL_M-1to10Pseudodata.root
    - TTZToLLNuNu_M-10Pseudodata.root
    - TTZToQQPseudodata.root
    - tZq_llPseudodata.root
    - VBFHToBBPseudodata.root
    - VBFHToGGPseudodata.root
    - VBFHToMuMuPseudodata.root
    - VBFHToTauTauPseudodata.root
    - VBFHToWWTo2L2NuPseudodata.root
    - VBFHToWWToLNuQQPseudodata.root
    - VBFHToZZTo4LPseudodata.root
    - VHToNonbbPseudodata.root
    - WGToLNuGPseudodata.root
    - WJetsToLNu_0J_NLOPseudodata.root
    - WJetsToLNu_1J_NLOPseudodata.root
    - WJetsToLNu_2J_NLOPseudodata.root
    - WminusH_HToBB_WToLNuPseudodata.root
    - WplusH_HToBB_WToLNuPseudodata.root
    - WpWpJJPseudodata.root
    - WWTo2L2Nu_DoubleScatteringPseudodata.root
    - WWTo2L2NuPseudodata.root
    - WWToLNuQQPseudodata.root
    - WWWPseudodata.root
    - WWZPseudodata.root
    - WZGPseudodata.root
    - WZTo3LNuPseudodata.root
    - WZZPseudodata.root
    - ZGToLLGPseudodata.root
    - ZH_HToBB_ZToLLPseudodata.root
    - ZHToTauTauPseudodata.root
    - ZZTo2L2QPseudodata.root
    - ZZTo4LPseudodata.root
    - ZZZPseudodata.root

