
## for benchmarks, qqHH needs to be used as background
#qqHH_CV_0p5_C2V_1_kl_1_hbbhww:
#  type: mc
#  legend: HH bbWW VBF (CV 0.5 - C2V 1 - C3 1) 
#  order: 14
#  hide: True
#  line-color: '#cf8d13'
#  fill-color: '#cf8d13'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - cat: [".*SL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_0_5_C2V_1_C3_1_dipoleRecoilOff.root
#        - VBFHHTo2B2WToLNu2J_CV_0_5_C2V_1_C3_1_dipoleRecoilOff.root
#    - cat: [".*DL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_0_5_C2V_1_C3_1_dipoleRecoilOff.root
#qqHH_CV_1p5_C2V_1_kl_1_hbbhww:
#  type: mc
#  legend: HH bbWW VBF (CV 1.5 - C2V 1 - C3 1) 
#  order: 14
#  hide: True
#  line-color: '#cf8d13'
#  fill-color: '#cf8d13'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - cat: [".*SL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_5_C2V_1_C3_1_dipoleRecoilOff.root
#        - VBFHHTo2B2WToLNu2J_CV_1_5_C2V_1_C3_1_dipoleRecoilOff.root
#    - cat: [".*DL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_5_C2V_1_C3_1_dipoleRecoilOff.root
#qqHH_CV_1_C2V_0_kl_1_hbbhww:
#  type: mc
#  legend: HH bbWW VBF (CV 1 - C2V 0 - C3 1) 
#  order: 14
#  hide: True
#  line-color: '#cf8d13'
#  fill-color: '#cf8d13'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - cat: [".*SL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_0_C3_1_dipoleRecoilOff.root
#        - VBFHHTo2B2WToLNu2J_CV_1_C2V_0_C3_1_dipoleRecoilOff.root
#    - cat: [".*DL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_0_C3_1_dipoleRecoilOff.root
#qqHH_CV_1_C2V_1_kl_0_hbbhww:
#  type: mc
#  legend: HH bbWW VBF (CV 1 - C2V 1 - C3 0) 
#  order: 14
#  hide: True
#  line-color: '#cf8d13'
#  fill-color: '#cf8d13'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - cat: [".*SL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_0_dipoleRecoilOff.root
#        - VBFHHTo2B2WToLNu2J_CV_1_C2V_1_C3_0_dipoleRecoilOff.root
#    - cat: [".*DL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_0_dipoleRecoilOff.root
qqHH_CV_1_C2V_1_kl_1_hbbhww:
  type: mc
  legend: HH bbWW VBF (CV 1 - C2V 1 - C3 1) 
  order: 14
  hide: True
  line-color: '#cf8d13'
  fill-color: '#cf8d13'
  line-type: 1
  line-width: 2
  fill-type: 3354
  files:
    - cat: [".*SL.*"]
      files:
        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_1_dipoleRecoilOff.root
        - VBFHHTo2B2WToLNu2J_CV_1_C2V_1_C3_1_dipoleRecoilOff.root
    - cat: [".*DL.*"]
      files:
        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_1_dipoleRecoilOff.root
#qqHH_CV_1_C2V_1_kl_2_hbbhww:
#  type: mc
#  legend: HH bbWW VBF (CV 1 - C2V 1 - C3 2) 
#  order: 14
#  hide: True
#  line-color: '#cf8d13'
#  fill-color: '#cf8d13'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - cat: [".*SL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_2_dipoleRecoilOff.root
#        - VBFHHTo2B2WToLNu2J_CV_1_C2V_1_C3_2_dipoleRecoilOff.root
#    - cat: [".*DL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_2_dipoleRecoilOff.root
#qqHH_CV_1_C2V_2_kl_1_hbbhww:
#  type: mc
#  legend: HH bbWW VBF (CV 1 - C2V 2 - C3 1) 
#  order: 14
#  hide: True
#  line-color: '#cf8d13'
#  fill-color: '#cf8d13'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - cat: [".*SL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_2_C3_1_dipoleRecoilOff.root
#        - VBFHHTo2B2WToLNu2J_CV_1_C2V_2_C3_1_dipoleRecoilOff.root
#    - cat: [".*DL.*"]
#      files:
#        - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_2_C3_1_dipoleRecoilOff.root
#
#
#qqHH_CV_0p5_C2V_1_kl_1_hbbhtt:
#  type: mc
#  legend: HH bb#tau#tau VBF (CV 0.5 - C2V 1 - C3 1) 
#  order: 14
#  hide: True
#  line-color: '#b3b307'
#  fill-color: '#b3b307'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - VBFHHTo2B2Tau_CV_0_5_C2V_1_C3_1_dipoleRecoilOff.root
#qqHH_CV_1p5_C2V_1_kl_1_hbbhtt:
#  type: mc
#  legend: HH bb#tau#tau VBF (CV 1.5 - C2V 1 - C3 1) 
#  order: 14
#  hide: True
#  line-color: '#b3b307'
#  fill-color: '#b3b307'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - VBFHHTo2B2Tau_CV_1_5_C2V_1_C3_1_dipoleRecoilOff.root
#qqHH_CV_1_C2V_0_kl_1_hbbhtt:
#  type: mc
#  legend: HH bb#tau#tau VBF (CV 1 - C2V 0 - C3 1) 
#  order: 14
#  hide: True
#  line-color: '#b3b307'
#  fill-color: '#b3b307'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - VBFHHTo2B2Tau_CV_1_C2V_0_C3_1_dipoleRecoilOff.root
#qqHH_CV_1_C2V_1_kl_0_hbbhtt:
#  type: mc
#  legend: HH bb#tau#tau VBF (CV 1 - C2V 1 - C3 0) 
#  order: 14
#  hide: True
#  line-color: '#b3b307'
#  fill-color: '#b3b307'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - VBFHHTo2B2Tau_CV_1_C2V_1_C3_0_dipoleRecoilOff.root
qqHH_CV_1_C2V_1_kl_1_hbbhtt:
  type: mc
  legend: HH bb#tau#tau VBF (CV 1 - C2V 1 - C3 1) 
  order: 14
  hide: True
  line-color: '#b3b307'
  fill-color: '#b3b307'
  line-type: 1
  line-width: 2
  fill-type: 3354
  files:
    - VBFHHTo2B2Tau_CV_1_C2V_1_C3_1_dipoleRecoilOff.root
#qqHH_CV_1_C2V_1_kl_2_hbbhtt:
#  type: mc
#  legend: HH bb#tau#tau VBF (CV 1 - C2V 1 - C3 2) 
#  order: 14
#  hide: True
#  line-color: '#b3b307'
#  fill-color: '#b3b307'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - VBFHHTo2B2Tau_CV_1_C2V_1_C3_2_dipoleRecoilOff.root
#qqHH_CV_1_C2V_2_kl_1_hbbhtt:
#  type: mc
#  legend: HH bb#tau#tau VBF (CV 1 - C2V 2 - C3 1) 
#  order: 14
#  hide: True
#  line-color: '#b3b307'
#  fill-color: '#b3b307'
#  line-type: 1
#  line-width: 2
#  fill-type: 3354
#  files:
#    - VBFHHTo2B2Tau_CV_1_C2V_2_C3_1_dipoleRecoilOff.root
#
#
