DY:
  fill-color: '#1a83a1'
  legend: Drell-Yan 
  order: 3
  type: mc
  files:
    - DYJetsToLL_M-10to50.root
    - DYJetsToLL_M-50.root
    - DYToLL_0J.root
    - DYToLL_1J.root
    - DYToLL_2J.root

