signal_ggf_spin0_{mass}_hbbhww:
  type: signal  
  legend: "X (spin-0,{mass} GeV) #rightarrow HH"
  group: HH
  order: 14
  line-color: '#c91a26'
  fill-color: '#c91a26'
  line-type: 1
  line-width: 2
  fill-type: 3345
  files:
    - GluGluToRadionToHHTo2B2VTo2L2Nu_M-{mass}.root
signal_ggf_spin0_{mass}_hbbhtt:
  type: signal
  legend: "X (spin-0,{mass} GeV) #rightarrow HH"
  group: HH
  order: 14
  line-color: '#c91a26'
  fill-color: '#c91a26'
  line-type: 1
  line-width: 2
  fill-type: 3354
  files:
    - GluGluToRadionToHHTo2B2Tau_M-{mass}.root

