data_obs: 
  legend: data
  type: data
  files:
    - DoubleEGamma_2016B0.root
    - DoubleEGamma_2016B1.root
    - DoubleEGamma_2016C.root
    - DoubleEGamma_2016D.root
    - DoubleEGamma_2016E.root
    - DoubleEGamma_2016F.root
    - DoubleEGamma_2016G.root
    - DoubleEGamma_2016H0.root
    - DoubleEGamma_2016H1.root
    - DoubleMuon_2016B0.root
    - DoubleMuon_2016B1.root
    - DoubleMuon_2016C.root
    - DoubleMuon_2016D.root
    - DoubleMuon_2016E.root
    - DoubleMuon_2016F.root
    - DoubleMuon_2016G.root
    - DoubleMuon_2016H0.root
    - DoubleMuon_2016H1.root
    - MuonEG_2016B0.root
    - MuonEG_2016B1.root
    - MuonEG_2016C.root
    - MuonEG_2016D.root
    - MuonEG_2016E.root
    - MuonEG_2016F.root
    - MuonEG_2016G.root
    - MuonEG_2016H0.root
    - MuonEG_2016H1.root
    - SingleElectron_2016B0.root
    - SingleElectron_2016B1.root
    - SingleElectron_2016C.root
    - SingleElectron_2016D.root
    - SingleElectron_2016E.root
    - SingleElectron_2016F.root
    - SingleElectron_2016G.root
    - SingleElectron_2016H0.root
    - SingleElectron_2016H1.root
    - SingleMuon_2016B0.root
    - SingleMuon_2016B1.root
    - SingleMuon_2016C.root
    - SingleMuon_2016D.root
    - SingleMuon_2016E.root
    - SingleMuon_2016F.root
    - SingleMuon_2016G.root
    - SingleMuon_2016H0.root
    - SingleMuon_2016H1.root

