outputDir: Scans/Resonant_radion_syst_comparison_FR2

legend:
  position: [0.50,0.45,0.85,0.90]
  textsize: 0.02

combine: 
   limits_DL: limits
   limits_SL: limits
   limits_combined: limits
   gof: gof
   pulls: pulls
   impacts: impacts

plotting_limit: &plotting_limit
    lines:
        SetLineWidth: 2 
        SetLineStyle: 1 
    legend: 
        SetX1NDC: 0.50
        SetX2NDC: 0.85
        SetY1NDC: 0.45
        SetY2NDC: 0.90
        SetFillColor: 0
        SetTextFont: 42
        SetTextSize: 0.02
    canvas: 
        SetWindowPosition: [800,600]
        SetLeftMargin: 0.15
        SetRightMargin: 0.1
        SetTopMargin: 0.05
        SetBottomMargin: 0.10
        SetLogy: True
        SetGridx: True 
        SetGridy: True
        SetTickx: True
        SetTicky: True


curves:
  #########################################################################
  #                                   1D                                  #
  #########################################################################
    1D FR2:
        modes:
            limits_DL:
                subdirs: 
                    combination:      {SetLineColor:'#D81B60'}
                    combination_2016: {SetLineColor:'#1E88E5'}
                    combination_2017: {SetLineColor:'#FFC107'}
                    combination_2018: {SetLineColor:'#004D40'}
                plotting: *plotting_limit
            limits_SL:
                subdirs: 
                    combination:      {SetLineColor:'#D81B60'}
                plotting: *plotting_limit
            limits_combined:
                subdirs: 
                    combination:      {SetLineColor:'#D81B60'}
                plotting: *plotting_limit
        points:
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=260 branch=LowMass   
              label: 260
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=270 branch=LowMass   
              label: 270
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=280 branch=LowMass  --interpolation config/interpolation_DL_res.yml param1=270 param2=300 paramInt=280 --interpolation_config1 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=270 branch=LowMass --interpolation_config2 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=300 branch=LowMass --interpolation_era 2016
              label: 280
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=300 branch=LowMass  --interpolation config/interpolation_DL_res.yml param1=280 param2=320 paramInt=300 --interpolation_config1 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=280 branch=LowMass --interpolation_config2 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=320 branch=LowMass --interpolation_era 2017
              label: 300
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=350 branch=LowMass
              label: 350
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=400 branch=LowMass
              label: 400
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=450 branch=LowMass  --interpolation config/interpolation_DL_res.yml param1=400 param2=500 paramInt=450 --interpolation_config1 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=400 branch=LowMass --interpolation_config2 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=500 branch=LowMass --interpolation_era 2018
              label: 450 
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=500 branch=LowMass 
              label: 500
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=550 branch=HighMass  --interpolation config/interpolation_DL_res.yml param1=500 param2=600 paramInt=550 --interpolation_config1 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=500 branch=HighMass --interpolation_config2 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=600 branch=HighMass --interpolation_era 2017
              label: 550
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=600 branch=HighMass
              label: 600
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=650 branch=HighMass  --interpolation config/interpolation_DL_res.yml param1=600 param2=750 paramInt=650 --interpolation_config1 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=600 branch=HighMass --interpolation_config2 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=750 branch=HighMass --interpolation_era 2016
              label: 650
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=700 branch=HighMass  --interpolation config/interpolation_DL_res.yml param1=600 param2=750 paramInt=700 --interpolation_config1 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=600 branch=HighMass --interpolation_config2 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=750 branch=HighMass --interpolation_era 2016
              label: 700
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=750 branch=HighMass  
              label: 750
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=800 branch=HighMass  
              label: 800
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=850 branch=HighMass  --interpolation config/interpolation_DL_res.yml param1=800 param2=900 paramInt=850 --interpolation_config1 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=800 branch=HighMass --interpolation_config2 config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml mass=900 branch=HighMass --interpolation_era 2016
              label: 850
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_1D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=9000 --custom mass=900 branch=HighMass  
              label: 900
      

    #########################################################################
    #                                   2D                                  #
    #########################################################################
    2D FR2:
        modes:
            limits_DL:
                subdirs: 
                    combination:      {SetLineColor:'#D81B60'}
                    combination_2016: {SetLineColor:'#1E88E5'}
                    combination_2017: {SetLineColor:'#FFC107'}
                    combination_2018: {SetLineColor:'#004D40'}
                plotting: *plotting_limit
            limits_SL:
                subdirs: 
                    combination:      {SetLineColor:'#D81B60'}
                plotting: *plotting_limit
            limits_combined:
                subdirs: 
                    combination:      {SetLineColor:'#D81B60'}
                plotting: *plotting_limit

        points:
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=260 branch=LowMass   
              label: 260
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=270 branch=LowMass   
              label: 270
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=280 branch=LowMass  --interpolation config/interpolation_DL_res.yml param1=270 param2=300 paramInt=280 --interpolation_config1 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=270 branch=LowMass --interpolation_config2 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=300 branch=LowMass --interpolation_era 2016
              label: 280
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=300 branch=LowMass  --interpolation config/interpolation_DL_res.yml param1=280 param2=320 paramInt=300 --interpolation_config1 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=280 branch=LowMass --interpolation_config2 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=320 branch=LowMass --interpolation_era 2017
              label: 300
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=350 branch=LowMass
              label: 350
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=400 branch=LowMass
              label: 400
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=450 branch=LowMass  --interpolation config/interpolation_DL_res.yml param1=400 param2=500 paramInt=450 --interpolation_config1 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=400 branch=LowMass --interpolation_config2 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=500 branch=LowMass --interpolation_era 2018
              label: 450 
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=500 branch=LowMass 
              label: 500
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=550 branch=HighMass  --interpolation config/interpolation_DL_res.yml param1=500 param2=600 paramInt=550 --interpolation_config1 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=500 branch=HighMass --interpolation_config2 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=600 branch=HighMass --interpolation_era 2017
              label: 550
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=600 branch=HighMass
              label: 600
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=650 branch=HighMass  --interpolation config/interpolation_DL_res.yml param1=600 param2=750 paramInt=650 --interpolation_config1 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=600 branch=HighMass --interpolation_config2 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=750 branch=HighMass --interpolation_era 2016
              label: 650
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=700 branch=HighMass  --interpolation config/interpolation_DL_res.yml param1=600 param2=750 paramInt=700 --interpolation_config1 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=600 branch=HighMass --interpolation_config2 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=750 branch=HighMass --interpolation_era 2016
              label: 700
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=750 branch=HighMass  
              label: 750
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=800 branch=HighMass  
              label: 800
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=850 branch=HighMass  --interpolation config/interpolation_DL_res.yml param1=800 param2=900 paramInt=850 --interpolation_config1 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=800 branch=HighMass --interpolation_config2 config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml mass=900 branch=HighMass --interpolation_era 2016
              label: 850
            - command: python produceDataCards.py --yaml config/datacard_fit_Resonant_Radion_2D_syst_M_base_FR2.yml --split --submit time=0-08:00:00  mem-per-cpu=12000 --custom mass=900 branch=HighMass  
              label: 900

    
    











