  2016:
    - module: nonclosure.py:NonClosureDY
      init: 
        path_json: config/fit_results_Res{branch}.json
      categories: 
        HH_DL_{mass}_inclusive_DY_VVV : 
          key:      HH_{mass}_inclusive_DY_VVV_2016 
          systName: dy_inclusive_nonclosure_dy_vvv
        HH_DL_{mass}_resolved_other: 
          key:      HH_{mass}_resolved_other_2016
          systName: dy_resolved_nonclosure_other
        HH_DL_{mass}_boosted_other:
          key:      HH_{mass}_boosted_other
          systName: dy_boosted_nonclosure_other
  2017:
    - module: nonclosure.py:NonClosureDY
      init: 
        path_json: config/fit_results_Res{branch}.json
      categories: 
        HH_DL_{mass}_inclusive_DY_VVV : 
          key:      HH_{mass}_inclusive_DY_VVV_2017 
          systName: dy_inclusive_nonclosure_dy_vvv
        HH_DL_{mass}_resolved_other: 
          key:      HH_{mass}_resolved_other_2017
          systName: dy_resolved_nonclosure_other
        HH_DL_{mass}_boosted_other:
          key:      HH_{mass}_boosted_other
          systName: dy_boosted_nonclosure_other
  2018:
    - module: nonclosure.py:NonClosureDY
      init: 
        path_json: config/fit_results_Res{branch}.json
      categories: 
        HH_DL_{mass}_inclusive_DY_VVV : 
          key:      HH_{mass}_inclusive_DY_VVV_2018 
          systName: dy_inclusive_nonclosure_dy_vvv
        HH_DL_{mass}_resolved_other: 
          key:      HH_{mass}_resolved_other_2018
          systName: dy_resolved_nonclosure_other
        HH_DL_{mass}_boosted_other:
          key:      HH_{mass}_boosted_other
          systName: dy_boosted_nonclosure_other

