    ###############  2016 ###################
    module: nonclosure.py:NonClosureFake
    init: 
      path_json: config/factors_SL_Fake_2016.json
    categories: 
      HH_e_resolved1b_GGF:
        key:      HH_e_resolved1b_GGF_2016
        systName: fake_nc_e_res1b_GGF
      HH_m_resolved1b_GGF:
        key:      HH_m_resolved1b_GGF_2016
        systName: fake_nc_m_res1b_GGF
      HH_e_resolved1b_VBF:
        key:      HH_e_resolved1b_VBF_2016
        systName: fake_nc_e_res1b_VBF
      HH_m_resolved1b_VBF:
        key:      HH_m_resolved1b_VBF_2016
        systName: fake_nc_m_res1b_VBF
      HH_e_resolved2b_GGF:
        key:      HH_e_resolved2b_GGF_2016
        systName: fake_nc_e_res2b_GGF
      HH_m_resolved2b_GGF:
        key:      HH_m_resolved2b_GGF_2016
        systName: fake_nc_m_res2b_GGF
      HH_e_resolved2b_VBF:
        key:      HH_e_resolved2b_VBF_2016
        systName: fake_nc_e_res2b_VBF
      HH_m_resolved2b_VBF:
        key:      HH_m_resolved2b_VBF_2016
        systName: fake_nc_m_res2b_VBF
      HH_e_boosted_GGF:
        key:      HH_e_boosted_GGF_2016
        systName: fake_nc_e_boosted_GGF
      HH_m_boosted_GGF:
        key:      HH_m_boosted_GGF_2016
        systName: fake_nc_m_boosted_GGF
      HH_e_boosted_VBF:
        key:      HH_e_boosted_VBF_2016
        systName: fake_nc_e_boosted_VBF
      HH_m_boosted_VBF:
        key:      HH_m_boosted_VBF_2016
        systName: fake_nc_m_boosted_VBF
      HH_e_inclusive_WJets:
        key:      HH_e_inclusive_WJets_2016
        systName: fake_nc_e_inc_wjets
      HH_m_inclusive_WJets:
        key:      HH_m_inclusive_WJets_2016
        systName: fake_nc_m_inc_wjets
      HH_e_inclusive_OtherH:
        key:      HH_e_inclusive_OtherH_2016
        systName: fake_nc_e_inc_otherh
      HH_m_inclusive_OtherH:
        key:      HH_m_inclusive_OtherH_2016
        systName: fake_nc_m_inc_otherh
      HH_e_resolved_Top:
        key:      HH_e_resolved_Top_2016
        systName: fake_nc_e_res_top
      HH_m_resolved_Top:
        key:      HH_m_resolved_Top_2016
        systName: fake_nc_m_res_top
      HH_e_boosted_Top:
        key:      HH_e_boosted_Top_2016
        systName: fake_nc_e_boosted_top
      HH_m_boosted_Top:
        key:      HH_m_boosted_Top_2016
        systName: fake_nc_m_boosted_top

    ###############  2017 ###################
    module: nonclosure.py:NonClosureFake
    init: 
      path_json: config/factors_SL_Fake_2017.json
    categories: 
      HH_e_resolved1b_GGF:
        key:      HH_e_resolved1b_GGF_2017
        systName: fake_nc_e_res1b_GGF
      HH_m_resolved1b_GGF:
        key:      HH_m_resolved1b_GGF_2017
        systName: fake_nc_m_res1b_GGF
      HH_e_resolved1b_VBF:
        key:      HH_e_resolved1b_VBF_2017
        systName: fake_nc_e_res1b_VBF
      HH_m_resolved1b_VBF:
        key:      HH_m_resolved1b_VBF_2017
        systName: fake_nc_m_res1b_VBF
      HH_e_resolved2b_GGF:
        key:      HH_e_resolved2b_GGF_2017
        systName: fake_nc_e_res2b_GGF
      HH_m_resolved2b_GGF:
        key:      HH_m_resolved2b_GGF_2017
        systName: fake_nc_m_res2b_GGF
      HH_e_resolved2b_VBF:
        key:      HH_e_resolved2b_VBF_2017
        systName: fake_nc_e_res2b_VBF
      HH_m_resolved2b_VBF:
        key:      HH_m_resolved2b_VBF_2017
        systName: fake_nc_m_res2b_VBF
      HH_e_boosted_GGF:
        key:      HH_e_boosted_GGF_2017
        systName: fake_nc_e_boosted_GGF
      HH_m_boosted_GGF:
        key:      HH_m_boosted_GGF_2017
        systName: fake_nc_m_boosted_GGF
      HH_e_boosted_VBF:
        key:      HH_e_boosted_VBF_2017
        systName: fake_nc_e_boosted_VBF
      HH_m_boosted_VBF:
        key:      HH_m_boosted_VBF_2017
        systName: fake_nc_m_boosted_VBF
      HH_e_inclusive_WJets:
        key:      HH_e_inclusive_WJets_2017
        systName: fake_nc_e_inc_wjets
      HH_m_inclusive_WJets:
        key:      HH_m_inclusive_WJets_2017
        systName: fake_nc_m_inc_wjets
      HH_e_inclusive_OtherH:
        key:      HH_e_inclusive_OtherH_2017
        systName: fake_nc_e_inc_otherh
      HH_m_inclusive_OtherH:
        key:      HH_m_inclusive_OtherH_2017
        systName: fake_nc_m_inc_otherh
      HH_e_resolved_Top:
        key:      HH_e_resolved_Top_2017
        systName: fake_nc_e_res_top
      HH_m_resolved_Top:
        key:      HH_m_resolved_Top_2017
        systName: fake_nc_m_res_top
      HH_e_boosted_Top:
        key:      HH_e_boosted_Top_2017
        systName: fake_nc_e_boosted_top
      HH_m_boosted_Top:
        key:      HH_m_boosted_Top_2017
        systName: fake_nc_m_boosted_top


    ###############  2018 ###################
    module: nonclosure.py:NonClosureFake
    init: 
      path_json: config/factors_SL_Fake_2018.json
    categories: 
      HH_e_resolved1b_GGF:
        key:      HH_e_resolved1b_GGF_2018
        systName: fake_nc_e_res1b_GGF
      HH_m_resolved1b_GGF:
        key:      HH_m_resolved1b_GGF_2018
        systName: fake_nc_m_res1b_GGF
      HH_e_resolved1b_VBF:
        key:      HH_e_resolved1b_VBF_2018
        systName: fake_nc_e_res1b_VBF
      HH_m_resolved1b_VBF:
        key:      HH_m_resolved1b_VBF_2018
        systName: fake_nc_m_res1b_VBF
      HH_e_resolved2b_GGF:
        key:      HH_e_resolved2b_GGF_2018
        systName: fake_nc_e_res2b_GGF
      HH_m_resolved2b_GGF:
        key:      HH_m_resolved2b_GGF_2018
        systName: fake_nc_m_res2b_GGF
      HH_e_resolved2b_VBF:
        key:      HH_e_resolved2b_VBF_2018
        systName: fake_nc_e_res2b_VBF
      HH_m_resolved2b_VBF:
        key:      HH_m_resolved2b_VBF_2018
        systName: fake_nc_m_res2b_VBF
      HH_e_boosted_GGF:
        key:      HH_e_boosted_GGF_2018
        systName: fake_nc_e_boosted_GGF
      HH_m_boosted_GGF:
        key:      HH_m_boosted_GGF_2018
        systName: fake_nc_m_boosted_GGF
      HH_e_boosted_VBF:
        key:      HH_e_boosted_VBF_2018
        systName: fake_nc_e_boosted_VBF
      HH_m_boosted_VBF:
        key:      HH_m_boosted_VBF_2018
        systName: fake_nc_m_boosted_VBF
      HH_e_inclusive_WJets:
        key:      HH_e_inclusive_WJets_2018
        systName: fake_nc_e_inc_wjets
      HH_m_inclusive_WJets:
        key:      HH_m_inclusive_WJets_2018
        systName: fake_nc_m_inc_wjets
      HH_e_inclusive_OtherH:
        key:      HH_e_inclusive_OtherH_2018
        systName: fake_nc_e_inc_otherh
      HH_m_inclusive_OtherH:
        key:      HH_m_inclusive_OtherH_2018
        systName: fake_nc_m_inc_otherh
      HH_e_resolved_Top:
        key:      HH_e_resolved_Top_2018
        systName: fake_nc_e_res_top
      HH_m_resolved_Top:
        key:      HH_m_resolved_Top_2018
        systName: fake_nc_m_res_top
      HH_e_boosted_Top:
        key:      HH_e_boosted_Top_2018
        systName: fake_nc_e_boosted_top
      HH_m_boosted_Top:
        key:      HH_m_boosted_Top_2018
        systName: fake_nc_m_boosted_top


