#################################
#        Miscellanious          #
#################################

# m_top_unc_HH -> removed in favor of THU_HH which is added automatically by the physics model (still need for resonant though)
m_top_unc_HH:
  group:
  # Resonant #
  - signal_ggf_{spin}_250_hbbhww
  - signal_ggf_{spin}_260_hbbhww
  - signal_ggf_{spin}_270_hbbhww
  - signal_ggf_{spin}_280_hbbhww
  - signal_ggf_{spin}_300_hbbhww
  - signal_ggf_{spin}_320_hbbhww
  - signal_ggf_{spin}_350_hbbhww
  - signal_ggf_{spin}_400_hbbhww
  - signal_ggf_{spin}_450_hbbhww
  - signal_ggf_{spin}_500_hbbhww
  - signal_ggf_{spin}_550_hbbhww
  - signal_ggf_{spin}_600_hbbhww
  - signal_ggf_{spin}_650_hbbhww
  - signal_ggf_{spin}_700_hbbhww
  - signal_ggf_{spin}_750_hbbhww
  - signal_ggf_{spin}_800_hbbhww
  - signal_ggf_{spin}_850_hbbhww
  - signal_ggf_{spin}_900_hbbhww
  - signal_ggf_{spin}_250_hbbhtt
  - signal_ggf_{spin}_260_hbbhtt
  - signal_ggf_{spin}_270_hbbhtt
  - signal_ggf_{spin}_280_hbbhtt
  - signal_ggf_{spin}_300_hbbhtt
  - signal_ggf_{spin}_320_hbbhtt
  - signal_ggf_{spin}_350_hbbhtt
  - signal_ggf_{spin}_400_hbbhtt
  - signal_ggf_{spin}_450_hbbhtt
  - signal_ggf_{spin}_500_hbbhtt
  - signal_ggf_{spin}_550_hbbhtt
  - signal_ggf_{spin}_600_hbbhtt
  - signal_ggf_{spin}_650_hbbhtt
  - signal_ggf_{spin}_700_hbbhtt
  - signal_ggf_{spin}_750_hbbhtt
  - signal_ggf_{spin}_800_hbbhtt
  - signal_ggf_{spin}_850_hbbhtt
  - signal_ggf_{spin}_900_hbbhtt
  val: [0.82,1.04]

m_top_unc_tt:
  group:
  - TT
  val: [0.973,1.028]

EW_corr_ttZ:
  group:
  - ttZ
  val: [0.998,1.0]

EW_corr_ttW:
  group:
  - ttW
  val: [0.968,1.0]

total_VVV: # cross section uncertainty
  group: VVV
  val : [0.999,1.001]
#  https://cms-gen-dev.cern.ch/xsdb/?searchQuery=DAS=WWZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8

integration_DY:
  group: DY
  cat : [".*SL.*"]
  val: [0.9998,1.0002]



