- !include norm_lumi.yml
- !include norm_BR.yml
- !include norm_QCDscale.yml
- !include norm_alpha_s.yml
- !include norm_pdf.yml
- !include norm_misc.yml
- !include norm_comb_process.yml
- !include norm_DY_Res{branch}.yml
- footer:
  - line: "CMS_bbww_TT rateParam * TT 1 [0,5]"
    group: TT
  - line: "CMS_bbww_ST rateParam * ST 1 [0,5]"
    group: ST
  - line: "CMS_bbww_WJets rateParam * WJets 1 [0,5]" 
    group: WJets
    cat: ".*SL.*"

