CMS_bbwwdl_DYEstimation_nonclosure_boosted_GGF:
  cat: HH_boosted_GGF
  group: DY
  val:
  - 0.41
  - 1.59
CMS_bbwwdl_DYEstimation_nonclosure_boosted_H:
  cat: HH_boosted_H
  group: DY
  val:
  - 0.818
  - 1.182
CMS_bbwwdl_DYEstimation_nonclosure_boosted_VBF:
  cat: HH_boosted_VBF
  group: DY
  val:
  - 0.754
  - 1.246
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_GGF_2016:
  era: '2016'
  cat: HH_resolved1b_GGF
  group: DY
  val:
  - 0.917
  - 1.083
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_GGF_2017:
  era: '2017'
  cat: HH_resolved1b_GGF
  group: DY
  val:
  - 0.798
  - 1.202
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_GGF_2018:
  era: '2018'
  cat: HH_resolved1b_GGF
  group: DY
  val:
  - 0.801
  - 1.199
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_H_2016:
  era: '2016'
  cat: HH_resolved1b_H
  group: DY
  val:
  - 0.593
  - 1.407
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_H_2017:
  era: '2017'
  cat: HH_resolved1b_H
  group: DY
  val:
  - 0.939
  - 1.061
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_H_2018:
  era: '2018'
  cat: HH_resolved1b_H
  group: DY
  val:
  - 0.741
  - 1.259
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_VBF_2016:
  era: '2016'
  cat: HH_resolved1b_VBF
  group: DY
  val:
  - 0.405
  - 1.595
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_VBF_2017:
  era: '2017'
  cat: HH_resolved1b_VBF
  group: DY
  val:
  - 0.88
  - 1.12
CMS_bbwwdl_DYEstimation_nonclosure_resolved1b_VBF_2018:
  era: '2018'
  cat: HH_resolved1b_VBF
  group: DY
  val:
  - 0.882
  - 1.118
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_GGF_2016:
  era: '2016'
  cat: HH_resolved2b_GGF
  group: DY
  val:
  - 0.675
  - 1.325
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_GGF_2017:
  era: '2017'
  cat: HH_resolved2b_GGF
  group: DY
  val:
  - 0.946
  - 1.054
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_GGF_2018:
  era: '2018'
  cat: HH_resolved2b_GGF
  group: DY
  val:
  - 0.316
  - 1.684
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_H_2016:
  era: '2016'
  cat: HH_resolved2b_H
  group: DY
  val:
  - 0.01
  - 1.99
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_H_2017:
  era: '2017'
  cat: HH_resolved2b_H
  group: DY
  val:
  - 0.53
  - 1.47
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_H_2018:
  era: '2018'
  cat: HH_resolved2b_H
  group: DY
  val:
  - 0.62
  - 1.38
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_VBF_2016:
  era: '2016'
  cat: HH_resolved2b_VBF
  group: DY
  val:
  - 0.608
  - 1.392
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_VBF_2017:
  era: '2017'
  cat: HH_resolved2b_VBF
  group: DY
  val:
  - 0.917
  - 1.083
CMS_bbwwdl_DYEstimation_nonclosure_resolved2b_VBF_2018:
  era: '2018'
  cat: HH_resolved2b_VBF
  group: DY
  val:
  - 0.731
  - 1.269
