#################################
#            alpha_s            # 
#################################

alpha_s:
  - group:
    - ggH_hww
    - ggH_hbb
    - ggH_hgg
    - ggH_hmm
    - ggH_htt
    - ggH_hww
    - ggH_hzz
    val: 1.026
  - group:
    - qqH_hww
    - qqH_hbb
    - qqH_hgg
    - qqH_hmm
    - qqH_htt
    - qqH_hww
    - qqH_hzz
    val: 1.005
  - group:
    - ZH_hbb
    - ZH_htt
    - ZH_hww
    - VH_hww
    val: 1.009
  - group:
    - WH_hbb
    val: 1.009
  - group:
    - ttH_hbb
    - ttH_hww
    val: 1.02
  - group:
    - tHq_hww
    val: 1.012
  - group:
    - tHW_hww
    val: 1.015

# alpha_s_ggHH -> already taken into account in pdf_ggHH
#alpha_s_ggHH: 
#  group:
#  # Resonant #
#  - signal_ggf_{spin}_250_hbbhww
#  - signal_ggf_{spin}_260_hbbhww
#  - signal_ggf_{spin}_270_hbbhww
#  - signal_ggf_{spin}_280_hbbhww
#  - signal_ggf_{spin}_300_hbbhww
#  - signal_ggf_{spin}_320_hbbhww
#  - signal_ggf_{spin}_350_hbbhww
#  - signal_ggf_{spin}_400_hbbhww
#  - signal_ggf_{spin}_450_hbbhww
#  - signal_ggf_{spin}_500_hbbhww
#  - signal_ggf_{spin}_550_hbbhww
#  - signal_ggf_{spin}_600_hbbhww
#  - signal_ggf_{spin}_650_hbbhww
#  - signal_ggf_{spin}_700_hbbhww
#  - signal_ggf_{spin}_750_hbbhww
#  - signal_ggf_{spin}_800_hbbhww
#  - signal_ggf_{spin}_850_hbbhww
#  - signal_ggf_{spin}_900_hbbhww
#  - signal_ggf_{spin}_250_hbbhtt
#  - signal_ggf_{spin}_260_hbbhtt
#  - signal_ggf_{spin}_270_hbbhtt
#  - signal_ggf_{spin}_280_hbbhtt
#  - signal_ggf_{spin}_300_hbbhtt
#  - signal_ggf_{spin}_320_hbbhtt
#  - signal_ggf_{spin}_350_hbbhtt
#  - signal_ggf_{spin}_400_hbbhtt
#  - signal_ggf_{spin}_450_hbbhtt
#  - signal_ggf_{spin}_500_hbbhtt
#  - signal_ggf_{spin}_550_hbbhtt
#  - signal_ggf_{spin}_600_hbbhtt
#  - signal_ggf_{spin}_650_hbbhtt
#  - signal_ggf_{spin}_700_hbbhtt
#  - signal_ggf_{spin}_750_hbbhtt
#  - signal_ggf_{spin}_800_hbbhtt
#  - signal_ggf_{spin}_850_hbbhtt
#  - signal_ggf_{spin}_900_hbbhtt
#  val: 1.021
