#################################
#         Ad hoc norm           # 
#################################
CMS_bbww_TT_norm:
  group: 
    - TT
  val: 1.2

CMS_bbww_ST_norm:
  group: 
    - ST
  val: 1.2

CMS_bbww_WJets_norm:
  group: 
    - WJets
  val: 1.2

CMS_bbwwsl_fakes_norm:
  group:
    - Fakes
  val: 1.3

CMS_bbwwsl_ST_norm_boost:
  cat: 
    - HH_DL_boosted_GGF
    - HH_DL_boosted_VBF
    - HH_DL_boosted_Top
  group: 
    - ST
  val: 1.2

CMS_bbwwsl_TT_norm_boost:
  cat: 
    - HH_DL_boosted_GGF
    - HH_DL_boosted_VBF
    - HH_DL_boosted_Top
  group: 
    - TT
  val: 1.2

