CMS_bbwwdl_DY_ncc_boosted_GGF:
  cat: HH_DL_boosted_GGF
  group: DY
  val:
  - 0.599
  - 1.401
CMS_bbwwdl_DY_ncc_boosted_VBF:
  cat: HH_DL_boosted_VBF
  group: DY
  val:
  - 0.765
  - 1.235
CMS_bbwwdl_DY_ncc_resolved1b_GGF_2016:
  cat: HH_DL_resolved1b_GGF
  era: '2016'
  group: DY
  val:
  - 0.882
  - 1.118
CMS_bbwwdl_DY_ncc_resolved1b_GGF_2017:
  cat: HH_DL_resolved1b_GGF
  era: '2017'
  group: DY
  val:
  - 0.984
  - 1.016
CMS_bbwwdl_DY_ncc_resolved1b_GGF_2018:
  cat: HH_DL_resolved1b_GGF
  era: '2018'
  group: DY
  val:
  - 0.915
  - 1.085
CMS_bbwwdl_DY_ncc_resolved1b_VBF_2016:
  cat: HH_DL_resolved1b_VBF
  era: '2016'
  group: DY
  val:
  - 0.559
  - 1.441
CMS_bbwwdl_DY_ncc_resolved1b_VBF_2017:
  cat: HH_DL_resolved1b_VBF
  era: '2017'
  group: DY
  val:
  - 0.871
  - 1.129
CMS_bbwwdl_DY_ncc_resolved1b_VBF_2018:
  cat: HH_DL_resolved1b_VBF
  era: '2018'
  group: DY
  val:
  - 0.748
  - 1.252
CMS_bbwwdl_DY_ncc_resolved2b_GGF_2016:
  cat: HH_DL_resolved2b_GGF
  era: '2016'
  group: DY
  val:
  - 0.326
  - 1.674
CMS_bbwwdl_DY_ncc_resolved2b_GGF_2017:
  cat: HH_DL_resolved2b_GGF
  era: '2017'
  group: DY
  val:
  - 0.926
  - 1.074
CMS_bbwwdl_DY_ncc_resolved2b_GGF_2018:
  cat: HH_DL_resolved2b_GGF
  era: '2018'
  group: DY
  val:
  - 0.4
  - 1.6
CMS_bbwwdl_DY_ncc_resolved2b_VBF_2016:
  cat: HH_DL_resolved2b_VBF
  era: '2016'
  group: DY
  val:
  - 0.713
  - 1.287
CMS_bbwwdl_DY_ncc_resolved2b_VBF_2017:
  cat: HH_DL_resolved2b_VBF
  era: '2017'
  group: DY
  val:
  - 0.993
  - 1.007
CMS_bbwwdl_DY_ncc_resolved2b_VBF_2018:
  cat: HH_DL_resolved2b_VBF
  era: '2018'
  group: DY
  val:
  - 0.658
  - 1.342
