- !include norm_lumi.yml
- !include norm_BR.yml
- !include norm_QCDscale.yml
- !include norm_alpha_s.yml
- !include norm_pdf.yml
- !include norm_misc.yml
- !include norm_comb_nonres_process.yml
#- !include norm_fakes.yml
- !include norm_DY_NonRes.yml
- !include norm_dipolRecoil.yml
- footer: !include norm_footer_comb.yml

