CMS_bbwwdl_fakes_norm_boosted_DY_VVV_2017:
  cat: HH_DL_boosted_DY_VVV
  group: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_resolved_DY_VVV_2017:
  cat: HH_DL_resolved_DY_VVV
  group: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_boosted_other_2017:
  cat: HH_DL_boosted_other
  group: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_resolved_other_2017:
  cat: HH_DL_resolved_other
  group: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_boosted_GGF_2017:
  cat: HH_DL_boosted_GGF
  group: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_resolved1b_GGF_2017:
  cat: HH_DL_resolved1b_GGF
  group: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_resolved2b_GGF_2017:
  cat: HH_DL_resolved2b_GGF
  group: Fakes
  val: 1.3
