#################################
#           QCD scale           # 
#################################
QCDscale_VH:
  - group:
    - ZH_hbb
    - ZH_htt
    - ZH_hww
    - VH_hww
    val: [0.97,1.038]
  - group: 
    - WH_hbb
    val: [0.993,1.005]

QCDscale_VV:
  group:
  - VV
  val: [0.978,1.025]

QCDscale_qqHH:
  group:
  - qqHH_CV_0p5_C2V_1_kl_1_hbbhww
  - qqHH_CV_1p5_C2V_1_kl_1_hbbhww
  - qqHH_CV_1_C2V_0_kl_1_hbbhww
  - qqHH_CV_1_C2V_1_kl_0_hbbhww
  - qqHH_CV_1_C2V_1_kl_1_hbbhww
  - qqHH_CV_1_C2V_1_kl_2_hbbhww
  - qqHH_CV_1_C2V_2_kl_1_hbbhww
  - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwsl
  - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwsl
  - qqHH_CV_1_C2V_0_kl_1_hbbhwwsl
  - qqHH_CV_1_C2V_1_kl_0_hbbhwwsl
  - qqHH_CV_1_C2V_1_kl_1_hbbhwwsl
  - qqHH_CV_1_C2V_1_kl_2_hbbhwwsl
  - qqHH_CV_1_C2V_2_kl_1_hbbhwwsl
  - qqHH_CV_0p5_C2V_1_kl_1_hbbhtt
  - qqHH_CV_1p5_C2V_1_kl_1_hbbhtt
  - qqHH_CV_1_C2V_0_kl_1_hbbhtt
  - qqHH_CV_1_C2V_1_kl_0_hbbhtt
  - qqHH_CV_1_C2V_1_kl_1_hbbhtt
  - qqHH_CV_1_C2V_1_kl_2_hbbhtt
  - qqHH_CV_1_C2V_2_kl_1_hbbhtt
  val: [0.9996,1.0003]

# QCDscale_ggHH -> removed in favor of THU_HH which is added automatically by the physics model

QCDscale_ttH:
  - group: [tHq_hww] 
    val: [0.853,1.065]
  - group: [tHW_hww]
    val: [0.933,1.049]
  - group: 
    - ttH_hbb
    - ttH_hww
    val: [0.908,1.058]

QCDscale_ttbar:
  - group: [TT]
    val: [0.9649,1.0238]
  - group: [ST]
    val: [0.978,1.0288]
  - group: [ttZ]
    val: [0.887,1.096]
  - group: [ttW]
    val: [0.885,1.129]

QCDscale_ggH:
  group:
  - ggH_hww
  - ggH_hbb
  - ggH_hgg
  - ggH_hmm
  - ggH_htt
  - ggH_hww
  - ggH_hzz
  val: 1.039

QCDscale_qqH:
  group:
  - qqH_hww
  - qqH_hbb
  - qqH_hgg
  - qqH_hmm
  - qqH_htt
  - qqH_hww
  - qqH_hzz
  val: [0.997, 1.004]


