legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3
unitary_bin_width: True
plots: 
  HH_DL_{mass}_resolved1b_GGF: 
    x-axis: 'DNN output'
    blinded-range: [0,100]
  HH_DL_{mass}_resolved2b_GGF: 
    x-axis: 'DNN output'
    blinded-range: [0,100]
  HH_DL_{mass}_boosted_GGF: 
    x-axis: 'DNN output'
    blinded-range: [0,100]
  HH_DL_{mass}_inclusive_DY_VVV: 
    x-axis: 'DNN output'
    blinded-range: discard
  HH_DL_{mass}_resolved_other: 
    x-axis: 'DNN output'
    blinded-range: discard
  HH_DL_{mass}_boosted_other: 
    x-axis: 'DNN output'
    blinded-range: discard
  
