#bin_name_original       : none
#datacard_original       : none
#merged_eras_fit         : False
#minY                    : 0.001
#maxY                    : 10000000000000.
#useLogPlot              : True
#labelX                  : MVA bin #
#number_columns_legend   : 3
#minYerr                 : -0.6
#maxYerr                 : 0.6
#cats_labels_height      : 5000000.

legend:
  columns: 3
  textsize: 0.05
  textfont: 42
  headersize: 0.07
  headerfont: 62
x-axis: 
  textsize: 0.1
  labelsize: 0.1
  offset: 1.2
  label: "DNN score bin #"
y-axis: 
  textsize: 0.06
  labelsize: 0.05
  offset: 1.2
  label: "Events"
logy: True
ratio:
  offset: 0.8
  titlesize: 0.08
  labelsize: 0.1
labels:
  textsize: 0.06

