# PDF #
Fact:   discard 
Renorm: discard
Mixed:  discard
Envelope: 
    CMS_bbwwdl_thu_shape: 
        cat: [".*DL.*"]
    CMS_bbwwsl_thu_shape:
        cat: [".*SL.*"]
    
underlying_event: underlying_event

# PS #
psFSR: 
    CMS_bbwwsl_ps_fsr:
        cat: [".*SL.*"]
    CMS_bbwwdl_ps_fsr:
        cat: [".*DL.*"]
psISR: 
    CMS_bbwwsl_ps_isr:
        cat: [".*SL.*"]
    CMS_bbwwdl_ps_isr:
        cat: [".*DL.*"]
    

# Basics #
L1PreFiring:        CMS_l1_ecal_prefiring_{era}
pileup:             CMS_pileup_{era}
ttbarweightsyst:    CMS_top_pT_reweighting

# Btag SF #
btagSF_:            CMS_btag_subjet_{era}
    # HF, LF, cferr1 and cferr2 are correlated across years
btagSF_cferr1:      CMS_btag_cferr1_2016_2017_2018
btagSF_cferr2:      CMS_btag_cferr2_2016_2017_2018
btagSF_hf:          CMS_btag_HF_2016_2017_2018
btagSF_lf:          CMS_btag_LF_2016_2017_2018

    # {hf,lf}stats{1,2} uncorrelated across eras
btagSF_hfstats1:    CMS_btag_hfstats1_{era}
btagSF_hfstats2:    CMS_btag_hfstats2_{era}
btagSF_lfstats1:    CMS_btag_lfstats1_{era}
btagSF_lfstats2:    CMS_btag_lfstats2_{era}

# Trigger SF #
ttH_singleMuon_trigSF:      
    CMS_bbwwsl_TriggerWeight_e_{era}:
        cat: [".*SL.*"]
ttH_singleElectron_trigSF:  
    CMS_bbwwsl_TriggerWeight_m_{era}:
        cat: [".*SL.*"]

ttH_doubleElectron_trigSF:  
    CMS_bbwwdl_TriggerWeight_ee_{era}:
        cat: [".*DL.*"]
ttH_doubleMuon_trigSF:      
    CMS_bbwwdl_TriggerWeight_mm_{era}:
        cat: [".*DL.*"]
ttH_electronMuon_trigSF:    
    CMS_bbwwdl_TriggerWeight_emu_{era}:
        cat: [".*DL.*"]



# Lepton SF #
el_loose:               CMS_eff_e_id_loose_{era}
el_tight:               CMS_eff_e_id_tight_{era}
el_tth:                 CMS_eff_e_id_tth_{era}
mu_loose:               CMS_eff_m_id_loose_{era}
mu_tight:               CMS_eff_m_id_tight_{era}
mu_tth:                 CMS_eff_m_id_tth_{era}


# FakeRates #
el_FR_Loose_SL_pt_syst:     
    CMS_bbwwsl_FakeRate_e_pt_{era}:
        cat: [".*SL.*"]
el_FR_Loose_SL_barrel_syst: 
    CMS_bbwwsl_FakeRate_e_barrel_{era}:
        cat: [".*SL.*"]
el_FR_Loose_SL_norm_syst:   
    CMS_bbwwsl_FakeRate_e_norm_{era}:
        cat: [".*SL.*"]
mu_FR_Loose_SL_pt_syst:     
    CMS_bbwwsl_FakeRate_m_pt_{era}:
        cat: [".*SL.*"]
mu_FR_Loose_SL_barrel_syst: 
    CMS_bbwwsl_FakeRate_m_barrel_{era}:
        cat: [".*SL.*"]
mu_FR_Loose_SL_norm_syst:   
    CMS_bbwwsl_FakeRate_m_norm_{era}:
        cat: [".*SL.*"]

el_FR_Loose_DL_barrel_syst: 
    CMS_bbwwdl_FakeRate_e_barrel_{era}:
        cat: [".*DL.*"]
el_FR_Loose_DL_norm_syst:   
    CMS_bbwwdl_FakeRate_e_norm_{era}:
        cat: [".*DL.*"]
el_FR_Loose_DL_pt_syst:     
    CMS_bbwwdl_FakeRate_e_pt_{era}:
        cat: [".*DL.*"]
electronCorrFR:             
    CMS_bbwwdl_FakeRate_e_nonclosure_{era}:
        cat: [".*DL.*"]
mu_FR_Loose_DL_barrel_syst: 
    CMS_bbwwdl_FakeRate_m_barrel_{era}:
        cat: [".*DL.*"]
mu_FR_Loose_DL_norm_syst:   
    CMS_bbwwdl_FakeRate_m_norm_{era}:
        cat: [".*DL.*"]
mu_FR_Loose_DL_pt_syst:     
    CMS_bbwwdl_FakeRate_m_pt_{era}:
        cat: [".*DL.*"]
muonCorrFR:                 
    CMS_bbwwdl_FakeRate_m_nonclosure_{era}:
        cat: [".*DL.*"]


# JER
jer:                    CMS_res_j_{era}

# Fatjet mass corrections 
jmr:                    CMS_AK8_JMR
jms:                    CMS_AK8_JMS
    # -> fatjets

# MET jet uncertainties
unclustEn:              CMS_unclusteredEnergy_{era}

# JES 
jesAbsolute:            CMS_scale_j_Abs
jesBBEC1:               CMS_scale_j_BBEC1
jesEC2:                 CMS_scale_j_EC2
jesHF:                  CMS_scale_j_HF
jesRelativeBal:         CMS_scale_j_RelBal
jesFlavorQCD:           CMS_scale_j_FlavQCD
jesHEMIssue:            CMS_HEM_{era}  


jesAbsolute_2016:       CMS_scale_j_Abs_2016
jesBBEC1_2016:          CMS_scale_j_BBEC1_2016
jesEC2_2016:            CMS_scale_j_EC2_2016
jesHF_2016:             CMS_scale_j_HF_2016
jesRelativeSample_2016: CMS_scale_j_RelSample_2016

jesAbsolute_2017:       CMS_scale_j_Abs_2017
jesBBEC1_2017:          CMS_scale_j_BBEC1_2017
jesEC2_2017:            CMS_scale_j_EC2_2017
jesHF_2017:             CMS_scale_j_HF_2017
jesRelativeSample_2017: CMS_scale_j_RelSample_2017

jesAbsolute_2018:       CMS_scale_j_Abs_2018
jesBBEC1_2018:          CMS_scale_j_BBEC1_2018
jesEC2_2018:            CMS_scale_j_EC2_2018
jesHF_2018:             CMS_scale_j_HF_2018
jesRelativeSample_2018: CMS_scale_j_RelSample_2018

# Jet PU ID #
jetpuid_eff:            CMS_eff_j_PUJET_id_{era}
jetpuid_mistag:         CMS_eff_j_PUJET_mistag_{era}

# DY #
dy_boosted_1b:          
    CMS_bbwwdl_DY_boost_{era}:
        cat: [".*DL.*"]
dy_resolved_1b:         
    CMS_bbwwdl_DY_resolved1b_{era}:
        cat: [".*DL.*"]
dy_resolved_2b:         
    CMS_bbwwdl_DY_resolved2b_{era}:
        cat: [".*DL.*"]

dy_resolved_nonclosure_dy_vvv_shape1 : 
    CMS_bbwwdl_DY_ncc1_resolved_dy_vvv_{era}:
        cat: [".*DL.*"]
dy_resolved_nonclosure_dy_vvv_shape2 : 
    CMS_bbwwdl_DY_ncc2_resolved_dy_vvv_{era}:
        cat: [".*DL.*"]
dy_resolved_nonclosure_top_shape1 : 
    CMS_bbwwdl_DY_ncc1_resolved_top_{era}:
        cat: [".*DL.*"]
dy_resolved_nonclosure_top_shape2 : 
    CMS_bbwwdl_DY_ncc2_resolved_top_{era}:
        cat: [".*DL.*"]
dy_boosted_nonclosure_top_shape1 : 
    CMS_bbwwdl_DY_ncc1_boosted_toph_{era}:
        cat: [".*DL.*"]
dy_boosted_nonclosure_top_shape2 : 
    CMS_bbwwdl_DY_ncc2_boosted_toph_{era}:
        cat: [".*DL.*"]
dy_boosted_nonclosure_dy_vvv_shape1 : 
    CMS_bbwwdl_DY_ncc1_boost_dy_vvv:
        cat: [".*DL.*"]
dy_boosted_nonclosure_dy_vvv_shape2 : 
    CMS_bbwwdl_DY_ncc2_boost_dy_vvv:
        cat: [".*DL.*"]
dy_inclusive_nonclosure_dy_vvv_shape1 : 
    CMS_bbwwdl_DY_ncc1_inclusive_dy_vvv_{era}:
        cat: [".*DL.*"]
dy_inclusive_nonclosure_dy_vvv_shape2 : 
    CMS_bbwwdl_DY_ncc2_inclusive_dy_vvv_{era}:
        cat: [".*DL.*"]
dy_resolved_nonclosure_other_shape1 : 
    CMS_bbwwdl_DY_ncc1_resolved_other_{era}:
        cat: [".*DL.*"]
dy_resolved_nonclosure_other_shape2 : 
    CMS_bbwwdl_DY_ncc2_resolved_other_{era}:
        cat: [".*DL.*"]
dy_boosted_nonclosure_other_shape1 : 
    CMS_bbwwdl_DY_ncc1_boosted_other:
        cat: [".*DL.*"]
dy_boosted_nonclosure_other_shape2 : 
    CMS_bbwwdl_DY_ncc2_boosted_other:
        cat: [".*DL.*"]
dy_inclusive_nonclosure_otherh_shape1 : 
    CMS_bbwwdl_DY_ncc1_inclusive_otherh_{era}:
        cat: [".*DL.*"]
dy_inclusive_nonclosure_otherh_shape2 : 
    CMS_bbwwdl_DY_ncc2_inclusive_otherh_{era}:
        cat: [".*DL.*"]
dy_inclusive_nonclosure_otherh_shape1 : 
    CMS_bbwwdl_DY_ncc1_inclusive_otherh_{era}:
        cat: [".*DL.*"]
dy_inclusive_nonclosure_otherh_shape2 : 
    CMS_bbwwdl_DY_ncc2_inclusive_otherh_{era}:
        cat: [".*DL.*"]

# Fake non closure #
fake_nc_e_res1b_GGF_nom:         CMS_bbwwsl_Clos_nom_e_res1b_GGF
fake_nc_e_res1b_GGF_slope:       CMS_bbwwsl_Clos_slope_mu_res1b_GGF
fake_nc_m_res1b_GGF_nom:         CMS_bbwwsl_Clos_nom_mu_res1b_GGF
fake_nc_m_res1b_GGF_slope:       CMS_bbwwsl_Clos_slope_mu_res1b_GGF
fake_nc_e_res1b_VBF_nom:         CMS_bbwwsl_Clos_nom_e_res1b_VBF
fake_nc_e_res1b_VBF_slope:       CMS_bbwwsl_Clos_slope_e_res1b_VBF
fake_nc_m_res1b_VBF_nom:         CMS_bbwwsl_Clos_nom_mu_res1b_VBF
fake_nc_m_res1b_VBF_slope:       CMS_bbwwsl_Clos_slope_mu_res1b_VBF
fake_nc_e_res2b_GGF_nom:         CMS_bbwwsl_Clos_nom_e_res2b_GGF
fake_nc_e_res2b_GGF_slope:       CMS_bbwwsl_Clos_slope_e_res2b_GGF
fake_nc_m_res2b_GGF_nom:         CMS_bbwwsl_Clos_nom_mu_res2b_GGF
fake_nc_m_res2b_GGF_slope:       CMS_bbwwsl_Clos_slope_mu_res2b_GGF
fake_nc_e_res2b_VBF_nom:         CMS_bbwwsl_Clos_nom_e_res2b_VBF
fake_nc_e_res2b_VBF_slope:       CMS_bbwwsl_Clos_slope_e_res2b_VBF
fake_nc_m_res2b_VBF_nom:         CMS_bbwwsl_Clos_nom_mu_res2b_VBF
fake_nc_m_res2b_VBF_slope:       CMS_bbwwsl_Clos_slope_mu_res2b_VBF
fake_nc_e_boosted_GGF_nom:       CMS_bbwwsl_Clos_nom_e_boosted_GGF
fake_nc_e_boosted_GGF_slope:     CMS_bbwwsl_Clos_slope_e_boosted_GGF
fake_nc_m_boosted_GGF_nom:       CMS_bbwwsl_Clos_nom_mu_boosted_GGF
fake_nc_m_boosted_GGF_slope:     CMS_bbwwsl_Clos_slope_mu_boosted_GGF
fake_nc_e_boosted_VBF_nom:       CMS_bbwwsl_Clos_nom_e_boosted_VBF
fake_nc_e_boosted_VBF_slope:     CMS_bbwwsl_Clos_slope_e_boosted_VBF
fake_nc_m_boosted_VBF_nom:       CMS_bbwwsl_Clos_nom_mu_boosted_VBF
fake_nc_m_boosted_VBF_slope:     CMS_bbwwsl_Clos_slope_mu_boosted_VBF
fake_nc_e_inc_other_nom:         CMS_bbwwsl_Clos_nom_e_inc_other
fake_nc_e_inc_other_slope:       CMS_bbwwsl_Clos_slope_e_inc_other
fake_nc_m_inc_other_nom:         CMS_bbwwsl_Clos_nom_mu_inc_other
fake_nc_m_inc_other_slope:       CMS_bbwwsl_Clos_slope_mu_inc_other
fake_nc_e_res_toph_nom:          CMS_bbwwsl_Clos_nom_e_res_toph
fake_nc_e_res_toph_slope:        CMS_bbwwsl_Clos_slope_e_res_toph
fake_nc_m_res_toph_nom:          CMS_bbwwsl_Clos_nom_mu_res_toph
fake_nc_m_res_toph_slope:        CMS_bbwwsl_Clos_slope_mu_res_toph
fake_nc_e_boosted_toph_nom:      CMS_bbwwsl_Clos_nom_e_boosted_toph
fake_nc_e_boosted_toph_slope:    CMS_bbwwsl_Clos_slope_e_boosted_toph
fake_nc_m_boosted_toph_nom:      CMS_bbwwsl_Clos_nom_mu_boosted_toph
fake_nc_m_boosted_toph_slope:    CMS_bbwwsl_Clos_slope_mu_boosted_toph
