# PDF #
Fact:   discard 
Renorm: discard
Mixed:  discard
Envelope: 
  scale_DY: 
    group: "DY"
  scale_TT: 
    group: "TT"
  scale_VV: 
    group: "VV"
  scale_WJets:
    group: "WJets"
  scale_tHW: 
    group: "tHW"
  scale_tHq: 
    group: "tHq"
  scale_ttH: 
    group: "ttH"
  scale_ttW: 
    group: "ttW"
  scale_ttZ: 
    group: "ttZ"
  scale_ggHH: 
    group: [".*hbbhww.*",".*hbbhtt.*"]

# Theory #
underlying_event:   underlying_event
hdamp:              hdamp
erdOn:              erdOn
GluonMove:          GluonMove
QCDbased:           QCDbased

# PS #
psFSR:  
  ps_fsr_TT:
    group: "TT"
  ps_fsr_HH:
    group: [".*hbbhww.*",".*hbbhtt.*"]
psISR: 
  ps_isr_TT:
    group: "TT"
  ps_isr_HH:
    group: [".*hbbhww.*",".*hbbhtt.*"]

# Basics #
L1PreFiring:        CMS_l1_ecal_prefiring_{era}
pileup:             CMS_pileup
ttbarweightsyst:    CMS_top_pT_reweighting

# Btag SF #
btagSF_:            CMS_btag_subjet_{era}
    # HF, LF, cferr1 and cferr2 are correlated across years
btagSF_cferr1:      CMS_btag_cferr1_2016_2017_2018
btagSF_cferr2:      CMS_btag_cferr2_2016_2017_2018
btagSF_hf:          CMS_btag_HF_2016_2017_2018
btagSF_lf:          CMS_btag_LF_2016_2017_2018

    # {hf,lf}stats{1,2} uncorrelated across eras
btagSF_hfstats1:    CMS_btag_hfstats1_{era}
btagSF_hfstats2:    CMS_btag_hfstats2_{era}
btagSF_lfstats1:    CMS_btag_lfstats1_{era}
btagSF_lfstats2:    CMS_btag_lfstats2_{era}

# Trigger SF #
ttH_singleMuon_trigSF:      
    CMS_bbwwsl_TriggerWeight_e_{era}:
        cat: [".*SL.*"]
ttH_singleElectron_trigSF:  
    CMS_bbwwsl_TriggerWeight_m_{era}:
        cat: [".*SL.*"]

ttH_doubleElectron_trigSF:  
    CMS_bbwwdl_TriggerWeight_ee_{era}:
        cat: [".*DL.*"]
ttH_doubleMuon_trigSF:      
    CMS_bbwwdl_TriggerWeight_mm_{era}:
        cat: [".*DL.*"]
ttH_electronMuon_trigSF:    
    CMS_bbwwdl_TriggerWeight_emu_{era}:
        cat: [".*DL.*"]



# Lepton SF #
el_loose:    CMS_eff_e_id_loose_{era}
el_tight:    CMS_eff_e_id_tight_{era}
el_tth:      CMS_eff_e_id_tth_{era}
mu_loose:    CMS_eff_m_id_loose_{era}
mu_tight:    CMS_eff_m_id_tight_{era}
mu_tth:      CMS_eff_m_id_tth_{era}


# FakeRates #
#el_FR_Loose_SL_pt_syst:     
#    CMS_bbwwsl_FakeRate_e_pt_{era}:
#        cat: [".*SL.*"]
#el_FR_Loose_SL_barrel_syst: 
#    CMS_bbwwsl_FakeRate_e_barrel_{era}:
#        cat: [".*SL.*"]
#el_FR_Loose_SL_norm_syst:   
#    CMS_bbwwsl_FakeRate_e_norm_{era}:
#        cat: [".*SL.*"]
#mu_FR_Loose_SL_pt_syst:     
#    CMS_bbwwsl_FakeRate_m_pt_{era}:
#        cat: [".*SL.*"]
#mu_FR_Loose_SL_barrel_syst: 
#    CMS_bbwwsl_FakeRate_m_barrel_{era}:
#        cat: [".*SL.*"]
#mu_FR_Loose_SL_norm_syst:   
#    CMS_bbwwsl_FakeRate_m_norm_{era}:
#        cat: [".*SL.*"]
#
#el_FR_Loose_DL_barrel_syst: 
#    CMS_bbwwdl_FakeRate_e_barrel_{era}:
#        cat: [".*DL.*"]
#el_FR_Loose_DL_norm_syst:   
#    CMS_bbwwdl_FakeRate_e_norm_{era}:
#        cat: [".*DL.*"]
#el_FR_Loose_DL_pt_syst:     
#    CMS_bbwwdl_FakeRate_e_pt_{era}:
#        cat: [".*DL.*"]
#
#
#mu_FR_Loose_DL_barrel_syst: 
#    CMS_bbwwdl_FakeRate_m_barrel_{era}:
#        cat: [".*DL.*"]
#mu_FR_Loose_DL_norm_syst:   
#    CMS_bbwwdl_FakeRate_m_norm_{era}:
#        cat: [".*DL.*"]
#mu_FR_Loose_DL_pt_syst:     
#    CMS_bbwwdl_FakeRate_m_pt_{era}:
#        cat: [".*DL.*"]



muonCorrFR:                 
    CMS_bbwwdl_FakeRate_m_nonclosure_{era}:
        cat: [".*DL.*"]
electronCorrFR:             
    CMS_bbwwdl_FakeRate_e_nonclosure_{era}:
        cat: [".*DL.*"]

  
mu_FR_abseta_0p0_1p2_pt_10p0_15p0:
    CMS_bbwwdl_FakeRate_m_BVVVL_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_0p0_1p2_pt_15p0_20p0:
    CMS_bbwwdl_FakeRate_m_BVVL_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_0p0_1p2_pt_20p0_32p0:
    CMS_bbwwdl_FakeRate_m_BVL_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_0p0_1p2_pt_32p0_45p0:
    CMS_bbwwdl_FakeRate_m_BL_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_0p0_1p2_pt_25p0_45p0:
    CMS_bbwwsl_FakeRate_m_BL_{era}:
        cat: [".*SL.*"]
mu_FR_abseta_0p0_1p2_pt_45p0_65p0:
    CMS_bbwwsl_FakeRate_m_BM_{era}:
        cat: [".*SL.*"]
    CMS_bbwwdl_FakeRate_m_BM_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_0p0_1p2_pt_65p0_100p0:    
    CMS_bbwwsl_FakeRate_m_BH_{era}:
        cat: [".*SL.*"]
    CMS_bbwwdl_FakeRate_m_BH_{era}:
        cat: [".*DL.*"]


mu_FR_abseta_1p2_2p4_pt_10p0_15p0:
    CMS_bbwwdl_FakeRate_m_EVVVL_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_1p2_2p4_pt_15p0_20p0:
    CMS_bbwwdl_FakeRate_m_EVVL_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_1p2_2p4_pt_20p0_32p0:
    CMS_bbwwdl_FakeRate_m_EVL_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_1p2_2p4_pt_32p0_45p0:
    CMS_bbwwdl_FakeRate_m_EL_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_1p2_2p4_pt_25p0_45p0:
    CMS_bbwwsl_FakeRate_m_EL_{era}:
        cat: [".*SL.*"]
mu_FR_abseta_1p2_2p4_pt_45p0_65p0:
    CMS_bbwwsl_FakeRate_m_EM_{era}:
        cat: [".*SL.*"]
    CMS_bbwwdl_FakeRate_m_EM_{era}:
        cat: [".*DL.*"]
mu_FR_abseta_1p2_2p4_pt_65p0_100p0:
    CMS_bbwwsl_FakeRate_m_EH_{era}:
        cat: [".*SL.*"]
    CMS_bbwwdl_FakeRate_m_EM_{era}:
        cat: [".*DL.*"]




el_FR_abseta_0p0_1p479_pt_15p0_25p0:
    CMS_bbwwdl_FakeRate_e_BVVL_{era}:
        cat: [".*DL.*"]
el_FR_abseta_0p0_1p479_pt_25p0_35p0:
    CMS_bbwwdl_FakeRate_e_BVL_{era}:
        cat: [".*DL.*"]
el_FR_abseta_0p0_1p479_pt_35p0_45p0:
    CMS_bbwwdl_FakeRate_e_BL_{era}:
        cat: [".*DL.*"]
el_FR_abseta_0p0_1p479_pt_32p0_45p0:   
    CMS_bbwwsl_FakeRate_e_BL_{era}:
        cat: [".*SL.*"]
el_FR_abseta_0p0_1p479_pt_45p0_65p0: 
    CMS_bbwwsl_FakeRate_e_BM_{era}:
        cat: [".*SL.*"]
    CMS_bbwwdl_FakeRate_e_BM_{era}:
        cat: [".*DL.*"]
el_FR_abseta_0p0_1p479_pt_65p0_100p0:  
    CMS_bbwwsl_FakeRate_e_BH_{era}:
        cat: [".*SL.*"]
    CMS_bbwwdl_FakeRate_e_BH_{era}:
        cat: [".*DL.*"]

el_FR_abseta_1p479_2p5_pt_15p0_25p0:
    CMS_bbwwdl_FakeRate_e_EVVL_{era}:
        cat: [".*DL.*"]
el_FR_abseta_1p479_2p5_pt_25p0_35p0:
    CMS_bbwwdl_FakeRate_e_EVL_{era}:
        cat: [".*DL.*"]
el_FR_abseta_1p479_2p5_pt_35p0_45p0:
    CMS_bbwwdl_FakeRate_e_EL_{era}:
        cat: [".*DL.*"]
el_FR_abseta_1p479_2p5_pt_32p0_45p0:  
    CMS_bbwwsl_FakeRate_e_EL_{era}:
        cat: [".*SL.*"]
el_FR_abseta_1p479_2p5_pt_45p0_65p0: 
    CMS_bbwwsl_FakeRate_e_EM_{era}:
        cat: [".*SL.*"]
    CMS_bbwwdl_FakeRate_e_EM_{era}:
        cat: [".*DL.*"]
el_FR_abseta_1p479_2p5_pt_65p0_100p0:  
    CMS_bbwwsl_FakeRate_e_EH_{era}:
        cat: [".*SL.*"]
    CMS_bbwwdl_FakeRate_e_EH_{era}:
        cat: [".*DL.*"]

# JER
jer:                    CMS_res_j_{era}

# Fatjet mass corrections 
jmr:                    CMS_AK8_JMR
jms:                    CMS_AK8_JMS
    # -> fatjets

# MET jet uncertainties
unclustEn:              CMS_unclusteredEnergy_{era}

# JES 
jesAbsolute:            CMS_scale_j_Abs
jesBBEC1:               CMS_scale_j_BBEC1
jesEC2:                 CMS_scale_j_EC2
jesHF:                  CMS_scale_j_HF
jesRelativeBal:         CMS_scale_j_RelBal
jesFlavorQCD:           CMS_scale_j_FlavQCD
jesHEMIssue:            CMS_HEM_{era}  


jesAbsolute_2016:       CMS_scale_j_Abs_2016
jesBBEC1_2016:          CMS_scale_j_BBEC1_2016
jesEC2_2016:            CMS_scale_j_EC2_2016
jesHF_2016:             CMS_scale_j_HF_2016
jesRelativeSample_2016: CMS_scale_j_RelSample_2016

jesAbsolute_2017:       CMS_scale_j_Abs_2017
jesBBEC1_2017:          CMS_scale_j_BBEC1_2017
jesEC2_2017:            CMS_scale_j_EC2_2017
jesHF_2017:             CMS_scale_j_HF_2017
jesRelativeSample_2017: CMS_scale_j_RelSample_2017

jesAbsolute_2018:       CMS_scale_j_Abs_2018
jesBBEC1_2018:          CMS_scale_j_BBEC1_2018
jesEC2_2018:            CMS_scale_j_EC2_2018
jesHF_2018:             CMS_scale_j_HF_2018
jesRelativeSample_2018: CMS_scale_j_RelSample_2018

# Jet PU ID #
jetpuid_eff:            CMS_eff_j_PUJET_id_{era}
jetpuid_mistag:         CMS_eff_j_PUJET_mistag_{era}

# DY #
dy_boosted_1b:          
    CMS_bbwwdl_DY_boost_{era}:
        cat: [".*DL.*"]
dy_resolved_1b:         
    CMS_bbwwdl_DY_resolved1b_{era}:
        cat: [".*DL.*"]
dy_resolved_2b:         
    CMS_bbwwdl_DY_resolved2b_{era}:
        cat: [".*DL.*"]

dy_inclusive_nonclosure_dy_vvv_shape1 : 
    CMS_bbwwdl_DY_ncc1_inclusive_dy_vvv_{era}:
        cat: [".*DL.*"]
dy_inclusive_nonclosure_dy_vvv_shape2 : 
    CMS_bbwwdl_DY_ncc2_inclusive_dy_vvv_{era}:
        cat: [".*DL.*"]
dy_resolved_nonclosure_other_shape1 : 
    CMS_bbwwdl_DY_ncc1_resolved_other_{era}:
        cat: [".*DL.*"]
dy_resolved_nonclosure_other_shape2 : 
    CMS_bbwwdl_DY_ncc2_resolved_other_{era}:
        cat: [".*DL.*"]
dy_boosted_nonclosure_other_shape1 : 
    CMS_bbwwdl_DY_ncc1_boosted_other:
        cat: [".*DL.*"]
dy_boosted_nonclosure_other_shape2 : 
    CMS_bbwwdl_DY_ncc2_boosted_other:
        cat: [".*DL.*"]

# Fake non closure #
fake_nc_e_res1b_GGF_nom:         CMS_bbwwsl_Clos_nom_e_res1b_GGF_{era}
fake_nc_e_res1b_GGF_slope:       CMS_bbwwsl_Clos_slope_mu_res1b_GGF_{era}
fake_nc_m_res1b_GGF_nom:         CMS_bbwwsl_Clos_nom_mu_res1b_GGF_{era}
fake_nc_m_res1b_GGF_slope:       CMS_bbwwsl_Clos_slope_mu_res1b_GGF_{era}
fake_nc_e_res1b_VBF_nom:         CMS_bbwwsl_Clos_nom_e_res1b_VBF_{era}
fake_nc_e_res1b_VBF_slope:       CMS_bbwwsl_Clos_slope_e_res1b_VBF_{era}
fake_nc_m_res1b_VBF_nom:         CMS_bbwwsl_Clos_nom_mu_res1b_VBF_{era}
fake_nc_m_res1b_VBF_slope:       CMS_bbwwsl_Clos_slope_mu_res1b_VBF_{era}
fake_nc_e_res2b_GGF_nom:         CMS_bbwwsl_Clos_nom_e_res2b_GGF_{era}
fake_nc_e_res2b_GGF_slope:       CMS_bbwwsl_Clos_slope_e_res2b_GGF_{era}
fake_nc_m_res2b_GGF_nom:         CMS_bbwwsl_Clos_nom_mu_res2b_GGF_{era}
fake_nc_m_res2b_GGF_slope:       CMS_bbwwsl_Clos_slope_mu_res2b_GGF_{era}
fake_nc_e_res2b_VBF_nom:         CMS_bbwwsl_Clos_nom_e_res2b_VBF_{era}
fake_nc_e_res2b_VBF_slope:       CMS_bbwwsl_Clos_slope_e_res2b_VBF_{era}
fake_nc_m_res2b_VBF_nom:         CMS_bbwwsl_Clos_nom_mu_res2b_VBF_{era}
fake_nc_m_res2b_VBF_slope:       CMS_bbwwsl_Clos_slope_mu_res2b_VBF_{era}
fake_nc_e_boosted_GGF_nom:       CMS_bbwwsl_Clos_nom_e_boosted_GGF_{era}
fake_nc_e_boosted_GGF_slope:     CMS_bbwwsl_Clos_slope_e_boosted_GGF_{era}
fake_nc_m_boosted_GGF_nom:       CMS_bbwwsl_Clos_nom_mu_boosted_GGF_{era}
fake_nc_m_boosted_GGF_slope:     CMS_bbwwsl_Clos_slope_mu_boosted_GGF_{era}
fake_nc_e_boosted_VBF_nom:       CMS_bbwwsl_Clos_nom_e_boosted_VBF_{era}
fake_nc_e_boosted_VBF_slope:     CMS_bbwwsl_Clos_slope_e_boosted_VBF_{era}
fake_nc_m_boosted_VBF_nom:       CMS_bbwwsl_Clos_nom_mu_boosted_VBF_{era}
fake_nc_m_boosted_VBF_slope:     CMS_bbwwsl_Clos_slope_mu_boosted_VBF_{era}
fake_nc_e_inc_wjets_other_nom:   CMS_bbwwsl_Clos_nom_e_inc_wjets_other_{era}
fake_nc_e_inc_wjets_other_slope: CMS_bbwwsl_Clos_slope_e_inc_wjets_other_{era}
fake_nc_m_inc_wjets_other_nom:   CMS_bbwwsl_Clos_nom_mu_inc_wjets_other_{era}
fake_nc_m_inc_wjets_other_slope: CMS_bbwwsl_Clos_slope_mu_inc_wjets_other_{era}
fake_nc_e_res_toph_nom:          CMS_bbwwsl_Clos_nom_e_res_toph_{era}
fake_nc_e_res_toph_slope:        CMS_bbwwsl_Clos_slope_e_res_toph_{era}
fake_nc_m_res_toph_nom:          CMS_bbwwsl_Clos_nom_mu_res_toph_{era}
fake_nc_m_res_toph_slope:        CMS_bbwwsl_Clos_slope_mu_res_toph_{era}
fake_nc_e_boosted_toph_nom:      CMS_bbwwsl_Clos_nom_e_boosted_toph_{era}
fake_nc_e_boosted_toph_slope:    CMS_bbwwsl_Clos_slope_e_boosted_toph_{era}
fake_nc_m_boosted_toph_nom:      CMS_bbwwsl_Clos_nom_mu_boosted_toph_{era}
fake_nc_m_boosted_toph_slope:    CMS_bbwwsl_Clos_slope_mu_boosted_toph_{era}
