# Signal nodes #
HH_DL_resolved1b_GGF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400GGFnode_DNNOutputvsHME_GGF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400GGFnode_DNNOutputvsHME_GGF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400GGFnode_DNNOutputvsHME_GGF
HH_DL_resolved1b_H:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Hnode_DNNOutput_H
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Hnode_DNNOutput_H
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Hnode_DNNOutput_H

HH_DL_resolved2b_GGF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400GGFnode_DNNOutputvsHME_GGF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400GGFnode_DNNOutputvsHME_GGF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400GGFnode_DNNOutputvsHME_GGF
HH_DL_resolved2b_H:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Hnode_DNNOutput_H
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Hnode_DNNOutput_H
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Hnode_DNNOutput_H

HH_DL_boosted_GGF:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400GGFnode_DNNOutputvsHME_GGF
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400GGFnode_DNNOutputvsHME_GGF
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400GGFnode_DNNOutputvsHME_GGF
HH_DL_boosted_H:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Hnode_DNNOutput_H
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Hnode_DNNOutput_H
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Hnode_DNNOutput_H


# Background nodes #
HH_DL_resolved_DY_VVV:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400DYnode_DNNOutput_DY
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400DYnode_DNNOutput_DY
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400DYnode_DNNOutput_DY
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400DYnode_DNNOutput_DY
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400DYnode_DNNOutput_DY
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400DYnode_DNNOutput_DY
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400VVVnode_DNNOutput_VVV
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400VVVnode_DNNOutput_VVV
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400VVVnode_DNNOutput_VVV
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400VVVnode_DNNOutput_VVV
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400VVVnode_DNNOutput_VVV
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400VVVnode_DNNOutput_VVV

HH_DL_boosted_DY_VVV:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400DYnode_DNNOutput_DY
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400DYnode_DNNOutput_DY
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400DYnode_DNNOutput_DY
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400VVVnode_DNNOutput_VVV
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400VVVnode_DNNOutput_VVV
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400VVVnode_DNNOutput_VVV

HH_DL_inclusive_other:
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTnode_DNNOutput_TT
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTnode_DNNOutput_TT
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTnode_DNNOutput_TT
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTnode_DNNOutput_TT
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTnode_DNNOutput_TT
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTnode_DNNOutput_TT
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400STnode_DNNOutput_ST
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400STnode_DNNOutput_ST
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400STnode_DNNOutput_ST
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400STnode_DNNOutput_ST
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400STnode_DNNOutput_ST
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400STnode_DNNOutput_ST
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTVXnode_DNNOutput_TTVX
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTVXnode_DNNOutput_TTVX
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTVXnode_DNNOutput_TTVX
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTVXnode_DNNOutput_TTVX
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTVXnode_DNNOutput_TTVX
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTVXnode_DNNOutput_TTVX
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Rarenode_DNNOutput_Rare
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Rarenode_DNNOutput_Rare
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Rarenode_DNNOutput_Rare
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Rarenode_DNNOutput_Rare
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Rarenode_DNNOutput_Rare
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Rarenode_DNNOutput_Rare
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTnode_DNNOutput_TT
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTnode_DNNOutput_TT
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTnode_DNNOutput_TT
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400STnode_DNNOutput_ST
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400STnode_DNNOutput_ST
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400STnode_DNNOutput_ST
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTVXnode_DNNOutput_TTVX
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTVXnode_DNNOutput_TTVX
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTVXnode_DNNOutput_TTVX
  - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Rarenode_DNNOutput_Rare
  - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Rarenode_DNNOutput_Rare
  - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Rarenode_DNNOutput_Rare



