module: PlotterHHtobbWWSLbasic.py:PlotterNanoHHtobbWWSL
config: 
  era:
    #- 2016: Yaml/analysis2016_v7.yml
    #- 2017: Yaml/analysis2017_v7.yml
    - 2018: Yaml/analysis2018_v7.yml

args:
  - "--subset=mc,data,VBFLO,GGFNLO,bbww2l,bbww1l,bbtautau"
  - "--analysis=nonres"
  - cat:
      - Resolved1B: "--Resolved1Btag"
      - Resolved2B: "--Resolved2Btag"
      - Boosted:  "--Boosted"
  - "--datadriven=FakeExtrapolation"
  - "--NoSystematics"
 
output: /nfs/scratch/fynu/gsaha/PlotNoSyst2018SL/full{era}NanoV7_TTHIDLoose_Fake_DNNSL01_{cat}/
