module: PlotterHHtobbWWDL.py:PlotterNanoHHtobbWWDL
config: 
  era:
    #- 2016: Yaml/analysis2016_v7.yml
    - 2017: Yaml/analysis2017_v7.yml
    #- 2018: Yaml/analysis2018_v7.yml

args:
  - "--subset=mc,data,bbww2l,bbtautau,graviton,radion"
  - cat:
      #- Resolved1B : "--Resolved1Btag"
      #- Resolved2B : "--Resolved2Btag"
      - Boosted1B  : "--Boosted1Btag"
  - "--datadriven=FakeExtrapolation,DYEstimation"
  - mass:
    - 250: "--mass 250"
    - 260: "--mass 260"
    - 270: "--mass 270"
    - 280 : "--mass 280"
    - 300 : "--mass 300"
    - 320 : "--mass 320"
    - 350 : "--mass 350"
    - 400 : "--mass 400"
    - 450 : "--mass 450"
    - 500 : "--mass 500"
    - 550 : "--mass 550"
    - 600 : "--mass 600"
    - 650 : "--mass 650"
    - 700 : "--mass 700"
    - 750 : "--mass 750"
    - 800 : "--mass 800"
    - 850 : "--mass 850"
    - 900 : "--mass 900"

output: /nfs/scratch/fynu/gsaha/BambooOutputHHtobbWW_Master/full{era}NanoV7_TTHIDLoose_Fake_Resonant_{cat}_syst_M_{mass}