module: SkimmerHHtobbWWHME.py:SkimmerHME

config: 
  era:
#    - 2016: Yaml/analysis2016_v7.yml
    - 2017: Yaml/analysis2017_v7.yml
#    - 2018: Yaml/analysis2018_v7.yml

args:
  - --subset=mc,data,bbww2l,bbtautau,graviton,radion
  - cat:
    - Resolved1B: --Resolved1Btag
    - Resolved2B: --Resolved2Btag
    - Boosted1B:  --Boosted1Btag
  - channel:
    - ElEl: --Channel=ElEl
    - MuMu: --Channel=MuMu
    - ElMu: --Channel=ElMu
  - type:   
#    - "SR" : "" 
#    - "FakeCR": "--FakeCR"
    - "DYCR"  : "--DYCR"
  - --NoSystematics
  - --analysis=res

output: /nfs/scratch/fynu/gsaha/SkimsHME/Skim{era}_{cat}_{channel}_{type}
