module: PlotterHHtobbWWDL.py:PlotterNanoHHtobbWWDL
config: 
  era:
    - 2016: Yaml/analysis2016_v7.yml
    - 2017: Yaml/analysis2017_v7.yml
    - 2018: Yaml/analysis2018_v7.yml

args:
  - "--subset=GGFNLO,bbww2l,bbtautau"
  - "--analysis=nonres"
  - "--Resolved1Btag --Resolved2Btag --Boosted1Btag"
  - BM:
    - SM: "--HHReweighting BenchmarkSM"
 
output: /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full{era}NanoV7_TTHIDLoose_Fake_DNN11_GGFNLO_Benchmark{BM}

