module: PlotterHHtobbWWSLbasic.py:PlotterNanoHHtobbWWSL
config: 
  era:
    #- 2016: Yaml/analysis2016_v7.yml
    #- 2017: Yaml/analysis2017_v7.yml
    - 2018: Yaml/analysis2018_v7.yml

args:
  - "--subset=GGFNLO,bbww1l"
  - "--analysis=nonres"
  - "--Resolved1Btag --Resolved2Btag --Boosted"
  - BM:
    - SM:       "--HHReweighting BenchmarkSM"
    - 1:        "--HHReweighting Benchmark1"
    - 2:        "--HHReweighting Benchmark2"
    - 3:        "--HHReweighting Benchmark3"
    - 4:        "--HHReweighting Benchmark4"
    - 5:        "--HHReweighting Benchmark5"
    - 6:        "--HHReweighting Benchmark6"
    - 7:        "--HHReweighting Benchmark7"
    - 8:        "--HHReweighting Benchmark8"
    - 8a:       "--HHReweighting Benchmark8a"
    - 9:        "--HHReweighting Benchmark9"
    - 10:       "--HHReweighting Benchmark10"
    - 11:       "--HHReweighting Benchmark11"
    - 12:       "--HHReweighting Benchmark12"
#    - cHHH0:    "--HHReweighting BenchmarkcHHH0"
#    - cHHH1:    "--HHReweighting BenchmarkcHHH1"
#    - cHHH2p45: "--HHReweighting BenchmarkcHHH2p45"
#    - cHHH5:    "--HHReweighting BenchmarkcHHH5"
    - cluster1: "--HHReweighting Benchmarkcluster1"
    - cluster2: "--HHReweighting Benchmarkcluster2"
    - cluster3: "--HHReweighting Benchmarkcluster3"
    - cluster4: "--HHReweighting Benchmarkcluster4"
    - cluster5: "--HHReweighting Benchmarkcluster5"
    - cluster6: "--HHReweighting Benchmarkcluster6"
    - cluster7: "--HHReweighting Benchmarkcluster7"
  
output: /nfs/scratch/fynu/gsaha/Sync_Aachen_EFT_Output/full{era}NanoV7_TTHIDLoose_Fake_SL_DNN01_GGFNLO_Benchmark{BM}