module: SignalReweightingHistogram.py:SignalReweightingHistogramNano
config: 
  era:
    - 2016: Yaml/analysis2016_v7.yml
    - 2017: Yaml/analysis2017_v7.yml
    - 2018: Yaml/analysis2018_v7.yml

args:
  - "--subset=bbww1l,bbww2l,bbtautau,GGFLO,GGFNLO"
 
output: /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/SignalHistograms_{era}_v2

