# Signal categories #
HH_e_resolved1b_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12GGF_DNNOutput_GGF
HH_m_resolved1b_GGF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12GGF_DNNOutput_GGF

HH_e_resolved1b_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12VBF_DNNOutput_VBF
HH_m_resolved1b_VBF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12VBF_DNNOutput_VBF

HH_e_resolved2b_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12GGF_DNNOutput_GGF
HH_m_resolved2b_GGF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12GGF_DNNOutput_GGF

HH_e_resolved2b_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12VBF_DNNOutput_VBF
HH_m_resolved2b_VBF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12VBF_DNNOutput_VBF

HH_e_boosted_GGF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12GGF_DNNOutput_GGF
HH_m_boosted_GGF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12GGF_DNNOutput_GGF

HH_e_boosted_VBF:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12VBF_DNNOutput_VBF
HH_m_boosted_VBF:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12VBF_DNNOutput_VBF


# Background categories #
HH_e_inclusive_WJets:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12WJets_DNNOutput_WJets
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12WJets_DNNOutput_WJets
HH_m_inclusive_WJets:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12WJets_DNNOutput_WJets
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12WJets_DNNOutput_WJets

HH_e_inclusive_OtherH:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12H_DNNOutput_H
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12H_DNNOutput_H
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12H_DNNOutput_H
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12Other_DNNOutput_Other
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12Other_DNNOutput_Other
HH_m_inclusive_OtherH:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12H_DNNOutput_H
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12Other_DNNOutput_Other
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12Other_DNNOutput_Other


HH_e_resolved_Top:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12ST_DNNOutput_ST
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12ST_DNNOutput_ST
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12TT_DNNOutput_TT
HH_m_resolved_Top:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12TT_DNNOutput_TT
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved1b12ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedResolvedExclusiveResolved2b12ST_DNNOutput_ST

HH_e_boosted_Top:
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12TT_DNNOutput_TT
  - El_Has1FakeableElWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12ST_DNNOutput_ST
HH_m_boosted_Top:
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12ST_DNNOutput_ST
  - Mu_Has1FakeableMuWithTriggersPtCutsPreMllCutOutZnoTauTightSelectedBoosted12TT_DNNOutput_TT
