HH_DL_resolved1b_GGF:
  - HH_e_resolved1b_GGF
  - HH_m_resolved1b_GGF
HH_DL_resolved1b_VBF:
  - HH_e_resolved1b_VBF
  - HH_m_resolved1b_VBF

HH_DL_resolved2b_GGF:
  - HH_e_resolved2b_GGF
  - HH_m_resolved2b_GGF
    
HH_DL_resolved2b_VBF:
  - HH_e_resolved2b_VBF
  - HH_m_resolved2b_VBF
    
HH_DL_boosted_GGF:
  - HH_e_boosted_GGF
  - HH_m_boosted_GGF
    
HH_DL_boosted_VBF:
  - HH_e_boosted_VBF
  - HH_m_boosted_VBF
    
HH_DL_inclusive_WJets:
  - HH_e_inclusive_WJets
  - HH_m_inclusive_WJets
    
HH_DL_inclusive_OtherH:
  - HH_e_inclusive_OtherH
  - HH_m_inclusive_OtherH
    
HH_DL_resolved_Top:
  - HH_e_resolved_Top
  - HH_m_resolved_Top
    
HH_DL_boosted_Top:
  - HH_e_boosted_Top
  - HH_m_boosted_Top
