  limits:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1 -d {}"
    submit :  
      time: '0-08:00:00'
      mem : 9000
    combine_eras: True
    split_eras: True
    bins:
      - HH_DL_{mass}_resolved1b_GGF
      - HH_DL_{mass}_resolved2b_GGF
      - HH_DL_{mass}_boosted_GGF
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
  limits_res1b:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1 -d {}"
    submit :  
      time: '0-08:00:00'
      mem : 9000
    combine_eras: True
    split_eras: True
    bins:
      - HH_DL_{mass}_resolved1b_GGF
  limits_res2b:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1 -d {}"
    submit :  
      time: '0-08:00:00'
      mem : 9000
    combine_eras: True
    split_eras: True
    bins:
      - HH_DL_{mass}_resolved2b_GGF
  limits_boo:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1 -d {}"
    submit :  
      time: '0-08:00:00'
      mem : 9000
    combine_eras: True
    split_eras: True
    bins:
      - HH_DL_{mass}_boosted_GGF
  limits_bkg:
    mode: limits
    command: "combine -M AsymptoticLimits -t -1 -d {}"
    submit :  
      time: '0-08:00:00'
      mem : 9000
    combine_eras: True
    split_eras: True
    bins:
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other


  gof:
    mode: gof
    command: "combine -M GoodnessOfFit -d {} --algo=saturated --toysFrequentist"
    toys: 500
    toys-per-job: 10
    combine_bins: True
    combine_eras: True
    split_bins: True
    split_eras: True
    plotting:
      n_bins        : 32
      #left_margin   : 200
      #right_margin  : 20
    submit :  
      time: '0-02:00:00'
      mem : 3000
    bins:
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
  pulls:
    mode: pulls_impact
    command: "combine -M MultiDimFit {} --verbose 3 --mass 125.0 --redefineSignalPOIs r --setParameterRanges r=-6000.0,6000.0 --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.1 --cminFallbackAlgo Minuit2,0:0.2 --cminFallbackAlgo Minuit2,0:0.4 --floatOtherPOIs 1 --saveInactivePOI 1 --saveNLL --X-rtd REMOVE_CONSTANT_ZERO_POINT=1 --X-rtd MINIMIZER_freezeDisassociatedParams --X-rtd MINIMIZER_multiMin_hideConstants --X-rtd MINIMIZER_multiMin_maskConstraints --X-rtd MINIMIZER_multiMin_maskChannels=2"
    #command: "combine -M MultiDimFit -d {} --verbose 3 --redefineSignalPOIs r  --setParameterRanges r=-6000.0,6000.0 --keepFailures --robustFit 1 --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic"
    mc_stats: False
    unblind: True
    combine_eras: True
    split_eras: True
    submit :  
      time: '0-01:00:00'
      mem : 3000
    plotting:
      left_margin           : 400
      right_margin          : 20
      label_size            : 18
      parameters_per_page   : 35
      order_by_impact       : False
    bins:
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
  impacts:
    mode: pulls_impact
    command: "combine -M MultiDimFit {} --verbose 3 --mass 125.0 --redefineSignalPOIs r --setParameters r=1.0  --setParameterRanges r=-6000.0,6000.0 --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminDefaultMinimizerTolerance 0.1 --cminFallbackAlgo Minuit2,0:0.2 --cminFallbackAlgo Minuit2,0:0.4 --floatOtherPOIs 1 --saveInactivePOI 1 "
    #command: "combine -M MultiDimFit -d {} --verbose 3 --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-6000.0,6000.0 --keepFailures --robustFit 1 --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic "
        #   --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic --robustHesse true
    mc_stats: False
    combine_eras: True
    split_eras: True
    submit :  
      time: '0-01:00:00'
      mem : 3000
    plotting:
      left_margin           : 400
      right_margin          : 20
      label_size            : 18
      parameters_per_page   : 35
      order_by_impact       : False
    bins:
      - HH_DL_{mass}_resolved1b_GGF
      - HH_DL_{mass}_resolved2b_GGF
      - HH_DL_{mass}_boosted_GGF
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
  prefit:
    mode: prefit 
    command: "combine -M FitDiagnostics {} --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic --keepFailures  --skipSBFit --skipBOnlyFit --ignoreCovWarning -n HHbbWW"
    submit :  
      time: '1-00:00:00'
      mem : 15000
    bins:
      - HH_DL_{mass}_resolved1b_GGF
      - HH_DL_{mass}_resolved2b_GGF
      - HH_DL_{mass}_boosted_GGF
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
    plotting:
        main: !include prefit_DL_res_main.yml
        plots: 
          - name: GGFnode
            header: GGF node
            bins : [HH_DL_{mass}_resolved1b_GGF,HH_DL_{mass}_resolved2b_GGF,HH_DL_{mass}_boosted_GGF]
            labels: ['Resolved 1b','Resolved 2b','Boosted']
            labelpos: [1,11,18]
            unblind: False
          - name: DYnode
            header: DY + VV(V) node
            bins : [HH_DL_{mass}_resolved_DY_VVV,HH_DL_{mass}_boosted_DY_VVV]
            labels: ['Resolved','Boosted']
            labelpos: [1, 5]
            unblind: True
          - name: Othernode
            header: TT + Other BKG node
            bins : [HH_DL_{mass}_resolved_other,HH_DL_{mass}_boosted_other]
            labels: ['Resolved','Boosted']
            labelpos: [1, 5]
            unblind: True
  postfit_b:
    mode: postfit_b
    command: "combine -M FitDiagnostics {} --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic --keepFailures  --skipSBFit --ignoreCovWarning -n HHbbWW"
    submit :  
      time: '1-00:00:00'
      mem : 15000
    bins:
      - HH_DL_{mass}_inclusive_DY_VVV
      - HH_DL_{mass}_resolved_other
      - HH_DL_{mass}_boosted_other
    plotting:
        main: !include postfit_DL_res_main.yml
        plots: 
          - name: DYnode
            header: DY + VV(V) node
            bins : [HH_DL_{mass}_resolved_DY_VVV,HH_DL_{mass}_boosted_DY_VVV]
            labels: ['Resolved','Boosted']
            labelpos: [1, 5]
            unblind: True
          - name: Othernode
            header: TT + Other BKG node
            bins : [HH_DL_{mass}_resolved_other,HH_DL_{mass}_boosted_other]
            labels: ['Resolved','Boosted']
            labelpos: [1, 5]
            unblind: True

#  postfit_s:
#    mode: postfit_s
#    command: "combine -M FitDiagnostics {} --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic --keepFailures  --skipBOnlyFit --ignoreCovWarning -n HHbbWW"
#    submit :  
#      time: '1-00:00:00'
#      mem : 15000
#    bins:
#      - HH_DL_resolved1b_GGF
#      - HH_DL_{mass}_resolved2b_GGF
#      - HH_DL_{mass}_boosted_GGF
#      - HH_DL_{mass}_resolved_DY_VVV
#      - HH_DL_{mass}_boosted_DY_VVV
#      - HH_DL_{mass}_resolved_other
#      - HH_DL_{mass}_boosted_other
#    plotting:
#        main: !include postfit_main.yml
#        plots: 
#          - name: GGFnode
#            header: GGF node
#            bins : [HH_DL_resolved1b_GGF,HH_DL_resolved2b_GGF,HH_DL_boosted_GGF]
#            labels: ['Resolved 1b','Resolved 2b','Boosted']
#            labelpos: [0.5, 8.5, 17]
#            unblind: False
#          - name: DYnode
#            header: DY + VV(V) node
#            bins : [HH_DL_resolved_DY_VVV,HH_DL_boosted_DY_VVV]
#            labels: ['Resolved','Boosted']
#            labelpos: [2, 10]
#            unblind: True
#          - name: Othernode
#            header: TT + Other BKG node
#            bins : [HH_DL_resolved_other,HH_DL_boosted_other]
#            labels: ['Resolved','Boosted']
#            labelpos: [2, 8]
#            unblind: True


