path: 
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved1B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved2B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Boosted1B/
use_syst: True

yamlName: plots_DYEstimation_FakeExtrapolation.yml

produce_plots: True

era: 2016

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99


shapeSyst : !include shape_systematics.yml
normSyst  : !include norm_datadriven_systematics.yml

rebin: !include type2_rebin_nonresonant.yml
  
DYnonclosure:
  path : config/fit_results.json
  hist:
    HH_resolved_DY_VVV : 
      entry: HH_resolved_DY_VVV_2016
      name: dy_resolved_nonclosure_dy_vvv
    HH_boosted_DY_VVV : 
      entry: HH_boosted_DY_VVV
      name: dy_boosted_nonclosure_dy_vvv
    HH_inclusive_other: 
      entry: HH_inclusive_other_2016
      name: dy_nonclosure_other
  group: DY


hist_conv: !include type2_cat_nonresonant.yml

  
groups:
  - !include groups_DL_bkg_2016.yml
  - !include groups_DY_datadriven_2016.yml
  - !include groups_data_2016.yml
  - !include groups_DL_nonres.yml

