path: /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_LowMass_DYEstimation_PseudoData_allmass/
use_syst: False

yamlName: plots_pseudodata.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99


hist_conv: !include resonant_cat_allmass.yml

groups:
  - !include groups_DL_bkg_2018.yml
  - !include groups_DL_PseudoData_2018.yml
  - !include groups_DY_datadriven_closure.yml

