path: 
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Boosted
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Resolved1B
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Resolved2B

use_syst: False

yamlName: plots_FakeExtrapolation.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

#combineConfigs: !include combine_Res.yml

normSyst  : 
  - !include norm_lumi.yml
  - !include norm_BR.yml
  - !include norm_QCDscale.yml
  - !include norm_alpha_s.yml
  - !include norm_pdf.yml
  - !include norm_misc.yml
  - !include norm_process.yml
  # Footer #
  - footer:
      - "nuisance edit rename TT * ps_fsr ps_fsr_TT"
      - "nuisance edit rename DY * ps_fsr ps_fsr_DY"
      - "nuisance edit rename TT * ps_isr ps_isr_TT"
      - "nuisance edit rename DY * ps_isr ps_isr_DY"


shapeSyst  : !include shape_systematics.yml


rebin: !include rebin_SL_nonresonant.yml


hist_conv: !include cat_SL_nonresonant.yml
  
groups:
  - !include groups_SL_bkg_2018.yml
  - !include groups_Fakes_2018.yml
  - !include groups_data_2018.yml
  - !include groups_SL_signal_nonres.yml

