path: 
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Boosted
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Resolved1B
- /nfs/scratch/fynu/gsaha/Sync_Aachen/PlotOutWithFullSyst2018_Resolved2B

outputDir: datacards/datacard_fit_NonResonant_SL_DNN001_2018

use_syst: True

yamlName: plots_FakeExtrapolation.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

#combineConfigs: !include combine_Res.yml

normSyst  : 
  - !include norm_lumi.yml
  - !include norm_BR.yml
  - !include norm_QCDscale.yml
  - !include norm_alpha_s.yml
  - !include norm_pdf.yml
  - !include norm_misc.yml
  - !include norm_SL_nonres_process.yml
  # Footer #
  - footer:
      - "nuisance edit rename TT    * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
      - "nuisance edit rename ST    * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_ST"
      - "nuisance edit rename WJets * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_WJets"
      - "nuisance edit rename TT    * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_TT"
      - "nuisance edit rename ST    * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_ST"


shapeSyst  : !include shape_SL_systematics.yml


rebin: !include rebin_SL_nonresonant.yml


hist_conv: !include cat_SL_nonresonant.yml
  
groups:
  - !include groups_SL_bkg_2018.yml
  - !include groups_Fakes_2018.yml
  - !include groups_data_2018.yml
  - !include groups_SL_signal_nonres.yml

