path: /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_v4_M_400/
use_syst: True

textfiles: datacard_M_400.txt

combineCmd: "combine -M AsymptoticLimits -t -1 -d {}"

yamlName: plots_FakeExtrapolation.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

normSyst  : !include norm_mc_systematics.yml

quantiles : &quant [0., 0.2, 0.4, 0.6, 0.8 ,1.]
backgrounds : &back [TT,ST,DY,WJets,VV,VVV,Other_bbWW,ggH_hbb,ggH_hgg,ggH_hmm,ggH_htt,ggH_hww,ggH_hzz,qqH_hbb,qqH_hgg,qqH_hmm,qqH_htt,qqH_hww,qqH_hzz,ttH_hbb,ttH_hww,WH_hbb,ZH_hbb,ZH_htt,ZH_hww,tHq_hww,tHW_hww,VH_hww]
thresh: &thresh [1.e-05, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100.0, 121.0, 144.0, 169.0, 196.0, 225.0, 256.0, 289.0, 324.0, 361.0, 400.0, 441.0, 484.0, 529.0, 576.0, 625.0, 676.0, 729.0, 784.0, 841.0, 900.0, 961.0, 1024.0, 1089.0, 1156.0, 1225.0, 1296.0, 1369.0, 1444.0, 1521.0, 1600.0, 1681.0, 1764.0, 1849.0, 1936.0, 2025.0, 2116.0, 2209.0, 2304.0, 2401.0]

rebin:
  HH_resolved1b_GGF:
    method: threshold
    params: 
      - *thresh
      - [ggHH_M_400_hbbhwwdl,ggHH_M_400_hbbhtt]
      - [TT,ST,DY]
      - 20
      - 0.1
  HH_resolved2b_GGF:
    method: threshold
    params:
      - *thresh
      - [ggHH_M_400_hbbhwwdl,ggHH_M_400_hbbhtt]
      - [TT,ST,DY]
      - 20
      - 0.1
  HH_boosted_GGF:
    method: threshold
    params:
      - *thresh
      - [ggHH_M_400_hbbhwwdl,ggHH_M_400_hbbhtt]
      - [TT,ST,DY]
      - 20
      - 0.2

  HH_resolved2b_H:
    method : quantile
    params : [*quant, *back]
  HH_resolved1b_H:
    method : quantile
    params : [*quant, *back]
  HH_boosted_H:
    method : quantile
    params : [[0.,0.33,0.66,1.], *back]
  
  HH_resolved_DY_VVV:
    method : quantile
    params : [*quant, *back]
  HH_boosted_DY_VVV:
    method : quantile
    params : [*quant, *back]
  HH_inclusive_other:
    method : quantile
    params : [*quant, *back]

  
#DYnonclosure:
#  path : config/fit_results.json
#  hist:
#    HH_resolved_DY_VVV : 
#      entry: HH_resolved_DY_VVV_2018
#      name: dy_resolved_nonclosure_dy_vvv
#    HH_boosted_DY_VVV : 
#      entry: HH_boosted_DY_VVV
#      name: dy_boosted_nonclosure_dy_vvv
#    HH_inclusive_other: 
#      entry: HH_inclusive_other_2018
#      name: dy_nonclosure_other
#  group: DY





hist_conv: 
  # Signal s #
  HH_resolved1b_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400GGF_DNNOutput_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400GGF_DNNOutput_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400GGF_DNNOutput_GGF
  HH_resolved1b_H:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400H_DNNOutput_H
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400H_DNNOutput_H
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400H_DNNOutput_H
  
  HH_resolved2b_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400GGF_DNNOutput_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400GGF_DNNOutput_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400GGF_DNNOutput_GGF
  HH_resolved2b_H:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400H_DNNOutput_H
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400H_DNNOutput_H
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400H_DNNOutput_H
  
  HH_boosted_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400GGF_DNNOutput_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400GGF_DNNOutput_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400GGF_DNNOutput_GGF
  HH_boosted_H:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400H_DNNOutput_H
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400H_DNNOutput_H
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400H_DNNOutput_H
  
  
  # Background s #
  HH_resolved_DY_VVV:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400DY_DNNOutput_DY
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400DY_DNNOutput_DY
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400DY_DNNOutput_DY
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400DY_DNNOutput_DY
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400DY_DNNOutput_DY
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400DY_DNNOutput_DY
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400VVV_DNNOutput_VVV
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400VVV_DNNOutput_VVV
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400VVV_DNNOutput_VVV
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400VVV_DNNOutput_VVV
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400VVV_DNNOutput_VVV
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400VVV_DNNOutput_VVV
  
  HH_boosted_DY_VVV:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400DY_DNNOutput_DY
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400DY_DNNOutput_DY
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400DY_DNNOutput_DY
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400VVV_DNNOutput_VVV
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400VVV_DNNOutput_VVV
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400VVV_DNNOutput_VVV
  
  HH_inclusive_other:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TT_DNNOutput_TT
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TT_DNNOutput_TT
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TT_DNNOutput_TT
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TT_DNNOutput_TT
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TT_DNNOutput_TT
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TT_DNNOutput_TT
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400ST_DNNOutput_ST
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400ST_DNNOutput_ST
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400ST_DNNOutput_ST
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400ST_DNNOutput_ST
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400ST_DNNOutput_ST
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400ST_DNNOutput_ST
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTVX_DNNOutput_TTVX
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTVX_DNNOutput_TTVX
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400TTVX_DNNOutput_TTVX
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTVX_DNNOutput_TTVX
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTVX_DNNOutput_TTVX
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400TTVX_DNNOutput_TTVX
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Rare_DNNOutput_Rare
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Rare_DNNOutput_Rare
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM400Rare_DNNOutput_Rare
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Rare_DNNOutput_Rare
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Rare_DNNOutput_Rare
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM400Rare_DNNOutput_Rare
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TT_DNNOutput_TT
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TT_DNNOutput_TT
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TT_DNNOutput_TT
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400ST_DNNOutput_ST
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400ST_DNNOutput_ST
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400ST_DNNOutput_ST
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTVX_DNNOutput_TTVX
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTVX_DNNOutput_TTVX
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400TTVX_DNNOutput_TTVX
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Rare_DNNOutput_Rare
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Rare_DNNOutput_Rare
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM400Rare_DNNOutput_Rare
  


  
groups:
  - !include groups_DL_bkg_2018.yml
  #- !include groups_DY_datadriven_2018.yml
  - !include groups_DY_MC.yml
  - !include groups_data_2018.yml
  - ggHH_M_400_hbbhwwdl:
      type: signal
      legend: Graviton#rightarrowHH#rightarrowbbWW (M = 400 GeV)
      scale: 100
      order: 14
      line-color: '#288a24'
      line-type: 1
      files:
        - GluGluToBulkGravitonToHHTo2B2VTo2L2Nu_M-400.root
    ggHH_M_400_hbbhtt:
      type: signal
      legend: Graviton#rightarrowHH#rightarrowbb#tau#tau (M = 400 GeV)
      scale: 100
      order: 14
      line-color: '#288a24'
      line-type: 2
      files:
        - GluGluToBulkGravitonToHHTo2B2Tau_M-400.root

