path: 
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved1B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved2B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2017NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Boosted1B/
use_syst: True

yamlName: plots_DYEstimation_FakeExtrapolation.yml

produce_plots: True

era: 2017

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99

    
shapeSyst : !include shape_systematics.yml
normSyst  : !include norm_datadriven_systematics.yml

rebin: !include type2_rebin.yml


hist_conv: !include type2_cat_nonresonant.yml


groups:
  - !include groups_DL_bkg_2017.yml
  - !include groups_DY_datadriven_2017.yml
  - !include groups_data_2017.yml
  - !include groups_DL_nonres.yml
