path: /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_DYEstimation_Resonant_v1_M_500_v2/
use_syst: False


yamlName: plots_FakeExtrapolation.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3




hist_conv: 
  # Signals #
  HH_resolved1b_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM500GGF_DNNOutputvsHME_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM500GGF_DNNOutputvsHME_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM500GGF_DNNOutputvsHME_GGF
  HH_resolved2b_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM500GGF_DNNOutputvsHME_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM500GGF_DNNOutputvsHME_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM500GGF_DNNOutputvsHME_GGF
  HH_boosted_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM500GGF_DNNOutputvsHME_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM500GGF_DNNOutputvsHME_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM500GGF_DNNOutputvsHME_GGF
  
groups:
  - !include groups_DL_bkg_2018.yml
  #- !include groups_DY_datadriven_2018.yml
  - !include groups_DY_MC.yml
  - !include groups_data_2018.yml
  - ggHH_M_500_hbbhwwdl:
      type: signal
      legend: Graviton#rightarrowHH#rightarrowbbWW (M = 500 GeV)
      scale: 100
      order: 14
      line-color: '#288a24'
      line-type: 1
      files:
        - GluGluToBulkGravitonToHHTo2B2VTo2L2Nu_M-500.root
    ggHH_M_500_hbbhtt:
      type: signal
      legend: Graviton#rightarrowHH#rightarrow#tau#tau (M = 500 GeV)
      scale: 100
      order: 14
      line-color: '#288a24'
      line-type: 2
      files:
        - GluGluToBulkGravitonToHHTo2B2Tau_M-500.root

