path: /nfs/scratch/fynu/fbury/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_LowMass_DYEstimation_allmass/
use_syst: False

yamlName: plots_DYEstimation.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

hist_conv: !include resonant_cat_allmass.yml


groups:
  - !include groups_DL_bkg_2018.yml
  - !include groups_data_2018.yml
  - !include groups_DY_datadriven_2018.yml

