path: 
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved1B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved2B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2016NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Boosted1B/

use_syst: True

combineCmds: 
  - mode: limits
    command: "combine -M AsymptoticLimits -t -1 -d {}"
    bins:
      - HH_resolved1b_GGF
      - HH_resolved2b_GGF
      - HH_boosted_GGF
      - HH_resolved1b_VBF
      - HH_resolved2b_VBF
      - HH_boosted_VBF
      - HH_resolved1b_H
      - HH_resolved2b_H
      - HH_boosted_H
      - HH_resolved_DY_VVV
      - HH_boosted_DY_VVV
      - HH_resolved_other
      - HH_boosted_other
  - mode: prefit 
    command: "combine -M FitDiagnostics {} --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic --keepFailures  --skipSBFit --skipBFit --ignoreCovWarning -n HHbbWW"
    bins:
      - HH_resolved1b_GGF
      - HH_resolved2b_GGF
      - HH_boosted_GGF
      - HH_resolved1b_VBF
      - HH_resolved2b_VBF
      - HH_boosted_VBF
      - HH_resolved1b_H
      - HH_resolved2b_H
      - HH_boosted_H
      - HH_resolved_DY_VVV
      - HH_boosted_DY_VVV
      - HH_resolved_other
      - HH_boosted_other
    split: True
    plotting:
        main: !include prefit_main.yml
        plots: 
          - name: GGFnode
            header: GGF node
            bins : [HH_resolved1b_GGF,HH_resolved2b_GGF,HH_boosted_GGF]
            labels: ['Resolved 1b','Resolved 2b','Boosted']
            labelpos: [0.5, 8.5, 17]
            unblind: False
          - name: VBFnode
            header: VBF node
            bins : [HH_resolved1b_VBF,HH_resolved2b_VBF,HH_boosted_VBF]
            labels: ['Resolved 1b','Resolved 2b','Boosted']
            labelpos: [0.5, 8.5, 17]
            unblind: False
          - name: Hnode
            header: single H node
            bins : [HH_resolved1b_H,HH_resolved2b_H,HH_boosted_H]
            labels: ['Resolved 1b','Resolved 2b','Boosted']
            labelpos: [0.5, 8.5, 17]
            unblind: True
          - name: DYnode
            header: DY + VV(V) node
            bins : [HH_resolved_DY_VVV,HH_boosted_DY_VVV]
            labels: ['Resolved','Boosted']
            labelpos: [2, 10]
            unblind: True
          - name: Othernode
            header: TT + Other BKG node
            bins : [HH_resolved_other,HH_boosted_other]
            labels: ['Resolved','Boosted']
            labelpos: [2, 8]
            unblind: True
  - mode: postfit_b
    command: "combine -M FitDiagnostics {} --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic --keepFailures  --skipSBFit --ignoreCovWarning -n HHbbWW"
    bins:
      - HH_resolved1b_H
      - HH_resolved2b_H
      - HH_boosted_H
      - HH_resolved_DY_VVV
      - HH_boosted_DY_VVV
      - HH_resolved_other
      - HH_boosted_other
    plotting:
        main: !include postfit_main.yml
        plots: 
          - name: Hnode
            header: single H node
            bins : [HH_resolved1b_H,HH_resolved2b_H,HH_boosted_H]
            labels: ['Resolved 1b','Resolved 2b','Boosted']
            labelpos: [0.5, 8.5, 17]
            unblind: True
          - name: DYnode
            header: DY + VV(V) node
            bins : [HH_resolved_DY_VVV,HH_boosted_DY_VVV]
            labels: ['Resolved','Boosted']
            labelpos: [2, 10]
            unblind: True
          - name: Othernode
            header: TT + Other BKG node
            bins : [HH_resolved_other,HH_boosted_other]
            labels: ['Resolved','Boosted']
            labelpos: [2, 8]
            unblind: True

  - mode: postfit_s
    command: "combine -M FitDiagnostics {} --verbose 3 --mass 125  --redefineSignalPOIs r --setParameters r=1.0 --setParameterRanges r=-1000,1000 --saveShapes --saveWithUncertainties --saveNormalizations --saveWorkspace --saveToys --saveNLL --saveOverallShapes --cminDefaultMinimizerType Minuit2 --cminDefaultMinimizerStrategy 0 --cminFallbackAlgo Minuit2,0:1.0 --X-rtd MINIMIZER_no_analytic --keepFailures  --skipBFit --ignoreCovWarning -n HHbbWW"
    bins:
      - HH_resolved1b_GGF
      - HH_resolved2b_GGF
      - HH_boosted_GGF
      - HH_resolved1b_VBF
      - HH_resolved2b_VBF
      - HH_boosted_VBF
      - HH_resolved1b_H
      - HH_resolved2b_H
      - HH_boosted_H
      - HH_resolved_DY_VVV
      - HH_boosted_DY_VVV
      - HH_resolved_other
      - HH_boosted_other
    plotting:
        main: !include postfit_main.yml
        plots: 
          - name: GGFnode
            header: GGF node
            bins : [HH_resolved1b_GGF,HH_resolved2b_GGF,HH_boosted_GGF]
            labels: ['Resolved 1b','Resolved 2b','Boosted']
            labelpos: [0.5, 8.5, 17]
            unblind: False
          - name: VBFnode
            header: VBF node
            bins : [HH_resolved1b_VBF,HH_resolved2b_VBF,HH_boosted_VBF]
            labels: ['Resolved 1b','Resolved 2b','Boosted']
            labelpos: [0.5, 8.5, 17]
            unblind: False
          - name: Hnode
            header: single H node
            bins : [HH_resolved1b_H,HH_resolved2b_H,HH_boosted_H]
            labels: ['Resolved 1b','Resolved 2b','Boosted']
            labelpos: [0.5, 8.5, 17]
            unblind: True
          - name: DYnode
            header: DY + VV(V) node
            bins : [HH_resolved_DY_VVV,HH_boosted_DY_VVV]
            labels: ['Resolved','Boosted']
            labelpos: [2, 10]
            unblind: True
          - name: Othernode
            header: TT + Other BKG node
            bins : [HH_resolved_other,HH_boosted_other]
            labels: ['Resolved','Boosted']
            labelpos: [2, 8]
            unblind: True



yamlName: plots_DYEstimation_FakeExtrapolation.yml

produce_plots: True

era: 2016

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99

shapeSyst : !include shape_systematics.yml
normSyst  : !include norm_datadriven_systematics.yml

rebin: !include type2_rebin_nonresonant.yml

DYnonclosure:
  path : config/fit_results.json
  hist:
    HH_resolved_DY_VVV : 
      entry: HH_resolved_DY_VVV_2016
      name: dy_resolved_nonclosure_dy_vvv
    HH_boosted_DY_VVV : 
      entry: HH_boosted_DY_VVV
      name: dy_boosted_nonclosure_dy_vvv
    HH_resolved_other: 
      entry: HH_inclusive_other_2016
      name: dy_resolved_nonclosure_other
    HH_boosted_other: 
      entry: HH_inclusive_other_2016
      name: dy_boosted_nonclosure_other
  group: DY

hist_conv: !include type2_cat_nonresonant.yml

  
groups: 
  - !include groups_DL_bkg_2016.yml
  - !include groups_DY_datadriven_2016.yml
  - !include groups_data_2016.yml
  - !include groups_Fakes_2016.yml
  #- !include groups_DL_BM_qqHH.yml
  - ggHH_BM_SM_hbbhwwdl:
      type: signal
      legend: HH#rightarrowbb2l2#nu
      order: 14
      line-color: '#288a24'
      line-type: 1
      files:
        - GluGluToHHTo2B2VTo2L2Nu_node_cHHH1.root
  
    ggHH_BM_SM_hbbhtt:
      type: signal
      legend: HH#rightarrowbb#tau#tau
      order: 14
      line-color: '#288a24'
      line-type: 1
      files:
        - GluGluToHHTo2B2Tau_node_cHHH1.root



