path: 
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved1B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Resolved2B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_DNN11_DYEstimation_HT_Boosted1B/
  - /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_DNN11_GGFLO_Benchmark8a/
use_syst: True

textfiles: datacard_8a_{}.txt

yamlName: 
  - plots_DYEstimation_FakeExtrapolation.yml
  - plots.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.8
  - 0.6
  - 0.99
  - 0.99


shapeSyst : !include shape_systematics.yml
normSyst  : !include norm_datadriven_systematics.yml

rebin: !include type2_rebin_nonresonant.yml
  
DYnonclosure:
  path : config/fit_results.json
  hist:
    HH_resolved_DY_VVV : 
      entry: HH_resolved_DY_VVV_2018
      name: dy_resolved_nonclosure_dy_vvv
    HH_boosted_DY_VVV : 
      entry: HH_boosted_DY_VVV
      name: dy_boosted_nonclosure_dy_vvv
    HH_inclusive_other: 
      entry: HH_inclusive_other_2018
      name: dy_nonclosure_other
  group: DY


hist_conv: !include type2_cat_nonresonant.yml

  
groups: 
  - !include groups_DL_bkg_2018.yml
  - !include groups_DY_datadriven_2018.yml
  - !include groups_data_2018.yml
  - !include groups_DL_BM_qqHH.yml
  - ggHH_BM_8a_hbbhwwdl:
      type: signal
      legend: HH bbWW GGF (BM 8a) 
      order: 14
      line-color: '#288a24'
      line-type: 1
      files:
        - GluGluToHHTo2B2VTo2L2Nu_NLOBenchmark8a.root
  
    ggHH_BM_8a_hbbhtt:
      type: signal
      legend: HH bbWW GGF (BM 8a) 
      order: 14
      line-color: '#288a24'
      line-type: 1
      files:
        - GluGluToHHTo2B2Tau_NLOBenchmark8a.root



