path: 
- /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Boosted1B_HighMass_syst_M_800/
- /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Resolved1B_HighMass_syst_M_800/
- /home/ucl/cp3/fbury/scratch/BambooOutputHHtobbWW/full2018NanoV7_TTHIDLoose_Fake_Resonant_Resolved2B_HighMass_syst_M_800/

use_syst: True

yamlName: plots_DYEstimation_FakeExtrapolation.yml

produce_plots: True

era: 2018

legend:
  position:
  - 0.2
  - 0.7
  - 0.9
  - 0.9
  columns: 3

combineConfigs: !include combine_Res.yml

normSyst  : 
  # Main #
  - !include norm_res_datadriven_systematics.yml
  # Boosted top #
  - CMS_bbwwdl_top_norm_boost:
      hist: 
        - HH_boosted_GGF
        - HH_boosted_H
        - HH_boosted_DY_VVV
        - HH_boosted_other
      proc: 
        - ST
        - TT
      val: 1.2
  # Fakes #
  - CMS_bbwwdl_fakes_norm_boosted_DY_VVV_2018:
      hist: HH_boosted_DY_VVV
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_resolved_DY_VVV_2018:
      hist: HH_resolved_DY_VVV
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_boosted_other_2018:
      hist: HH_boosted_other
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_resolved_other_2018:
      hist: HH_resolved_other
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_boosted_H_2018:
      hist: HH_boosted_H
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_resolved1b_H_2018:
      hist: HH_resolved1b_H
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_resolved2b_H_2018:
      hist: HH_resolved2b_H
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_boosted_GGF_2018:
      hist: HH_boosted_GGF
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_resolved1b_GGF_2018:
      hist: HH_resolved1b_GGF
      proc: Fakes
      val: 1.3
    CMS_bbwwdl_fakes_norm_resolved2b_GGF_2018:
      hist: HH_resolved2b_GGF
      proc: Fakes
      val: 1.3
  # DY #
  - CMS_bbwwdl_DYEstimation_nonclosure_800_boosted_GGF:
      hist: HH_800_boosted_GGF
      proc: DY
      val:
      - 0.858
      - 1.142
    CMS_bbwwdl_DYEstimation_nonclosure_800_boosted_H:
      hist: HH_800_boosted_H
      proc: DY
      val:
      - 0.774
      - 1.226
    CMS_bbwwdl_DYEstimation_nonclosure_800_resolved1b_GGF_2018:
      era: '2018'
      hist: HH_800_resolved1b_GGF
      proc: DY
      val:
      - 0.422
      - 1.578
    CMS_bbwwdl_DYEstimation_nonclosure_800_resolved1b_H_2018:
      era: '2018'
      hist: HH_800_resolved1b_H
      proc: DY
      val:
      - 0.954
      - 1.046
    CMS_bbwwdl_DYEstimation_nonclosure_800_resolved2b_GGF_2018:
      era: '2018'
      hist: HH_800_resolved2b_GGF
      proc: DY
      val:
      - 0.715
      - 1.285
    CMS_bbwwdl_DYEstimation_nonclosure_800_resolved2b_H_2018:
      era: '2018'
      hist: HH_800_resolved2b_H
      proc: DY
      val:
      - 0.908
      - 1.092

  # Footer #
  - footer:
      - "nuisance edit rename TT * ps_fsr ps_fsr_TT"
      - "nuisance edit rename DY * ps_fsr ps_fsr_DY"
      - "nuisance edit rename TT * ps_isr ps_isr_TT"
      - "nuisance edit rename DY * ps_isr ps_isr_DY"


shapeSyst  : !include shape_systematics.yml


quantiles : 
  - &quant5 [0., 0.2, 0.4, 0.6, 0.8 ,1.]
  - &quant3 [0., 0.33, 0.66, 1.]
backgrounds : &back [TT,ST,DY,WJets,VV,VVV,Other_bbWW,ggH_hbb,ggH_hgg,ggH_hmm,ggH_htt,ggH_hww,ggH_hzz,qqH_hbb,qqH_hgg,qqH_hmm,qqH_htt,qqH_hww,qqH_hzz,ttH_hbb,ttH_hww,WH_hbb,ZH_hbb,ZH_htt,ZH_hww,tHq_hww,tHW_hww,VH_hww]
thresh: &thresh [1.e-05, 1.0, 4.0, 9.0, 16.0, 25.0, 36.0, 49.0, 64.0, 81.0, 100., 121., 144., 169., 196., 225.]

rebin:
  HH_resolved1b_GGF:
    method: threshold 
    params: 
      - *thresh
      - [TT,ST,DY]
      - 10
      - 0.05
      - [ggHH_M_800_hbbhwwdl,ggHH_M_800_hbbhtt]
  HH_resolved2b_GGF:
    method: threshold 
    params: 
      - *thresh
      - [TT,ST,DY]
      - 10
      - 0.1
      - [ggHH_M_800_hbbhwwdl,ggHH_M_800_hbbhtt]
  HH_boosted_GGF:
    method: threshold 
    params: 
      - *thresh
      - [TT,ST,DY]
      - 10
      - 0.2
      - [ggHH_M_800_hbbhwwdl,ggHH_M_800_hbbhtt]

  HH_resolved2b_H:
    method : quantile
    params : [*quant5, *back]
  HH_resolved1b_H:
    method : quantile
    params : [*quant5, *back]
  HH_boosted_H:
    method : quantile
    params : [*quant3, *back]
  
  HH_resolved_DY_VVV:
    method : quantile
    params : [*quant5, *back]
  HH_boosted_DY_VVV:
    method : quantile
    params : [*quant3, *back]

  HH_resolved_other:
    method : quantile
    params : [*quant5, *back]
  HH_boosted_other:
    method : quantile
    params : [*quant3, *back]

  
DYnonclosure:
  path : CompareDY/fit_results_ResHighMass.json
  hist:
    HH_resolved_DY_VVV : 
      entry: HH_800_resolved_DY_VVV_2018
      name: dy_resolved_nonclosure_dy_vvv
    HH_boosted_DY_VVV : 
      entry: HH_800_boosted_DY_VVV
      name: dy_boosted_nonclosure_dy_vvv
    HH_resolved_other: 
      entry: HH_800_resolved_other_2018
      name: dy_resolved_nonclosure_other
    HH_boosted_other: 
      entry: HH_800_boosted_other
      name: dy_boosted_nonclosure_other
  group: DY



hist_conv: 
  # Signal #
  HH_resolved1b_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800GGF_DNNOutput_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800GGF_DNNOutput_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800GGF_DNNOutput_GGF
  HH_resolved1b_H:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800H_DNNOutput_H
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800H_DNNOutput_H
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800H_DNNOutput_H
  
  HH_resolved2b_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800GGF_DNNOutput_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800GGF_DNNOutput_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800GGF_DNNOutput_GGF
  HH_resolved2b_H:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800H_DNNOutput_H
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800H_DNNOutput_H
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800H_DNNOutput_H
  
  HH_boosted_GGF:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800GGF_DNNOutput_GGF
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800GGF_DNNOutput_GGF
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800GGF_DNNOutput_GGF
  HH_boosted_H:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800H_DNNOutput_H
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800H_DNNOutput_H
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800H_DNNOutput_H
  
  
  # Backgrounds #
  HH_resolved_DY_VVV:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800DY_DNNOutput_DY
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800DY_DNNOutput_DY
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800DY_DNNOutput_DY
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800DY_DNNOutput_DY
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800DY_DNNOutput_DY
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800DY_DNNOutput_DY
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800VVV_DNNOutput_VVV
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800VVV_DNNOutput_VVV
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800VVV_DNNOutput_VVV
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800VVV_DNNOutput_VVV
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800VVV_DNNOutput_VVV
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800VVV_DNNOutput_VVV
  
  HH_boosted_DY_VVV:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800DY_DNNOutput_DY
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800DY_DNNOutput_DY
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800DY_DNNOutput_DY
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800VVV_DNNOutput_VVV
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800VVV_DNNOutput_VVV
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800VVV_DNNOutput_VVV
  
  HH_resolved_other:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800TT_DNNOutput_TT
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800TT_DNNOutput_TT
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800TT_DNNOutput_TT
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800TT_DNNOutput_TT
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800TT_DNNOutput_TT
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800TT_DNNOutput_TT
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800ST_DNNOutput_ST
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800ST_DNNOutput_ST
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800ST_DNNOutput_ST
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800ST_DNNOutput_ST
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800ST_DNNOutput_ST
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800ST_DNNOutput_ST
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800TTVX_DNNOutput_TTVX
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800TTVX_DNNOutput_TTVX
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800TTVX_DNNOutput_TTVX
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800TTVX_DNNOutput_TTVX
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800TTVX_DNNOutput_TTVX
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800TTVX_DNNOutput_TTVX
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800Rare_DNNOutput_Rare
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800Rare_DNNOutput_Rare
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedOneBtagM800Rare_DNNOutput_Rare
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800Rare_DNNOutput_Rare
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800Rare_DNNOutput_Rare
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedTwoAk4JetsExclusiveResolvedTwoBtagsM800Rare_DNNOutput_Rare

  HH_boosted_other:
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800TT_DNNOutput_TT
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800TT_DNNOutput_TT
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800TT_DNNOutput_TT
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800ST_DNNOutput_ST
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800ST_DNNOutput_ST
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800ST_DNNOutput_ST
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800TTVX_DNNOutput_TTVX
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800TTVX_DNNOutput_TTVX
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800TTVX_DNNOutput_TTVX
    - ElEl_Has2FakeableElElOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800Rare_DNNOutput_Rare
    - ElMu_Has2FakeableElMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800Rare_DNNOutput_Rare
    - MuMu_Has2FakeableMuMuOSWithTriggersPtCutsPreMllCutOutZTightSelectedOneAk8JetInclusiveBoostedOneBtagM800Rare_DNNOutput_Rare
  

groups:
  - !include groups_DL_bkg_2018.yml
  - !include groups_DY_datadriven_2018.yml
  - !include groups_Fakes_2018.yml
  - !include groups_data_2018.yml
  - ggHH_M_800_hbbhwwdl:
      type: signal
      legend: "Radion 800 GeV #rightarrowHH#rightarrowbbWW [1 pb]"
      scale: 100
      order: 14
      line-color: '#288a24'
      fill-color: '#288a24'
      line-type: 1
      line-width: 2
      fill-type: 3345
      files:
        - GluGluToRadionToHHTo2B2VTo2L2Nu_M-800.root
    ggHH_M_800_hbbhtt:
      type: signal
      legend: "Radion 800 GeV #rightarrowHH#rightarrowbb#tau#tau [1 pb]"
      scale: 100
      order: 14
      line-color: '#c91a26'
      fill-color: '#c91a26'
      line-type: 1
      line-width: 2
      fill-type: 3354
      files:
        - GluGluToRadionToHHTo2B2Tau_M-800.root

