DY:
  fill-color: '#1a83a1'
  legend: Drell-Yan 
  order: 3
  type: mc
  files:
    - DoubleEGamma_2016B0DYEstimation.root
    - DoubleEGamma_2016B1DYEstimation.root
    - DoubleEGamma_2016CDYEstimation.root
    - DoubleEGamma_2016DDYEstimation.root
    - DoubleEGamma_2016EDYEstimation.root
    - DoubleEGamma_2016FDYEstimation.root
    - DoubleEGamma_2016GDYEstimation.root
    - DoubleEGamma_2016H0DYEstimation.root
    - DoubleEGamma_2016H1DYEstimation.root
    - DoubleMuon_2016B0DYEstimation.root
    - DoubleMuon_2016B1DYEstimation.root
    - DoubleMuon_2016CDYEstimation.root
    - DoubleMuon_2016DDYEstimation.root
    - DoubleMuon_2016EDYEstimation.root
    - DoubleMuon_2016FDYEstimation.root
    - DoubleMuon_2016GDYEstimation.root
    - DoubleMuon_2016H0DYEstimation.root
    - DoubleMuon_2016H1DYEstimation.root
    - GluGluHToBBDYEstimation.root
    - GluGluHToGGDYEstimation.root
    - GluGluHToMuMuDYEstimation.root
    - GluGluHToTauTauDYEstimation.root
    - GluGluHToWWTo2L2NuDYEstimation.root
    - GluGluHToWWToLNuQQDYEstimation.root
    - GluGluHToZZTo4LDYEstimation.root
    - HZJ_HToWWDYEstimation.root
    - MuonEG_2016B0DYEstimation.root
    - MuonEG_2016B1DYEstimation.root
    - MuonEG_2016CDYEstimation.root
    - MuonEG_2016DDYEstimation.root
    - MuonEG_2016EDYEstimation.root
    - MuonEG_2016FDYEstimation.root
    - MuonEG_2016GDYEstimation.root
    - MuonEG_2016H0DYEstimation.root
    - MuonEG_2016H1DYEstimation.root
    - SingleElectron_2016B0DYEstimation.root
    - SingleElectron_2016B1DYEstimation.root
    - SingleElectron_2016CDYEstimation.root
    - SingleElectron_2016DDYEstimation.root
    - SingleElectron_2016EDYEstimation.root
    - SingleElectron_2016FDYEstimation.root
    - SingleElectron_2016GDYEstimation.root
    - SingleElectron_2016H0DYEstimation.root
    - SingleElectron_2016H1DYEstimation.root
    - SingleMuon_2016B0DYEstimation.root
    - SingleMuon_2016B1DYEstimation.root
    - SingleMuon_2016CDYEstimation.root
    - SingleMuon_2016DDYEstimation.root
    - SingleMuon_2016EDYEstimation.root
    - SingleMuon_2016FDYEstimation.root
    - SingleMuon_2016GDYEstimation.root
    - SingleMuon_2016H0DYEstimation.root
    - SingleMuon_2016H1DYEstimation.root
    - ST_schannel_4fDYEstimation.root
    - ST_tchannel_antitop_4fDYEstimation.root
    - ST_tchannel_top_4fDYEstimation.root
    - ST_tW_antitop_5fDYEstimation.root
    - ST_tWll_5fDYEstimation.root
    - ST_tW_top_5fDYEstimation.root
    - TGJetsDYEstimation.root
    - THQDYEstimation.root
    - THWDYEstimation.root
    - TTGJetsDYEstimation.root
    - ttHJetTobbDYEstimation.root
    - ttHJetToNonbbDYEstimation.root
    - TTTo2L2NuDYEstimation.root
    - TTToHadronicDYEstimation.root
    - TTToSemiLeptonicDYEstimation.root
    - TTTTDYEstimation.root
    - TTWHDYEstimation.root
    - TTWJetsToLNuDYEstimation.root
    - TTWJetsToQQDYEstimation.root
    - TTWWDYEstimation.root
    - TTZHDYEstimation.root
    - TTZToLL_M-1to10DYEstimation.root
    - TTZToLLNuNu_M-10DYEstimation.root
    - TTZToQQDYEstimation.root
    - tZq_llDYEstimation.root
    - VBFHToBBDYEstimation.root
    - VBFHToGGDYEstimation.root
    - VBFHToMuMuDYEstimation.root
    - VBFHToTauTauDYEstimation.root
    - VBFHToWWTo2L2NuDYEstimation.root
    - VBFHToWWToLNuQQDYEstimation.root
    - VBFHToZZTo4LDYEstimation.root
    - VHToNonbbDYEstimation.root
    - W1JetsToLNuDYEstimation.root
    - W2JetsToLNuDYEstimation.root
    - W3JetsToLNuDYEstimation.root
    - W4JetsToLNuDYEstimation.root
    - WGToLNuGDYEstimation.root
    - WJetsToLNuDYEstimation.root
    - WJetsToLNu_HT-100To200DYEstimation.root
    - WJetsToLNu_HT-1200To2500DYEstimation.root
    - WJetsToLNu_HT-200To400DYEstimation.root
    - WJetsToLNu_HT-2500ToInfDYEstimation.root
    - WJetsToLNu_HT-400To600DYEstimation.root
    - WJetsToLNu_HT-600To800DYEstimation.root
    - WJetsToLNu_HT-70To100DYEstimation.root
    - WJetsToLNu_HT-800To1200DYEstimation.root
    - WminusH_HToBB_WToLNuDYEstimation.root
    - WplusH_HToBB_WToLNuDYEstimation.root
    - WpWpJJDYEstimation.root
    - WWTo2L2Nu_DoubleScatteringDYEstimation.root
    - WWTo2L2NuDYEstimation.root
    - WWToLNuQQDYEstimation.root
    - WWWDYEstimation.root
    - WWZDYEstimation.root
    - WZGDYEstimation.root
    - WZTo2L2QDYEstimation.root
    - WZTo3LNuDYEstimation.root
    - WZZDYEstimation.root
    - ZGTo2LGDYEstimation.root
    - ZH_HToBB_ZToLLDYEstimation.root
    - ZHToTauTauDYEstimation.root
    - ZZTo2L2QDYEstimation.root
    - ZZTo4LDYEstimation.root
    - ZZZDYEstimation.root

