data_obs: 
  legend: data
  type: data
  group: data
  files:
    - DoubleMuon_2018A.root
    - DoubleMuon_2018B.root
    - DoubleMuon_2018C.root
    - DoubleMuon_2018D.root
    - MuonEG_2018A.root
    - MuonEG_2018B.root
    - MuonEG_2018C.root
    - MuonEG_2018D.root
    - SingleMuon_2018A.root
    - SingleMuon_2018B.root
    - SingleMuon_2018C.root
    - SingleMuon_2018D.root
    - EGamma_2018A.root
    - EGamma_2018B.root
    - EGamma_2018C.root
    - EGamma_2018D.root


