
# for benchmarks, qqHH needs to be used as background
qqHH_CV_0p5_C2V_1_kl_1_hbbhwwdl:
  type: mc
  legend: HH bbWW VBF (CV 0.5 - C2V 1 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2VTo2L2Nu_CV_0_5_C2V_1_C3_1_dipoleRecoilOff.root
qqHH_CV_1p5_C2V_1_kl_1_hbbhwwdl:
  type: mc
  legend: HH bbWW VBF (CV 1.5 - C2V 1 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2VTo2L2Nu_CV_1_5_C2V_1_C3_1_dipoleRecoilOff.root
qqHH_CV_1_C2V_0_kl_1_hbbhwwdl:
  type: mc
  legend: HH bbWW VBF (CV 1 - C2V 0 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_0_C3_1_dipoleRecoilOff.root
qqHH_CV_1_C2V_1_kl_0_hbbhwwdl:
  type: mc
  legend: HH bbWW VBF (CV 1 - C2V 1 - C3 0) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_0_dipoleRecoilOff.root
qqHH_CV_1_C2V_1_kl_1_hbbhwwdl:
  type: mc
  legend: HH bbWW VBF (CV 1 - C2V 1 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_1_dipoleRecoilOff.root
qqHH_CV_1_C2V_1_kl_2_hbbhwwdl:
  type: mc
  legend: HH bbWW VBF (CV 1 - C2V 1 - C3 2) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_1_C3_2_dipoleRecoilOff.root
qqHH_CV_1_C2V_2_kl_1_hbbhwwdl:
  type: mc
  legend: HH bbWW VBF (CV 1 - C2V 2 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2VTo2L2Nu_CV_1_C2V_2_C3_1_dipoleRecoilOff.root


qqHH_CV_0p5_C2V_1_kl_1_hbbhtt:
  type: mc
  legend: HH bb#tau#tau VBF (CV 0.5 - C2V 1 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2Tau_CV_0_5_C2V_1_C3_1_dipoleRecoilOff.root
qqHH_CV_1p5_C2V_1_kl_1_hbbhtt:
  type: mc
  legend: HH bb#tau#tau VBF (CV 1.5 - C2V 1 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2Tau_CV_1_5_C2V_1_C3_1_dipoleRecoilOff.root
qqHH_CV_1_C2V_0_kl_1_hbbhtt:
  type: mc
  legend: HH bb#tau#tau VBF (CV 1 - C2V 0 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2Tau_CV_1_C2V_0_C3_1_dipoleRecoilOff.root
qqHH_CV_1_C2V_1_kl_0_hbbhtt:
  type: mc
  legend: HH bb#tau#tau VBF (CV 1 - C2V 1 - C3 0) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2Tau_CV_1_C2V_1_C3_0_dipoleRecoilOff.root
qqHH_CV_1_C2V_1_kl_1_hbbhtt:
  type: mc
  legend: HH bb#tau#tau VBF (CV 1 - C2V 1 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2Tau_CV_1_C2V_1_C3_1_dipoleRecoilOff.root
qqHH_CV_1_C2V_1_kl_2_hbbhtt:
  type: mc
  legend: HH bb#tau#tau VBF (CV 1 - C2V 1 - C3 2) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2Tau_CV_1_C2V_1_C3_2_dipoleRecoilOff.root
qqHH_CV_1_C2V_2_kl_1_hbbhtt:
  type: mc
  legend: HH bb#tau#tau VBF (CV 1 - C2V 2 - C3 1) 
  order: 14
  line-color: '#fc0505'
  line-type: 1
  files:
    - VBFHHTo2B2Tau_CV_1_C2V_2_C3_1_dipoleRecoilOff.root


