#################################
#        Miscellanious          #
#################################
#m_top_unc_HH:
#  proc:
#  # Non-resonant #
#  - ggHH_kl_1_kt_1_hbbhwwsl
#  - ggHH_kl_0_kt_1_hbbhwwsl
#  - ggHH_kl_5_kt_1_hbbhwwsl
#  - ggHH_kl_2p45_kt_1_hbbhwwsl
#  - ggHH_kl_1_kt_1_hbbhwwdl
#  - ggHH_kl_0_kt_1_hbbhwwdl
#  - ggHH_kl_5_kt_1_hbbhwwdl
#  - ggHH_kl_2p45_kt_1_hbbhwwdl
#  - ggHH_kl_1_kt_1_hbbhtt
#  - ggHH_kl_0_kt_1_hbbhtt
#  - ggHH_kl_5_kt_1_hbbhtt
#  - ggHH_kl_2p45_kt_1_hbbhtt
#  # Resonant #
#  - ggHH_M_250_hbbhwwdl
#  - ggHH_M_260_hbbhwwdl
#  - ggHH_M_270_hbbhwwdl
#  - ggHH_M_280_hbbhwwdl
#  - ggHH_M_300_hbbhwwdl
#  - ggHH_M_320_hbbhwwdl
#  - ggHH_M_350_hbbhwwdl
#  - ggHH_M_400_hbbhwwdl
#  - ggHH_M_450_hbbhwwdl
#  - ggHH_M_500_hbbhwwdl
#  - ggHH_M_550_hbbhwwdl
#  - ggHH_M_600_hbbhwwdl
#  - ggHH_M_650_hbbhwwdl
#  - ggHH_M_700_hbbhwwdl
#  - ggHH_M_750_hbbhwwdl
#  - ggHH_M_800_hbbhwwdl
#  - ggHH_M_850_hbbhwwdl
#  - ggHH_M_900_hbbhwwdl
#  - ggHH_M_250_hbbhtt
#  - ggHH_M_260_hbbhtt
#  - ggHH_M_270_hbbhtt
#  - ggHH_M_280_hbbhtt
#  - ggHH_M_300_hbbhtt
#  - ggHH_M_320_hbbhtt
#  - ggHH_M_350_hbbhtt
#  - ggHH_M_400_hbbhtt
#  - ggHH_M_450_hbbhtt
#  - ggHH_M_500_hbbhtt
#  - ggHH_M_550_hbbhtt
#  - ggHH_M_600_hbbhtt
#  - ggHH_M_650_hbbhtt
#  - ggHH_M_700_hbbhtt
#  - ggHH_M_750_hbbhtt
#  - ggHH_M_800_hbbhtt
#  - ggHH_M_850_hbbhtt
#  - ggHH_M_900_hbbhtt
#  - ggHH_M_250_hbbhwwsl
#  - ggHH_M_260_hbbhwwsl
#  - ggHH_M_270_hbbhwwsl
#  - ggHH_M_280_hbbhwwsl
#  - ggHH_M_300_hbbhwwsl
#  - ggHH_M_320_hbbhwwsl
#  - ggHH_M_350_hbbhwwsl
#  - ggHH_M_400_hbbhwwsl
#  - ggHH_M_450_hbbhwwsl
#  - ggHH_M_500_hbbhwwsl
#  - ggHH_M_550_hbbhwwsl
#  - ggHH_M_600_hbbhwwsl
#  - ggHH_M_650_hbbhwwsl
#  - ggHH_M_700_hbbhwwsl
#  - ggHH_M_750_hbbhwwsl
#  - ggHH_M_800_hbbhwwsl
#  - ggHH_M_850_hbbhwwsl
#  - ggHH_M_900_hbbhwwsl
#
#  val: 1.026

m_top_unc_tt:
  proc:
  - TT
  val: [0.973,1.028]

EW_corr_ttZ:
  proc:
  - ttZ
  val: [0.998,1.0]

EW_corr_ttW:
  proc:
  - ttW
  val: [0.968,1.0]

total_VVV: # cross section uncertainty
  proc: VVV
  val : [0.999,1.001]
#  https://cms-gen-dev.cern.ch/xsdb/?searchQuery=DAS=WWZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8




