#  https://gitlab.cern.ch/hh/naming-conventions#systematic-uncertainties

#################################
#              BR               # 
#################################
BR_hbb:
  proc: 
    # Single Higgs #
    - ggH_hbb
    - qqH_hbb
    - ttH_hbb
    - WH_hbb
    - ZH_hbb
    # Non-resonant GGF #
    - ggHH_kl_0_kt_1_hbbhwwdl
    - ggHH_kl_1_kt_1_hbbhwwdl
    - ggHH_kl_2p45_kt_1_hbbhwwdl
    - ggHH_kl_5_kt_1_hbbhwwdl
    - ggHH_kl_0_kt_1_hbbhtt
    - ggHH_kl_1_kt_1_hbbhtt
    - ggHH_kl_2p45_kt_1_hbbhtt
    - ggHH_kl_5_kt_1_hbbhtt
    - ggHH_kl_0_kt_1_hbbhwwsl
    - ggHH_kl_1_kt_1_hbbhwwsl
    - ggHH_kl_2p45_kt_1_hbbhwwsl
    - ggHH_kl_5_kt_1_hbbhwwsl
    # Non-resonant VBF #
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwdl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwdl
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1_C2V_0_kl_1_hbbhtt
    - qqHH_CV_1_C2V_1_kl_0_hbbhtt
    - qqHH_CV_1_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1_C2V_1_kl_2_hbbhtt
    - qqHH_CV_1_C2V_2_kl_1_hbbhtt
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwsl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwsl
    # Resonant #
    - ggHH_M_250_hbbhwwdl
    - ggHH_M_260_hbbhwwdl
    - ggHH_M_270_hbbhwwdl
    - ggHH_M_280_hbbhwwdl
    - ggHH_M_300_hbbhwwdl
    - ggHH_M_320_hbbhwwdl
    - ggHH_M_350_hbbhwwdl
    - ggHH_M_400_hbbhwwdl
    - ggHH_M_450_hbbhwwdl
    - ggHH_M_500_hbbhwwdl
    - ggHH_M_550_hbbhwwdl
    - ggHH_M_600_hbbhwwdl
    - ggHH_M_650_hbbhwwdl
    - ggHH_M_700_hbbhwwdl
    - ggHH_M_750_hbbhwwdl
    - ggHH_M_800_hbbhwwdl
    - ggHH_M_850_hbbhwwdl
    - ggHH_M_900_hbbhwwdl
    - ggHH_M_250_hbbhtt
    - ggHH_M_260_hbbhtt
    - ggHH_M_270_hbbhtt
    - ggHH_M_280_hbbhtt
    - ggHH_M_300_hbbhtt
    - ggHH_M_320_hbbhtt
    - ggHH_M_350_hbbhtt
    - ggHH_M_400_hbbhtt
    - ggHH_M_450_hbbhtt
    - ggHH_M_500_hbbhtt
    - ggHH_M_550_hbbhtt
    - ggHH_M_600_hbbhtt
    - ggHH_M_650_hbbhtt
    - ggHH_M_700_hbbhtt
    - ggHH_M_750_hbbhtt
    - ggHH_M_800_hbbhtt
    - ggHH_M_850_hbbhtt
    - ggHH_M_900_hbbhtt
    - ggHH_M_250_hbbhwwsl
    - ggHH_M_260_hbbhwwsl
    - ggHH_M_270_hbbhwwsl
    - ggHH_M_280_hbbhwwsl
    - ggHH_M_300_hbbhwwsl
    - ggHH_M_320_hbbhwwsl
    - ggHH_M_350_hbbhwwsl
    - ggHH_M_400_hbbhwwsl
    - ggHH_M_450_hbbhwwsl
    - ggHH_M_500_hbbhwwsl
    - ggHH_M_550_hbbhwwsl
    - ggHH_M_600_hbbhwwsl
    - ggHH_M_650_hbbhwwsl
    - ggHH_M_700_hbbhwwsl
    - ggHH_M_750_hbbhwwsl
    - ggHH_M_800_hbbhwwsl
    - ggHH_M_850_hbbhwwsl
    - ggHH_M_900_hbbhwwsl
  val : [0.9874,1.0124]

BR_hww:
  proc:
    # Single Higgs #
    - ggH_hww
    - qqH_hww
    - ttH_hww
    - ZH_hww
    - tHq_hww
    - tHW_hww
    - VH_hww
    # Non-resonant GGF #
    - ggHH_kl_0_kt_1_hbbhwwdl
    - ggHH_kl_1_kt_1_hbbhwwdl
    - ggHH_kl_2p45_kt_1_hbbhwwdl
    - ggHH_kl_5_kt_1_hbbhwwdl
    - ggHH_kl_0_kt_1_hbbhwwsl
    - ggHH_kl_1_kt_1_hbbhwwsl
    - ggHH_kl_2p45_kt_1_hbbhwwsl
    - ggHH_kl_5_kt_1_hbbhwwsl
    # Non-resonant VBF #
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwdl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwdl
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwsl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwsl
    # Resonant #
    - ggHH_M_250_hbbhwwdl
    - ggHH_M_260_hbbhwwdl
    - ggHH_M_270_hbbhwwdl
    - ggHH_M_280_hbbhwwdl
    - ggHH_M_300_hbbhwwdl
    - ggHH_M_320_hbbhwwdl
    - ggHH_M_350_hbbhwwdl
    - ggHH_M_400_hbbhwwdl
    - ggHH_M_450_hbbhwwdl
    - ggHH_M_500_hbbhwwdl
    - ggHH_M_550_hbbhwwdl
    - ggHH_M_600_hbbhwwdl
    - ggHH_M_650_hbbhwwdl
    - ggHH_M_700_hbbhwwdl
    - ggHH_M_750_hbbhwwdl
    - ggHH_M_800_hbbhwwdl
    - ggHH_M_850_hbbhwwdl
    - ggHH_M_900_hbbhwwdl
    - ggHH_M_250_hbbhwwsl
    - ggHH_M_260_hbbhwwsl
    - ggHH_M_270_hbbhwwsl
    - ggHH_M_280_hbbhwwsl
    - ggHH_M_300_hbbhwwsl
    - ggHH_M_320_hbbhwwsl
    - ggHH_M_350_hbbhwwsl
    - ggHH_M_400_hbbhwwsl
    - ggHH_M_450_hbbhwwsl
    - ggHH_M_500_hbbhwwsl
    - ggHH_M_550_hbbhwwsl
    - ggHH_M_600_hbbhwwsl
    - ggHH_M_650_hbbhwwsl
    - ggHH_M_700_hbbhwwsl
    - ggHH_M_750_hbbhwwsl
    - ggHH_M_800_hbbhwwsl
    - ggHH_M_850_hbbhwwsl
    - ggHH_M_900_hbbhwwsl
  val : [0.9848,1.0153]

BR_hzz: # bbww 2l contains both bbww and bbzz
  proc:
    # Single Higgs #
    - ggH_hzz
    - qqH_hzz
    # Non-resonant GGF #
    - ggHH_kl_0_kt_1_hbbhwwdl
    - ggHH_kl_1_kt_1_hbbhwwdl
    - ggHH_kl_2p45_kt_1_hbbhwwdl
    - ggHH_kl_5_kt_1_hbbhwwdl
    # Non-resonant VBF #
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwdl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwdl
    # Resonant #
    - ggHH_M_250_hbbhwwdl
    - ggHH_M_260_hbbhwwdl
    - ggHH_M_270_hbbhwwdl
    - ggHH_M_280_hbbhwwdl
    - ggHH_M_300_hbbhwwdl
    - ggHH_M_320_hbbhwwdl
    - ggHH_M_350_hbbhwwdl
    - ggHH_M_400_hbbhwwdl
    - ggHH_M_450_hbbhwwdl
    - ggHH_M_500_hbbhwwdl
    - ggHH_M_550_hbbhwwdl
    - ggHH_M_600_hbbhwwdl
    - ggHH_M_650_hbbhwwdl
    - ggHH_M_700_hbbhwwdl
    - ggHH_M_750_hbbhwwdl
    - ggHH_M_800_hbbhwwdl
    - ggHH_M_850_hbbhwwdl
    - ggHH_M_900_hbbhwwdl
  val : [0.9848,1.0153]

BR_htt:
  proc:
    # Non-resonant GGF #
    - ggHH_kl_0_kt_1_hbbhtt
    - ggHH_kl_1_kt_1_hbbhtt
    - ggHH_kl_2p45_kt_1_hbbhtt
    - ggHH_kl_5_kt_1_hbbhtt
    # Non-resonant VBF #
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1_C2V_0_kl_1_hbbhtt
    - qqHH_CV_1_C2V_1_kl_0_hbbhtt
    - qqHH_CV_1_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1_C2V_1_kl_2_hbbhtt
    - qqHH_CV_1_C2V_2_kl_1_hbbhtt
    # Resonant #
    - ggHH_M_250_hbbhtt
    - ggHH_M_260_hbbhtt
    - ggHH_M_270_hbbhtt
    - ggHH_M_280_hbbhtt
    - ggHH_M_300_hbbhtt
    - ggHH_M_320_hbbhtt
    - ggHH_M_350_hbbhtt
    - ggHH_M_400_hbbhtt
    - ggHH_M_450_hbbhtt
    - ggHH_M_500_hbbhtt
    - ggHH_M_550_hbbhtt
    - ggHH_M_600_hbbhtt
    - ggHH_M_650_hbbhtt
    - ggHH_M_700_hbbhtt
    - ggHH_M_750_hbbhtt
    - ggHH_M_800_hbbhtt
    - ggHH_M_850_hbbhtt
    - ggHH_M_900_hbbhtt
  val : [0.9837,1.0165]


