#################################
#         Ad hoc norm           # 
#################################
CMS_bbww_TT_norm:
  proc: 
    - ST
    - TT
  val: 1.2

CMS_bbwwdl_top_norm_boost:
  hist: 
   - HH_DL_boosted_GGF
   - HH_DL_boosted_H
   - HH_DL_boosted_DY_VVV
   - HH_DL_boosted_other
  proc: 
    - ST
    - TT
  val: 1.2


