  2016:
    - !include norm_lumi.yml
    - !include norm_BR.yml
    - !include norm_QCDscale.yml
    - !include norm_alpha_s.yml
    - !include norm_pdf.yml
    - !include norm_misc.yml
    - !include norm_DL_res_process.yml
    - !include norm_fakes_2016.yml
    - !include norm_DY_Res{branch}.yml
    - footer:
        - "nuisance edit rename TT * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
        - "nuisance edit rename DY * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_DY"
        - "nuisance edit rename TT * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
        - "nuisance edit rename DY * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_DY"
  2017:
    - !include norm_lumi.yml
    - !include norm_BR.yml
    - !include norm_QCDscale.yml
    - !include norm_alpha_s.yml
    - !include norm_pdf.yml
    - !include norm_misc.yml
    - !include norm_DL_res_process.yml
    - !include norm_fakes_2017.yml
    - !include norm_DY_Res{branch}.yml
    - footer:
        - "nuisance edit rename TT * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
        - "nuisance edit rename DY * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_DY"
        - "nuisance edit rename TT * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
        - "nuisance edit rename DY * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_DY"
  2018:
    - !include norm_lumi.yml
    - !include norm_BR.yml
    - !include norm_QCDscale.yml
    - !include norm_alpha_s.yml
    - !include norm_pdf.yml
    - !include norm_misc.yml
    - !include norm_DL_res_process.yml
    - !include norm_fakes_2018.yml
    - !include norm_DY_Res{branch}.yml
    - footer:
        - "nuisance edit rename TT * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
        - "nuisance edit rename DY * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_DY"
        - "nuisance edit rename TT * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
        - "nuisance edit rename DY * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_DY"



