#  https://gitlab.cern.ch/hh/naming-conventions#systematic-uncertainties

#################################
#              BR               # 
#################################
BR_hbb:
  proc: 
    # Single Higgs #
    - ggH_hbb
    - qqH_hbb
    - ttH_hbb
    - WH_hbb
    - ZH_hbb
    # Non-resonant GGF #
    - ggHH_kl_0_kt_1_hbbhwwdl
    - ggHH_kl_1_kt_1_hbbhwwdl
    - ggHH_kl_2p45_kt_1_hbbhwwdl
    - ggHH_kl_5_kt_1_hbbhwwdl
    - ggHH_kl_0_kt_1_hbbhtt
    - ggHH_kl_1_kt_1_hbbhtt
    - ggHH_kl_2p45_kt_1_hbbhtt
    - ggHH_kl_5_kt_1_hbbhtt
    - ggHH_kl_0_kt_1_hbbhwwsl
    - ggHH_kl_1_kt_1_hbbhwwsl
    - ggHH_kl_2p45_kt_1_hbbhwwsl
    - ggHH_kl_5_kt_1_hbbhwwsl
    # Non-resonant VBF #
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwdl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwdl
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1_C2V_0_kl_1_hbbhtt
    - qqHH_CV_1_C2V_1_kl_0_hbbhtt
    - qqHH_CV_1_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1_C2V_1_kl_2_hbbhtt
    - qqHH_CV_1_C2V_2_kl_1_hbbhtt
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwsl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwsl
    # Resonant #
    - signal_ggf_{spin}_250_hbbhwwdl
    - signal_ggf_{spin}_260_hbbhwwdl
    - signal_ggf_{spin}_270_hbbhwwdl
    - signal_ggf_{spin}_280_hbbhwwdl
    - signal_ggf_{spin}_300_hbbhwwdl
    - signal_ggf_{spin}_320_hbbhwwdl
    - signal_ggf_{spin}_350_hbbhwwdl
    - signal_ggf_{spin}_400_hbbhwwdl
    - signal_ggf_{spin}_450_hbbhwwdl
    - signal_ggf_{spin}_500_hbbhwwdl
    - signal_ggf_{spin}_550_hbbhwwdl
    - signal_ggf_{spin}_600_hbbhwwdl
    - signal_ggf_{spin}_650_hbbhwwdl
    - signal_ggf_{spin}_700_hbbhwwdl
    - signal_ggf_{spin}_750_hbbhwwdl
    - signal_ggf_{spin}_800_hbbhwwdl
    - signal_ggf_{spin}_850_hbbhwwdl
    - signal_ggf_{spin}_900_hbbhwwdl
    - signal_ggf_{spin}_250_hbbhtt
    - signal_ggf_{spin}_260_hbbhtt
    - signal_ggf_{spin}_270_hbbhtt
    - signal_ggf_{spin}_280_hbbhtt
    - signal_ggf_{spin}_300_hbbhtt
    - signal_ggf_{spin}_320_hbbhtt
    - signal_ggf_{spin}_350_hbbhtt
    - signal_ggf_{spin}_400_hbbhtt
    - signal_ggf_{spin}_450_hbbhtt
    - signal_ggf_{spin}_500_hbbhtt
    - signal_ggf_{spin}_550_hbbhtt
    - signal_ggf_{spin}_600_hbbhtt
    - signal_ggf_{spin}_650_hbbhtt
    - signal_ggf_{spin}_700_hbbhtt
    - signal_ggf_{spin}_750_hbbhtt
    - signal_ggf_{spin}_800_hbbhtt
    - signal_ggf_{spin}_850_hbbhtt
    - signal_ggf_{spin}_900_hbbhtt
    - signal_ggf_{spin}_250_hbbhwwsl
    - signal_ggf_{spin}_260_hbbhwwsl
    - signal_ggf_{spin}_270_hbbhwwsl
    - signal_ggf_{spin}_280_hbbhwwsl
    - signal_ggf_{spin}_300_hbbhwwsl
    - signal_ggf_{spin}_320_hbbhwwsl
    - signal_ggf_{spin}_350_hbbhwwsl
    - signal_ggf_{spin}_400_hbbhwwsl
    - signal_ggf_{spin}_450_hbbhwwsl
    - signal_ggf_{spin}_500_hbbhwwsl
    - signal_ggf_{spin}_550_hbbhwwsl
    - signal_ggf_{spin}_600_hbbhwwsl
    - signal_ggf_{spin}_650_hbbhwwsl
    - signal_ggf_{spin}_700_hbbhwwsl
    - signal_ggf_{spin}_750_hbbhwwsl
    - signal_ggf_{spin}_800_hbbhwwsl
    - signal_ggf_{spin}_850_hbbhwwsl
    - signal_ggf_{spin}_900_hbbhwwsl
  val : [0.9874,1.0124]

BR_hww:
  proc:
    # Single Higgs #
    - ggH_hww
    - qqH_hww
    - ttH_hww
    - ZH_hww
    - tHq_hww
    - tHW_hww
    - VH_hww
    # Non-resonant GGF #
    - ggHH_kl_0_kt_1_hbbhwwdl
    - ggHH_kl_1_kt_1_hbbhwwdl
    - ggHH_kl_2p45_kt_1_hbbhwwdl
    - ggHH_kl_5_kt_1_hbbhwwdl
    - ggHH_kl_0_kt_1_hbbhwwsl
    - ggHH_kl_1_kt_1_hbbhwwsl
    - ggHH_kl_2p45_kt_1_hbbhwwsl
    - ggHH_kl_5_kt_1_hbbhwwsl
    # Non-resonant VBF #
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwdl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwdl
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwsl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwsl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwsl
    # Resonant #
    - signal_ggf_{spin}_250_hbbhwwdl
    - signal_ggf_{spin}_260_hbbhwwdl
    - signal_ggf_{spin}_270_hbbhwwdl
    - signal_ggf_{spin}_280_hbbhwwdl
    - signal_ggf_{spin}_300_hbbhwwdl
    - signal_ggf_{spin}_320_hbbhwwdl
    - signal_ggf_{spin}_350_hbbhwwdl
    - signal_ggf_{spin}_400_hbbhwwdl
    - signal_ggf_{spin}_450_hbbhwwdl
    - signal_ggf_{spin}_500_hbbhwwdl
    - signal_ggf_{spin}_550_hbbhwwdl
    - signal_ggf_{spin}_600_hbbhwwdl
    - signal_ggf_{spin}_650_hbbhwwdl
    - signal_ggf_{spin}_700_hbbhwwdl
    - signal_ggf_{spin}_750_hbbhwwdl
    - signal_ggf_{spin}_800_hbbhwwdl
    - signal_ggf_{spin}_850_hbbhwwdl
    - signal_ggf_{spin}_900_hbbhwwdl
    - signal_ggf_{spin}_250_hbbhwwsl
    - signal_ggf_{spin}_260_hbbhwwsl
    - signal_ggf_{spin}_270_hbbhwwsl
    - signal_ggf_{spin}_280_hbbhwwsl
    - signal_ggf_{spin}_300_hbbhwwsl
    - signal_ggf_{spin}_320_hbbhwwsl
    - signal_ggf_{spin}_350_hbbhwwsl
    - signal_ggf_{spin}_400_hbbhwwsl
    - signal_ggf_{spin}_450_hbbhwwsl
    - signal_ggf_{spin}_500_hbbhwwsl
    - signal_ggf_{spin}_550_hbbhwwsl
    - signal_ggf_{spin}_600_hbbhwwsl
    - signal_ggf_{spin}_650_hbbhwwsl
    - signal_ggf_{spin}_700_hbbhwwsl
    - signal_ggf_{spin}_750_hbbhwwsl
    - signal_ggf_{spin}_800_hbbhwwsl
    - signal_ggf_{spin}_850_hbbhwwsl
    - signal_ggf_{spin}_900_hbbhwwsl
  val : [0.9848,1.0153]

BR_hzz: # bbww 2l contains both bbww and bbzz
  proc:
    # Single Higgs #
    - ggH_hzz
    - qqH_hzz
    # Non-resonant GGF #
    - ggHH_kl_0_kt_1_hbbhwwdl
    - ggHH_kl_1_kt_1_hbbhwwdl
    - ggHH_kl_2p45_kt_1_hbbhwwdl
    - ggHH_kl_5_kt_1_hbbhwwdl
    # Non-resonant VBF #
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_0_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_0_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_1_hbbhwwdl
    - qqHH_CV_1_C2V_1_kl_2_hbbhwwdl
    - qqHH_CV_1_C2V_2_kl_1_hbbhwwdl
    # Resonant #
    - signal_ggf_{spin}_250_hbbhwwdl
    - signal_ggf_{spin}_260_hbbhwwdl
    - signal_ggf_{spin}_270_hbbhwwdl
    - signal_ggf_{spin}_280_hbbhwwdl
    - signal_ggf_{spin}_300_hbbhwwdl
    - signal_ggf_{spin}_320_hbbhwwdl
    - signal_ggf_{spin}_350_hbbhwwdl
    - signal_ggf_{spin}_400_hbbhwwdl
    - signal_ggf_{spin}_450_hbbhwwdl
    - signal_ggf_{spin}_500_hbbhwwdl
    - signal_ggf_{spin}_550_hbbhwwdl
    - signal_ggf_{spin}_600_hbbhwwdl
    - signal_ggf_{spin}_650_hbbhwwdl
    - signal_ggf_{spin}_700_hbbhwwdl
    - signal_ggf_{spin}_750_hbbhwwdl
    - signal_ggf_{spin}_800_hbbhwwdl
    - signal_ggf_{spin}_850_hbbhwwdl
    - signal_ggf_{spin}_900_hbbhwwdl
  val : [0.9848,1.0153]

BR_htt:
  proc:
    # Non-resonant GGF #
    - ggHH_kl_0_kt_1_hbbhtt
    - ggHH_kl_1_kt_1_hbbhtt
    - ggHH_kl_2p45_kt_1_hbbhtt
    - ggHH_kl_5_kt_1_hbbhtt
    # Non-resonant VBF #
    - qqHH_CV_0p5_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1p5_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1_C2V_0_kl_1_hbbhtt
    - qqHH_CV_1_C2V_1_kl_0_hbbhtt
    - qqHH_CV_1_C2V_1_kl_1_hbbhtt
    - qqHH_CV_1_C2V_1_kl_2_hbbhtt
    - qqHH_CV_1_C2V_2_kl_1_hbbhtt
    # Resonant #
    - signal_ggf_{spin}_250_hbbhtt
    - signal_ggf_{spin}_260_hbbhtt
    - signal_ggf_{spin}_270_hbbhtt
    - signal_ggf_{spin}_280_hbbhtt
    - signal_ggf_{spin}_300_hbbhtt
    - signal_ggf_{spin}_320_hbbhtt
    - signal_ggf_{spin}_350_hbbhtt
    - signal_ggf_{spin}_400_hbbhtt
    - signal_ggf_{spin}_450_hbbhtt
    - signal_ggf_{spin}_500_hbbhtt
    - signal_ggf_{spin}_550_hbbhtt
    - signal_ggf_{spin}_600_hbbhtt
    - signal_ggf_{spin}_650_hbbhtt
    - signal_ggf_{spin}_700_hbbhtt
    - signal_ggf_{spin}_750_hbbhtt
    - signal_ggf_{spin}_800_hbbhtt
    - signal_ggf_{spin}_850_hbbhtt
    - signal_ggf_{spin}_900_hbbhtt
  val : [0.9837,1.0165]


