CMS_bbwwdl_fakes_norm_boosted_DY_VVV_2016:
  hist: HH_DL_boosted_DY_VVV
  proc: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_resolved_DY_VVV_2016:
  hist: HH_DL_resolved_DY_VVV
  proc: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_boosted_other_2016:
  hist: HH_DL_boosted_other
  proc: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_resolved_other_2016:
  hist: HH_DL_resolved_other
  proc: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_boosted_GGF_2016:
  hist: HH_DL_boosted_GGF
  proc: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_resolved1b_GGF_2016:
  hist: HH_DL_resolved1b_GGF
  proc: Fakes
  val: 1.3
CMS_bbwwdl_fakes_norm_resolved2b_GGF_2016:
  hist: HH_DL_resolved2b_GGF
  proc: Fakes
  val: 1.3
