#################################
#         Ad hoc norm           # 
#################################
CMS_bbww_TT_norm:
  proc: 
    - TT
  val: 1.2

CMS_bbww_ST_norm:
  proc: 
    - ST
  val: 1.2

CMS_bbww_WJets_norm:
  proc: 
    - WJets
  val: 1.2

CMS_bbwwsl_fakes_norm:
  proc:
    - Fakes
  val: 1.3

CMS_bbwwsl_ST_norm_boost:
  hist: 
    - HH_DL_boosted_GGF
    - HH_DL_boosted_VBF
    - HH_DL_boosted_Top
  proc: 
    - ST
  val: 1.2

CMS_bbwwsl_TT_norm_boost:
  hist: 
    - HH_DL_boosted_GGF
    - HH_DL_boosted_VBF
    - HH_DL_boosted_Top
  proc: 
    - TT
  val: 1.2

