#################################
#        Miscellanious          #
#################################
#m_top_unc_HH:
#  proc:
#  # Non-resonant #
#  - ggHH_kl_1_kt_1_hbbhwwsl
#  - ggHH_kl_0_kt_1_hbbhwwsl
#  - ggHH_kl_5_kt_1_hbbhwwsl
#  - ggHH_kl_2p45_kt_1_hbbhwwsl
#  - ggHH_kl_1_kt_1_hbbhwwdl
#  - ggHH_kl_0_kt_1_hbbhwwdl
#  - ggHH_kl_5_kt_1_hbbhwwdl
#  - ggHH_kl_2p45_kt_1_hbbhwwdl
#  - ggHH_kl_1_kt_1_hbbhtt
#  - ggHH_kl_0_kt_1_hbbhtt
#  - ggHH_kl_5_kt_1_hbbhtt
#  - ggHH_kl_2p45_kt_1_hbbhtt
#  # Resonant #
#  - signal_ggf_{spin}_250_hbbhwwdl
#  - signal_ggf_{spin}_260_hbbhwwdl
#  - signal_ggf_{spin}_270_hbbhwwdl
#  - signal_ggf_{spin}_280_hbbhwwdl
#  - signal_ggf_{spin}_300_hbbhwwdl
#  - signal_ggf_{spin}_320_hbbhwwdl
#  - signal_ggf_{spin}_350_hbbhwwdl
#  - signal_ggf_{spin}_400_hbbhwwdl
#  - signal_ggf_{spin}_450_hbbhwwdl
#  - signal_ggf_{spin}_500_hbbhwwdl
#  - signal_ggf_{spin}_550_hbbhwwdl
#  - signal_ggf_{spin}_600_hbbhwwdl
#  - signal_ggf_{spin}_650_hbbhwwdl
#  - signal_ggf_{spin}_700_hbbhwwdl
#  - signal_ggf_{spin}_750_hbbhwwdl
#  - signal_ggf_{spin}_800_hbbhwwdl
#  - signal_ggf_{spin}_850_hbbhwwdl
#  - signal_ggf_{spin}_900_hbbhwwdl
#  - signal_ggf_{spin}_250_hbbhtt
#  - signal_ggf_{spin}_260_hbbhtt
#  - signal_ggf_{spin}_270_hbbhtt
#  - signal_ggf_{spin}_280_hbbhtt
#  - signal_ggf_{spin}_300_hbbhtt
#  - signal_ggf_{spin}_320_hbbhtt
#  - signal_ggf_{spin}_350_hbbhtt
#  - signal_ggf_{spin}_400_hbbhtt
#  - signal_ggf_{spin}_450_hbbhtt
#  - signal_ggf_{spin}_500_hbbhtt
#  - signal_ggf_{spin}_550_hbbhtt
#  - signal_ggf_{spin}_600_hbbhtt
#  - signal_ggf_{spin}_650_hbbhtt
#  - signal_ggf_{spin}_700_hbbhtt
#  - signal_ggf_{spin}_750_hbbhtt
#  - signal_ggf_{spin}_800_hbbhtt
#  - signal_ggf_{spin}_850_hbbhtt
#  - signal_ggf_{spin}_900_hbbhtt
#  - signal_ggf_{spin}_250_hbbhwwsl
#  - signal_ggf_{spin}_260_hbbhwwsl
#  - signal_ggf_{spin}_270_hbbhwwsl
#  - signal_ggf_{spin}_280_hbbhwwsl
#  - signal_ggf_{spin}_300_hbbhwwsl
#  - signal_ggf_{spin}_320_hbbhwwsl
#  - signal_ggf_{spin}_350_hbbhwwsl
#  - signal_ggf_{spin}_400_hbbhwwsl
#  - signal_ggf_{spin}_450_hbbhwwsl
#  - signal_ggf_{spin}_500_hbbhwwsl
#  - signal_ggf_{spin}_550_hbbhwwsl
#  - signal_ggf_{spin}_600_hbbhwwsl
#  - signal_ggf_{spin}_650_hbbhwwsl
#  - signal_ggf_{spin}_700_hbbhwwsl
#  - signal_ggf_{spin}_750_hbbhwwsl
#  - signal_ggf_{spin}_800_hbbhwwsl
#  - signal_ggf_{spin}_850_hbbhwwsl
#  - signal_ggf_{spin}_900_hbbhwwsl
#
#  val: 1.026

m_top_unc_tt:
  proc:
  - TT
  val: [0.973,1.028]

EW_corr_ttZ:
  proc:
  - ttZ
  val: [0.998,1.0]

EW_corr_ttW:
  proc:
  - ttW
  val: [0.968,1.0]

total_VVV: # cross section uncertainty
  proc: VVV
  val : [0.999,1.001]
#  https://cms-gen-dev.cern.ch/xsdb/?searchQuery=DAS=WWZ_TuneCUETP8M1_13TeV-amcatnlo-pythia8




