#################################
#            alpha_s            # 
#################################

alpha_s:
  - proc:
    - ggH_hww
    - ggH_hbb
    - ggH_hgg
    - ggH_hmm
    - ggH_htt
    - ggH_hww
    - ggH_hzz
    val: 1.026
  - proc:
    - qqH_hww
    - qqH_hbb
    - qqH_hgg
    - qqH_hmm
    - qqH_htt
    - qqH_hww
    - qqH_hzz
    val: 1.005
  - proc:
    - ZH_hbb
    - ZH_htt
    - ZH_hww
    - VH_hww
    val: 1.009
  - proc:
    - WH_hbb
    val: 1.009
  - proc:
    - ttH_hbb
    - ttH_hww
    val: 1.02
  - proc:
    - tHq_hww
    val: 1.012
  - proc:
    - tHW_hww
    val: 1.015

alpha_s_ggHH: 
  proc:
  # Non-resonant #
  - ggHH_kl_1_kt_1_hbbhwwsl
  - ggHH_kl_0_kt_1_hbbhwwsl
  - ggHH_kl_5_kt_1_hbbhwwsl
  - ggHH_kl_2p45_kt_1_hbbhwwsl
  - ggHH_kl_1_kt_1_hbbhwwdl
  - ggHH_kl_0_kt_1_hbbhwwdl
  - ggHH_kl_5_kt_1_hbbhwwdl
  - ggHH_kl_2p45_kt_1_hbbhwwdl
  - ggHH_kl_1_kt_1_hbbhtt
  - ggHH_kl_0_kt_1_hbbhtt
  - ggHH_kl_5_kt_1_hbbhtt
  - ggHH_kl_2p45_kt_1_hbbhtt
  # Resonant #
  - ggHH_M_250_hbbhwwdl
  - ggHH_M_260_hbbhwwdl
  - ggHH_M_270_hbbhwwdl
  - ggHH_M_280_hbbhwwdl
  - ggHH_M_300_hbbhwwdl
  - ggHH_M_320_hbbhwwdl
  - ggHH_M_350_hbbhwwdl
  - ggHH_M_400_hbbhwwdl
  - ggHH_M_450_hbbhwwdl
  - ggHH_M_500_hbbhwwdl
  - ggHH_M_550_hbbhwwdl
  - ggHH_M_600_hbbhwwdl
  - ggHH_M_650_hbbhwwdl
  - ggHH_M_700_hbbhwwdl
  - ggHH_M_750_hbbhwwdl
  - ggHH_M_800_hbbhwwdl
  - ggHH_M_850_hbbhwwdl
  - ggHH_M_900_hbbhwwdl
  - ggHH_M_250_hbbhtt
  - ggHH_M_260_hbbhtt
  - ggHH_M_270_hbbhtt
  - ggHH_M_280_hbbhtt
  - ggHH_M_300_hbbhtt
  - ggHH_M_320_hbbhtt
  - ggHH_M_350_hbbhtt
  - ggHH_M_400_hbbhtt
  - ggHH_M_450_hbbhtt
  - ggHH_M_500_hbbhtt
  - ggHH_M_550_hbbhtt
  - ggHH_M_600_hbbhtt
  - ggHH_M_650_hbbhtt
  - ggHH_M_700_hbbhtt
  - ggHH_M_750_hbbhtt
  - ggHH_M_800_hbbhtt
  - ggHH_M_850_hbbhtt
  - ggHH_M_900_hbbhtt
  - ggHH_M_250_hbbhwwsl
  - ggHH_M_260_hbbhwwsl
  - ggHH_M_270_hbbhwwsl
  - ggHH_M_280_hbbhwwsl
  - ggHH_M_300_hbbhwwsl
  - ggHH_M_320_hbbhwwsl
  - ggHH_M_350_hbbhwwsl
  - ggHH_M_400_hbbhwwsl
  - ggHH_M_450_hbbhwwsl
  - ggHH_M_500_hbbhwwsl
  - ggHH_M_550_hbbhwwsl
  - ggHH_M_600_hbbhwwsl
  - ggHH_M_650_hbbhwwsl
  - ggHH_M_700_hbbhwwsl
  - ggHH_M_750_hbbhwwsl
  - ggHH_M_800_hbbhwwsl
  - ggHH_M_850_hbbhwwsl
  - ggHH_M_900_hbbhwwsl
  val: 1.021

# no alpha_s_qqHH -> taken into account in pdf_qqHH


