- "nuisance edit rename TT * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
- "nuisance edit rename DY * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_DY"
- "nuisance edit rename TT * CMS_bbwwdl_PS_FSR CMS_bbwwdl_PS_FSR_TT"
- "nuisance edit rename DY * CMS_bbwwdl_PS_ISR CMS_bbwwdl_PS_ISR_DY"
- "nuisance edit rename TT * CMS_bbwwdl_thu_shape CMS_bbwwdl_thu_shape_TT"
- "nuisance edit rename DY * CMS_bbwwdl_thu_shape CMS_bbwwdl_thu_shape_DY"
