bin_name_original       : 'none'
datacard_original       : 'none'
merged_eras_fit         : False
minY                    : 0.001
maxY                    : 10000000000000.
useLogPlot              : True
labelX                  : 'MVA bin #'
number_columns_legend   : 3
minYerr                 : -0.6
maxYerr                 : 0.6
cats_labels_height      : 5000000.
