HH_DL_resolved1b_GGF:
  method: rebinlinearize2d
  params: 
    - y
    - Quantile
    - [*quantHME]
    - Threshold
    - [*thresh,[TT,ST,DY],3,0.3]
    - [ggHH_M_base_hbbhwwdl,ggHH_M_base_hbbhtt]
HH_DL_resolved2b_GGF:
  method: rebinlinearize2d
  params: 
    - y
    - Quantile
    - [*quantHME]
    - Threshold
    - [*thresh,[TT,ST,DY],3,0.3]
    - [ggHH_M_base_hbbhwwdl,ggHH_M_base_hbbhtt]
HH_DL_boosted_GGF:
  method: rebinlinearize2d
  params: 
    - y
    - Quantile
    - [*quantHME]
    - Threshold
    - [*thresh,[TT,ST,DY],3,0.5]
    - [ggHH_M_base_hbbhwwdl,ggHH_M_base_hbbhtt]


HH_DL_resolved2b_H:
  method : quantile
  params : [*quant, *back]
HH_DL_resolved1b_H:
  method : quantile
  params : [*quant, *back]
HH_DL_boosted_H:
  method : quantile
  params : [[0.,0.33,0.66,1.], *back]

HH_DL_resolved_DY_VVV:
  method : quantile
  params : [*quant, *back]
HH_DL_boosted_DY_VVV:
  method : quantile
  params : [*quant, *back]
HH_DL_inclusive_other:
  method : quantile
  params : [*quant, *back]

