HH_resolved1b_GGF:
  method: threshold
  params: 
    - *thresh
    - [ggHH_M_base_hbbhwwdl,ggHH_M_base_hbbhtt]
    - [TT,ST,DY]
    - 20
    - 0.1
HH_resolved2b_GGF:
  method: threshold
  params:
    - *thresh
    - [ggHH_M_base_hbbhwwdl,ggHH_M_base_hbbhtt]
    - [TT,ST,DY]
    - 20
    - 0.1
HH_boosted_GGF:
  method: threshold
  params:
    - *thresh
    - [ggHH_M_base_hbbhwwdl,ggHH_M_base_hbbhtt]
    - [TT,ST,DY]
    - 20
    - 0.2

HH_resolved2b_H:
  method : quantile
  params : [*quant, *back]
HH_resolved1b_H:
  method : quantile
  params : [*quant, *back]
HH_boosted_H:
  method : quantile
  params : [[0.,0.33,0.66,1.], *back]

HH_resolved_DY_VVV:
  method : quantile
  params : [*quant, *back]
HH_boosted_DY_VVV:
  method : quantile
  params : [*quant, *back]
HH_inclusive_other:
  method : quantile
  params : [*quant, *back]

