# PDF #
Fact:   scale_muF
Renorm: scale_muR
Mixed:  discard

# PS #
psFSR: CMS_bbwwsl_PS_FSR
psISR: CMS_bbwwsl_PS_ISR

# Basics #
L1PreFiring:        CMS_l1_ecal_prefiring_{era}
pileup:             CMS_pileup_{era}
ttbarweightsyst:    CMS_top_pT_reweighting

# Btag SF #
btagSF_:            CMS_btag_subjet_{era}
    # HF, LF, cferr1 and cferr2 are correlated across years
btagSF_cferr1:      CMS_btag_cferr1_2016_2017_2018
btagSF_cferr2:      CMS_btag_cferr2_2016_2017_2018
btagSF_hf:          CMS_btag_HF_2016_2017_2018
btagSF_lf:          CMS_btag_LF_2016_2017_2018

    # {hf,lf}stats{1,2} uncorrelated across eras
btagSF_hfstats1:    CMS_btag_hfstats1_{era}
btagSF_hfstats2:    CMS_btag_hfstats2_{era}
btagSF_lfstats1:    CMS_btag_lfstats1_{era}
btagSF_lfstats2:    CMS_btag_lfstats2_{era}

# Trigger SF #
ttH_singleMuon_trigSF:      CMS_bbwwsl_TriggerWeight_e_{era}
ttH_singleElectron_trigSF:  CMS_bbwwsl_TriggerWeight_m_{era}

# Lepton SF #
el_looseeff:            CMS_eff_e_id_loose01_{era}
el_looseid:             CMS_eff_e_id_loose02_{era}
el_loosereco:           CMS_eff_e_reco_{era}
el_tightmva:            CMS_eff_e_id_tth_{era}

mu_loose:       CMS_eff_m_idiso_{era}
mu_tightmva:    CMS_eff_m_id_tth_{era}

# FakeRates #
el_FR_Loose_SL_pt_syst:     CMS_bbwwsl_FakeRate_e_pt_{era}
el_FR_Loose_SL_barrel_syst: CMS_bbwwsl_FakeRate_e_barrel_{era}
el_FR_Loose_SL_norm_syst:   CMS_bbwwsl_FakeRate_e_norm_{era}
mu_FR_Loose_SL_pt_syst:     CMS_bbwwsl_FakeRate_m_pt_{era}
mu_FR_Loose_SL_barrel_syst: CMS_bbwwsl_FakeRate_m_barrel_{era}
mu_FR_Loose_SL_norm_syst:   CMS_bbwwsl_FakeRate_m_norm_{era}

# jes/jer
jer:                    CMS_JER_{era}

jmr:                    CMS_JMR_{era}
jms:                    CMS_JMS_{era}
jesTotal:               CMS_JES_Total
    # -> fatjets
unclustEn:              CMS_unclusteredEnergy_{era}
    # -> Met 

jesAbsolute:            CMS_JES_Abs
jesBBEC1:               CMS_JES_BBEC1
jesEC2:                 CMS_JES_EC2
jesHF:                  CMS_JES_HF
jesRelativeBal:         CMS_JES_RelBal
jesFlavorQCD:           CMS_JES_FlavQCD
jesHEMIssue:            CMS_JES_HEMIssue


jesAbsolute_2016:       CMS_JES_Abs_2016
jesBBEC1_2016:          CMS_JES_BBEC1_2016
jesEC2_2016:            CMS_JES_EC2_2016
jesHF_2016:             CMS_JES_HF_2016
jesRelativeSample_2016: CMS_JES_RelSample_2016

jesAbsolute_2017:       CMS_JES_Abs_2017
jesBBEC1_2017:          CMS_JES_BBEC1_2017
jesEC2_2017:            CMS_JES_EC2_2017
jesHF_2017:             CMS_JES_HF_2017
jesRelativeSample_2017: CMS_JES_RelSample_2017

jesAbsolute_2018:       CMS_JES_Abs_2018
jesBBEC1_2018:          CMS_JES_BBEC1_2018
jesEC2_2018:            CMS_JES_EC2_2018
jesHF_2018:             CMS_JES_HF_2018
jesRelativeSample_2018: CMS_JES_RelSample_2018

# Jet PU ID #
jetpuid_eff:            CMS_PUJET_eff_{era}
jetpuid_mistag:         CMS_PUJET_mistag_{era}

# Fake non closure #
fake_nc_e_res1b_GGF_nom:        CMS_bbwwsl_FakeRate_nc_nom_e_res1b_GGF
fake_nc_e_res1b_GGF_slope:      CMS_bbwwsl_FakeRate_nc_slope_mu_res1b_GGF
fake_nc_m_res1b_GGF_nom:        CMS_bbwwsl_FakeRate_nc_nom_mu_res1b_GGF
fake_nc_m_res1b_GGF_slope:      CMS_bbwwsl_FakeRate_nc_slope_mu_res1b_GGF
fake_nc_e_res1b_VBF_nom:        CMS_bbwwsl_FakeRate_nc_nom_e_res1b_VBF
fake_nc_e_res1b_VBF_slope:      CMS_bbwwsl_FakeRate_nc_slope_e_res1b_VBF
fake_nc_m_res1b_VBF_nom:        CMS_bbwwsl_FakeRate_nc_nom_mu_res1b_VBF
fake_nc_m_res1b_VBF_slope:      CMS_bbwwsl_FakeRate_nc_slope_mu_res1b_VBF
fake_nc_e_res2b_GGF_nom:        CMS_bbwwsl_FakeRate_nc_nom_e_res2b_GGF
fake_nc_e_res2b_GGF_slope:      CMS_bbwwsl_FakeRate_nc_slope_e_res2b_GGF
fake_nc_m_res2b_GGF_nom:        CMS_bbwwsl_FakeRate_nc_nom_mu_res2b_GGF
fake_nc_m_res2b_GGF_slope:      CMS_bbwwsl_FakeRate_nc_slope_mu_res2b_GGF
fake_nc_e_res2b_VBF_nom:        CMS_bbwwsl_FakeRate_nc_nom_e_res2b_VBF
fake_nc_e_res2b_VBF_slope:      CMS_bbwwsl_FakeRate_nc_slope_e_res2b_VBF
fake_nc_m_res2b_VBF_nom:        CMS_bbwwsl_FakeRate_nc_nom_mu_res2b_VBF
fake_nc_m_res2b_VBF_slope:      CMS_bbwwsl_FakeRate_nc_slope_mu_res2b_VBF
fake_nc_e_boosted_GGF_nom:      CMS_bbwwsl_FakeRate_nc_nom_e_boosted_GGF
fake_nc_e_boosted_GGF_slope:    CMS_bbwwsl_FakeRate_nc_slope_e_boosted_GGF
fake_nc_m_boosted_GGF_nom:      CMS_bbwwsl_FakeRate_nc_nom_mu_boosted_GGF
fake_nc_m_boosted_GGF_slope:    CMS_bbwwsl_FakeRate_nc_slope_mu_boosted_GGF
fake_nc_e_boosted_VBF_nom:      CMS_bbwwsl_FakeRate_nc_nom_e_boosted_VBF
fake_nc_e_boosted_VBF_slope:    CMS_bbwwsl_FakeRate_nc_slope_e_boosted_VBF
fake_nc_m_boosted_VBF_nom:      CMS_bbwwsl_FakeRate_nc_nom_mu_boosted_VBF
fake_nc_m_boosted_VBF_slope:    CMS_bbwwsl_FakeRate_nc_slope_mu_boosted_VBF
fake_nc_e_inc_wjets_nom:        CMS_bbwwsl_FakeRate_nc_nom_e_inc_wjets
fake_nc_e_inc_wjets_slope:      CMS_bbwwsl_FakeRate_nc_slope_e_inc_wjets
fake_nc_m_inc_wjets_nom:        CMS_bbwwsl_FakeRate_nc_nom_mu_inc_wjets
fake_nc_m_inc_wjets_slope:      CMS_bbwwsl_FakeRate_nc_slope_mu_inc_wjets
fake_nc_e_inc_otherh_nom:       CMS_bbwwsl_FakeRate_nc_nom_e_inc_otherh
fake_nc_e_inc_otherh_slope:     CMS_bbwwsl_FakeRate_nc_slope_e_inc_otherh
fake_nc_m_inc_otherh_nom:       CMS_bbwwsl_FakeRate_nc_nom_mu_inc_otherh
fake_nc_m_inc_otherh_slope:     CMS_bbwwsl_FakeRate_nc_slope_mu_inc_otherh
fake_nc_e_res_top_nom:          CMS_bbwwsl_FakeRate_nc_nom_e_res_top
fake_nc_e_res_top_slope:        CMS_bbwwsl_FakeRate_nc_slope_e_res_top
fake_nc_m_res_top_nom:          CMS_bbwwsl_FakeRate_nc_nom_mu_res_top
fake_nc_m_res_top_slope:        CMS_bbwwsl_FakeRate_nc_slope_mu_res_top
fake_nc_e_boosted_top_nom:      CMS_bbwwsl_FakeRate_nc_nom_e_boosted_top
fake_nc_e_boosted_top_slope:    CMS_bbwwsl_FakeRate_nc_slope_e_boosted_top
fake_nc_m_boosted_top_nom:      CMS_bbwwsl_FakeRate_nc_nom_mu_boosted_top
fake_nc_m_boosted_top_slope:    CMS_bbwwsl_FakeRate_nc_slope_mu_boosted_top
