thresholds: &thresh [586, 539, 494, 451, 410, 371, 334, 299, 266, 235, 206, 179, 154, 131, 110,  91,  74,  59,  46,  35,  26,  19,  14,  11,  10]
quantiles : &quant [0., 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.]

singleH: &singleH [ggH_hbb,ggH_hgg,ggH_hmm,ggH_htt,ggH_hww,ggH_hzz,qqH_hbb,qqH_hgg,qqH_hmm,qqH_htt,qqH_hww,qqH_hzz,ttH_hbb,ttH_hww,WH_hbb,ZH_hbb,ZH_htt,ZH_hww,SM H_hww,SM H_hww,VH_hww]
backgrounds : &back [TT,ST,DY,WJets,VV,VVV,Other_bbWW,Fakes,ggH_hbb,ggH_hgg,ggH_hmm,ggH_htt,ggH_hww,ggH_hzz,qqH_hbb,qqH_hgg,qqH_hmm,qqH_htt,qqH_hww,qqH_hzz,ttH_hbb,ttH_hww,WH_hbb,ZH_hbb,ZH_htt,ZH_hww,SM H_hww,SM H_hww,VH_hww]


HH_resolved1b_GGF:
  method : threshold 
  params : [*thresh,*back,[TT,ST,DY]]
HH_resolved2b_GGF:
  method : threshold 
  params : [*thresh,*back,[TT,ST,DY]]
HH_boosted_GGF:
  method : threshold 
  params : [*thresh,*back,[TT,ST,DY]]

HH_resolved1b_VBF:
  method : threshold 
  params : [*thresh,*back,[TT,ST,DY]]
HH_resolved2b_VBF:
  method : threshold 
  params : [*thresh,*back,[TT,ST,DY]]
HH_boosted_VBF:
  method : threshold 
  params : [*thresh,*back,[TT,ST,DY]]

HH_resolved2b_H:
  method : quantile
  params : [*quant, *back]
HH_resolved1b_H:
  method : quantile
  params : [*quant, *back]
HH_boosted_H:
  method : quantile
  params : [*quant, *back]

HH_resolved_DY_VVV:
  method : quantile
  params : [*quant, [DY,VV,VVV]]
HH_boosted_DY_VVV:
  method : quantile
  params : [*quant, [DY,VV,VVV]]
HH_inclusive_other:
  method : quantile
  params : [*quant, [TT,ST,WJets,Other_bbWW]]



